thoth-station/thoth-application

- overlays/test/imageStreamTags.yaml
- overlays/test/kustomization.yaml
> set latest->v0.6.0-dev

- adviser/README.md
- adviser/base/argo-workflows/finished-webhook.yaml
- adviser/base/imagestream.yaml
- adviser/overlays/test/imagestreamtag.yaml
Update trigger finished wehook removing Python script and using workflow-helpers image
> Use workflow helpers for trigger finished webhook

- core/overlays/test/kustomization.yaml
- core/overlays/test/postgresql.yaml
> added persistance to postgresql

- init-job/base/argo-workflows/initialize-schema.yaml
- init-job/base/argo-workflows/register-indexes.yaml
- init-job/base/argo-workflows/solve-core-packages.yaml
- init-job/base/argo-workflows/solve-data-science-packages.yaml
Add missing service accounts and add env variables for logging
> Add service accounts and variables

- adviser/base/argo-workflows/trigger-integration.yaml
- adviser/base/kustomization.yaml
- adviser/base/openshift-templates/adviser.yaml
Introduce trigger integration task
> Add trigger-integration

- unresolved-package-handler/base/deploymentconfig.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/20
Correct key in DC.
> Correct DC

- adviser/base/openshift-templates/adviser.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
> Keep wf for SLI

- core/overlays/quicklab/configmaps.yaml
- core/overlays/stage/configmaps.yaml
- core/overlays/test/configmaps.yaml
- metrics-exporter/base/deploymentconfig.yaml
Depends-On: https://github.com/thoth-station/metrics-exporter/issues/426
Remove variables for metrics-exporter
> Remove variables from metrics-exporter

- init-job/base/argo-workflows/initializer.yaml
Use SA init-job to read templates
> Use init-job SA to retrieve templates

- init-job/base/argo-workflows/solve-core-packages.yaml
- init-job/base/argo-workflows/solve-data-science-packages.yaml
Add variables missing to schedule Solver workflows from init-job
> Add missing variables for init-job tasks

- core/overlays/test/secrets.enc.yaml
> updated kafka certs

- adviser/base/openshift-templates/adviser.yaml
https://github.com/thoth-station/common/issues/882
common module looks for metadata label to schedule workflow.
copied from [adviser](https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/adviser-template.yaml)
> update adviser-template from adviser

- adviser/base/openshift-templates/adviser.yaml
The workflows which are not available would cause in using the following template.
As pointed out here:https://github.com/thoth-station/thoth-application/pull/46/files#r445189588
> use the workflow which are already present

- core/overlays/test/configmaps.yaml
Reduce parallelism due to PVC constraint
> Reduce parallelism

- core/overlays/test/configmaps.yaml
> Reduce parallelism more due to postgres PVC in test environment

- core/overlays/test/configmaps.yaml
I tried changing this value to 6 manually but it didn't seem to change the number being run so I'm trying here instead.
> reduce parallelism to 6

- package-extract/base/openshift-templates/packageExtract-template.yaml
I'll post workflow template shortly. Finishing tests with new thoth-common.
Related: https://github.com/thoth-station/package-extract/pull/406
> Introduce package-extract template

- package-extract/base/imagestream.yaml
- package-extract/base/kustomization.yaml
- package-extract/base/openshift-templates/package-extract.yaml
- package-extract/overlays/stage/imagestreamtag.yaml
- package-extract/overlays/stage/job-generate-name.yaml
- package-extract/overlays/stage/kustomization.yaml
- package-extract/overlays/stage/thoth-notification.yaml
- package-extract/overlays/test/imagestreamtag.yaml
- package-extract/overlays/test/job-generate-name.yaml
- package-extract/overlays/test/kustomization.yaml
- package-extract/overlays/test/thoth-notification.yaml
support package-extract project with argocd
https://github.com/thoth-station/package-extract/pull/406
includes package-extract application configuration to be deployed via argocd.
argocd project is to be created for package-extract once the pull request is merged.
> support package-extract project with argocd

- package-extract/base/kustomization.yaml
updated package-extract kustomize
All required template for package-extract to be deployed by argo-cd
> updated package-extract kustomize

- revsolver/base/imagestream.yaml
Related: https://github.com/thoth-station/revsolver/pull/3
> Add revsolver component

- graph-refresh/base/buildconfig.yaml
- graph-refresh/base/cronjob.yaml
- graph-refresh/base/imagestream.yaml
- graph-refresh/base/kustomization.yaml
- graph-refresh/overlays/stage/imagestreamtag.yaml
- graph-refresh/overlays/stage/job-generate-name.yaml
- graph-refresh/overlays/stage/kustomization.yaml
- graph-refresh/overlays/stage/thoth-notification.yaml
- graph-refresh/overlays/test/imagestreamtag.yaml
- graph-refresh/overlays/test/job-generate-name.yaml
- graph-refresh/overlays/test/kustomization.yaml
- graph-refresh/overlays/test/thoth-notification.yaml
setup basic for graph-refresh application in ocp
Related-to: #58 
Fixes: https://github.com/thoth-station/graph-refresh-job/issues/417
> setup basic for graph-refresh application in ocp

- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
> Amun argo wf does not use infra ns and registry parameters

- graph-backup-job/base/cronjob.yaml
- graph-backup-job/base/imagestream.yaml
- graph-backup-job/base/kustomization.yaml
Related: https://github.com/thoth-station/thoth-application/issues/58
> Add graph-backup-job component

- revsolver/base/argo-workflows/revsolver-template.yaml
> Add missing environment variables to revsolver

- revsolver/base/argo-workflows/revsolver-template.yaml
- revsolver/base/role.yaml
- revsolver/base/rolebinding.yaml
- revsolver/base/serviceaccount.yaml
> Add service account to let revsolver check registered solvers

- revsolver/base/argo-workflows/revsolver-template.yaml
Given the database size, the last value was too small. Let's try to increase and observe how much time we need to update entries.
> Increase deadline seconds for revsolver

- revsolver/base/argo-workflows/revsolver-template.yaml
> Increase CPU and decrease memory allocated for revsolver

- investigator/overlays/test/thoth-notification.yaml
use consistent naming convention
Related-to: https://argocd-server-aicoe-argocd.apps.ocp.prod.psi.redhat.com/applications/test-thoth-investigator
maintaining consistency
> use consistent naming convention

- advise-reporter/base/cronjob.yaml
- advise-reporter/base/deploymentconfig.yaml
- advise-reporter/base/kustomization.yaml
- package-update/base/cronjob.yaml
Related-to: https://github.com/thoth-station/advise-reporter/pull/40
Add missing template and adjust env variables
> Missing cronjob

- adviser/base/argo-workflows/investigate-unresolved-package.yaml
- adviser/base/openshift-templates/adviser.yaml
```
2020/07/11 08:40:00 Failed to submit workflow: templates.investigator-test.tasks.investigator-producer template reference exceeded max depth (10)
```
Adjust workflow template indentation
> adjust indentation and secret name

- adviser/base/argo-workflows/advise.yaml
- adviser/base/openshift-templates/adviser.yaml
Let's reduce beam width even more.
> Reduce adviser's beam width

- advise-reporter/base/cronjob.yaml
- advise-reporter/base/deploymentconfig.yaml
- adviser/base/argo-workflows/advise.yaml
- core/overlays/quicklab/configmaps.yaml
- core/overlays/stage/configmaps.yaml
- core/overlays/test/configmaps.yaml
- cve-update/base/cronjob.yaml
- graph-refresh/base/cronjob.yaml
- graph-sync/base/argo-workflows/sync-template.yaml
- graph-sync/base/openshift-templates/syncJob-template.yaml
- init-job/base/argo-workflows/solve-core-packages.yaml
- init-job/base/argo-workflows/solve-data-science-packages.yaml
- management-api/base/deploymentconfig.yaml
- metrics-exporter/base/deploymentconfig.yaml
- package-releases/base/cronjob.yaml
- package-update/base/cronjob.yaml
- package-update/base/deploymentconfig.yaml
- revsolver/base/argo-workflows/revsolver-template.yaml
- slo-reporter/base/cronjob.yaml
- solver/base/argo-workflows/solver-template.yaml
- user-api/base/deploymentconfig.yaml
> replaced deploymentName with deployment-name

- advise-reporter/base/cronjob.yaml
- graph-sync/base/argo-workflows/sync-template.yaml
- management-api/base/deploymentconfig.yaml
- package-update/base/cronjob.yaml
> Use CM for database host

- core/overlays/test/configmaps.yaml
- management-api/base/deploymentconfig.yaml
…
Add missing env to CM for Management-API
> Add amun-api-url env for management-API

- core/overlays/test/imagestreamtags.yaml
> update investigator image

- sefkhet-abwy/base/deploymentconfig.yaml
- sefkhet-abwy/base/imagestream.yaml
- sefkhet-abwy/base/kustomization.yaml
- sefkhet-abwy/base/route.yaml
- sefkhet-abwy/base/service.yaml
- sefkhet-abwy/overlays/ocp/kustomization.yaml
- sefkhet-abwy/overlays/ocp/secret-generator.yaml
- sefkhet-abwy/overlays/ocp/secrets.enc.yaml
- sefkhet-abwy/overlays/ocp/ultrahook.yaml
This migrated Sefkhet-Abwy from paas to cop cluster.
> added a sefkhet-abwy application with an ocp overlay

- security-indicators/base/security-indicators.yaml
Add syncing for security indicator results to si workflow
Fixes: https://github.com/thoth-station/graph-sync-job/issues/421
> add another step to workflow to sync results

- security-indicators/base/kustomization.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- security-indicators/overlays/test/buildconfig.yaml
- security-indicators/overlays/test/imagestreamtag.yaml
include additional manifest for security indicators
Related-to: 
https://github.com/thoth-station/thoth-application/issues/52
https://github.com/thoth-station/core/issues/236
including relevant images and build config for test environment.
> include additional manifest for security indicators

- mi-scheduler/base/cronjob.yaml
- mi-scheduler/base/kustomization.yaml
include additional manifest for mi indicators
include the workflow manifest for the mi application.
> include additional manifest for mi indicators

- investigator/base/deploymentconfig.yaml
- investigator/base/kustomization.yaml
- investigator/base/role.yaml
- investigator/base/role_binding.yaml
- investigator/base/serviceaccount.yaml
include the investigator manifest
> include the investigator manifest

- mi-scheduler/overlays/test/kustomization.yaml
- mi-scheduler/overlays/test/secret-generator.yaml
- mi-scheduler/overlays/test/secrets.enc.yaml
sesheta-srcops token for mi workflow
> sesheta-srcops token for mi workflow

- investigator/base/deploymentconfig.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/127
Fixes: https://github.com/thoth-station/investigator/issues/50
Add missing env variables to schedule solvers
> Add missing variables to schedule solvers

- advise-reporter/base/cronjob.yaml
Add missing env variables for adviser-reporter cronjob
> Missing env variables reporter

- adviser/base/argo-workflows/kebechet-run-results.yaml
- adviser/base/openshift-templates/adviser.yaml
Add kebechet run results task to adviser workflow (got lost after deleting templates from adviser)
> Add Kebechet-run results to adviser

- cve-update/overlays/stage/imagestreamtag.yaml
- cve-update/overlays/stage/thoth-notification.yaml
- cve-update/overlays/test/buildconfig.yaml
- cve-update/overlays/test/imagestreamtag.yaml
- cve-update/overlays/test/kustomization.yaml
NA
update image stream of test and stage.
cve-update-job minor configuration updates
> cve-update-job minor configuration updates

- solver/base/argo-workflows/parse_solver_inputs.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Related-To: https://github.com/thoth-station/solver/issues/579
Depends-On: https://github.com/thoth-station/thoth-application/pull/151
Depends-On: https://github.com/thoth-station/workflow-helpers/pull/25
Introduce workflow tasks to parse solver inputs and produce Kafka message for SolvedPackageMessage
> Add workflow tasks to send SolvedPackage message

- adviser/base/kustomization.yaml
Fixes: #158 
files stated in kustomize config are picked up by argocd.
include workflows and template with argocd
> include workflows and template with argocd

- package-extract/base/openshift-templates/package-extract.yaml
Fixes: #156 
update the package-extract template
> update the package-extract template

- core/overlays/quicklab/configmaps.yaml
- core/overlays/stage/configmaps.yaml
- core/overlays/test/configmaps.yaml
- management-api/base/deploymentconfig.yaml
- user-api/base/deploymentconfig.yaml
> Remove unused configuration options from cm

- adviser/overlays/stage/imagestreamtag.yaml
- adviser/overlays/stage/job-generate-name.yaml
- adviser/overlays/stage/kustomization.yaml
place adviser templates in infra namespace
> place adviser templates in infra namespace

- package-extract/overlays/stage/job-generate-name.yaml
run package-extract notification from infra
> run package-extract notification from infra

- core/overlays/graph-stage/pgbouncer.yaml
- core/overlays/graph-stage/postgresql.yaml
> Increase resources for pgbouncer and postgres

- mi-scheduler/base/kustomization.yaml
- mi-scheduler/base/role.yaml
Also remove unnecessary and unused resources in role
> Add missing yamls to kustomization

- mi-scheduler/base/kustomization.yaml
> fix the role_bindings

- graph-sync/base/kustomization.yaml
- graph-sync/base/openshift-templates/syncJob-template.yaml
- graph-sync/overlays/stage/imagestreamtag.yaml
- graph-sync/overlays/stage/job-generate-name.yaml
- graph-sync/overlays/stage/kustomization.yaml
- graph-sync/overlays/stage/put-into-infra-namespace.yaml
- graph-sync/overlays/stage/thoth-notification.yaml
manifest files required for graph-sync
> manifest files required for graph-sync

- core/overlays/stage/configmaps.yaml
Rectify ceph bucketname and prefix
Fixes: #180
> Rectify ceph bucketname and prefix

- amun/base/role.yaml
> Amun workflow SA can get pods and configmaps

- package-update/overlays/test/route.yaml
- package-update/overlays/test/service.yaml
route and service to expose metrics
> add route for viewing metrics

- mi-scheduler/base/cronjob.yaml
- mi-scheduler/base/openshift-templates/mi-run-template.yaml
- mi-scheduler/base/role_binding.yaml
MI scheduler required permissions
@xtuchyna this would fixes all the issues regarding mi scheduler, only the workflows would be left to test after this.
> MI scheduler required permissions

- adviser/base/argo-workflows/kebechet-run-results.yaml
- adviser/base/argo-workflows/trigger-integration.yaml
- adviser/base/openshift-templates/adviser.yaml
Depends on: https://github.com/thoth-station/workflow-helpers/pull/31
> pass parsed git service string to kebechet

- solver/overlays/stage/imagestreamtag.yaml
- solver/overlays/test/imagestreamtag.yaml
Updated solver with new release
updated image tag with new images
> Updated solver with new release

- core/overlays/middletier-stage/configmaps.yaml
- core/overlays/quicklab/configmaps.yaml
- core/overlays/test/configmaps.yaml
> Provide workflow parallelism in workflow defaults section

- graph-sync/base/argo-workflows/sync-template.yaml
- metrics-exporter/base/deploymentconfig.yaml
- solver/base/argo-workflows/parse-solver-inputs.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Related-to: #187 
- component of thoth shouldn't directly use amun configmap
- indentation fix of output in parse-solver workflow
fixes required for smooth solver execution
> fixes required for smooth solver execution

- user-api/base/deploymentconfig.yaml
> Remove not found exception from Sentry reports

- core/overlays/middletier-stage/argo-namespace-install.yaml
:arrow_up: increase workflow controller memory
OOM
> :arrow_up: increase workflow controller memory

- solver/base/openshift-templates/solve_and_sync-template.yaml
We should use the existing topic name here
> topic exists in thoth.messaging so use existing topic name

- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
> Resubmit pending pods in Amun inspections

- nepthys/base/cronjob.yaml
- nepthys/base/imagestreamtag.yaml
- nepthys/base/kustomization.yaml
- nepthys/overlays/ocp/buildConfig.yaml
- nepthys/overlays/ocp/imagestreamtag.yaml
- nepthys/overlays/ocp/job-generate-name.yaml
- nepthys/overlays/ocp/kustomization.yaml
- nepthys/overlays/ocp/secret-generator.yaml
- nepthys/overlays/ocp/secrets.enc.yaml
- nepthys/overlays/ocp/thoth-notification.yaml
Related-To: https://github.com/thoth-station/thoth-application/issues/58
include manifest files for nepthys to be deployed by argocd.
handle nepthy deployment with argocd
> handle nepthy deployment with argocd

- sefkhet-abwy/base/deploymentconfig.yaml
- sefkhet-abwy/base/route.yaml
- sefkhet-abwy/overlays/ocp/secrets.enc.yaml
- sefkhet-abwy/overlays/ocp/ultrahook.yaml
updated sefkhet-abwy manifest files
> updated sefkhet-abwy manifest files

- solver/base/openshift-templates/solve_and_sync-template.yaml
`Send Kafka messages task` after `parse solver inputs` task is finished.
> Adjust workflow logic

- core/overlays/stage/configmaps.yaml
- core/overlays/test/configmaps.yaml
maintianing consistency in the configmaps
Related-to: #187 
> maintianing consistency in the configmaps

- advise-reporter/overlays/stage/imagestreamtag.yaml
- advise-reporter/overlays/stage/job-generate-name.yaml
- advise-reporter/overlays/stage/kustomization.yaml
- advise-reporter/overlays/stage/thoth-notification.yaml
manifest files for advise-reporter stage deployment
> manifest files for advise-reporter stage deployment

- amun/overlays/stage/configmaps.yaml
- amun/overlays/test/configmaps.yaml
maintain consistency in ceph bucket storage
> maintain consistency in ceph bucket storage

- sefkhet-abwy/base/kustomization.yaml
- sefkhet-abwy/overlays/ocp/kustomization.yaml
- sefkhet-abwy/overlays/ocp/thoth-friday-scrum-cronjob.yaml
- sefkhet-abwy/overlays/ocp/thoth-scrum-cronjob.yaml
include cronjob manifest from sefkhet-abwy
> include cronjob manifest from sefkhet-abwy

- adviser/base/argo-workflows/kebechet-run-results.yaml
- adviser/overlays/stage/kustomization.yaml
- adviser/overlays/stage/put-into-middletier-namespace.yaml
- adviser/overlays/stage/secrets.enc.yaml
- user-api/overlays/stage/kustomization.yaml
include adviser template in stage development
Fixes: #223 
- include templates in the infra-stage namespace.
-  all the templates would be placed in infra-stage namespace.
> include adviser template in stage development

- amun/overlays/stage/imagestreamtag.yaml
update amun stage imagestreamtag
> update amun stage imagestreamtag

- core/overlays/test/configmaps.yaml
- slo-reporter/base/cronjob.yaml
Add missing env variables to run slo-reporter
> Missing env variables for SLO-reporter

- adviser/base/argo-workflows/trigger-integration.yaml
fix workflow output resolve
Fixes: #228 
output should be indented in the level of container. 
https://argoproj.github.io/argo/examples/#output-parameters
Fixed indentation.
> fix workflow output resolve

- solver/base/argo-workflows/parse-solver-inputs.yaml
> Adjust variable name for solver parsing

- amun/overlays/stage/imagestreamtag.yaml
Depends-On: https://github.com/thoth-station/amun-api/issues/499
> Update Amun API in stage environment

- qeb-hwt-github-app/base/configmap.yaml
- qeb-hwt-github-app/base/deploymentconfig.yaml
updated qebhwt app with new url and minor fix
Fixes: #33 
- updated a new URL based on the OCP cluster
- update replica is autogenerated, not a key recognized while deployment 
Fix component for qebhwt webhook app to function in the new cluster.
> updated qebhwt app with new url and minor fix

- amun/overlays/amun-inspection/argo-namespace-install.yaml
It might be easier to operate Amun inspections this way.
> Run just one workflow at the time

- amun/base/deploymentconfig.yaml
Fixes: https://github.com/thoth-station/amun-api/issues/516
> Ignore validation errors on Amun API in Sentry

- amun/overlays/stage/imagestreamtag.yaml
https://github.com/thoth-station/amun-api/issues/520
> Bump Amun version to 0.7.7

- security-indicators/overlays/stage/imagestreamtag.yaml
- security-indicators/overlays/stage/job-generate-name.yaml
- security-indicators/overlays/stage/kustomization.yaml
- security-indicators/overlays/stage/put-into-infra-namespace.yaml
- security-indicators/overlays/stage/thoth-notification.yaml
manifest file for stage deployementof si indicator
Fixes: https://github.com/thoth-station/thoth-application/issues/52
- included manifest files for stage deployment
- template are patched to be deployed to infra
All the required manifest files are added for stage deployment of si indicator.
> manifest file for stage deployementof si indicator

- core/overlays/test/argo-namespace-install.yaml
... also pull images from quay.io not to hit dockerhub limits.
> Use Argo Workflows 2.9.5 in test environment

- qeb-hwt-github-app/base/route.yaml
> Make pre-commit happy again

- amun/overlays/stage/imagestreamtag.yaml
> Use Amun v0.8.0 in stage environment

- metrics-exporter/base/deploymentconfig.yaml
- metrics-exporter/overlays/test/buildConfig.yaml
None
-fixed namespace variable in deployment config.
correction in deploymentconfig environment vars
> correction in deploymentconfig environment vars

- core/overlays/stage/imagestreamtags.yaml
- core/overlays/test/imagestreamtags.yaml
Missing messaging images in git details
included latest messaging image
Included messaging image for test and stage deployment
> Included messaging image for test and stage deployment

- amun/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/amun-api/issues/535
> Bump Amun API in stage to 0.9.0

- core/overlays/backend-stage/argo-namespace-install.yaml
- core/overlays/middletier-stage/argo-namespace-install.yaml
> Use Argo 2.9.5 in middletier and backend namespace

- slo-reporter/base/cronjob.yaml
> Modify time schedule for SLO reporter

- core/overlays/test/argo-namespace-install.yaml
fix up version of workflow-controller
fix version v in test workflow-controller
> fix version v in test workflow-controller

- amun/overlays/stage/imagestreamtag.yaml
> Bump Amun API in stage version to 0.9.2

- graph-sync/overlays/stage/imagestreamtag.yaml
stage deployment needed storage module update.
Bump graph-sync stage to v0.7.2-dev
> Bump graph-sync stage to v0.7.2-dev

- revsolver/overlays/stage/imagestreamtag.yaml
> Bump revsolver to v0.2.3 in stage environment

- slo-reporter/base/cronjob.yaml
Related-To: https://github.com/thoth-station/slo-reporter/pull/70/files
Remove unused env variable
> Remove env variable

- core/base/argo-workflows/send-message.yaml
https://github.com/thoth-station/messaging/issues/215
> make many optional and add ability to pass dep. name

- solver/base/openshift-templates/solve_and_sync-template.yaml
> pass thoth_deployment name to send_message

- amun/base/argo-workflows/inspection-build-with-cpu.yaml
- amun/base/argo-workflows/inspection-build.yaml
Fixes: https://github.com/thoth-station/amun-api/issues/547
> Prepare environment before running resubmitted Amun inspections

- security-indicators/overlays/test/buildConfig.yaml
Remove duplicate env variables
> remove duplicate env variables

- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
https://github.com/thoth-station/amun-api/issues/552
> on exit send message

- core/overlays/stage/configmaps.yaml
Assign correct endpoint for metrics-exporter stage
> Adjust endpoint for metrics-exporter deployment

- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
> add more descriptive topic name

- amun/overlays/amun-inspection/argo-namespace-install.yaml
Let's give it a try and see if resource handling will be better.
Related: https://github.com/argoproj/argo/issues/1913
> Install Argo's workflow-controller with fix-3791

- amun/overlays/amun-inspection/configmaps.yaml
Related: https://github.com/thoth-station/thoth-application/pull/316
As self-healing is turned on, let's make this change here to see how argo behaves.
> Increase parallelism to see how resources are handled

- amun/overlays/amun-inspection/configmaps.yaml
Related: https://github.com/thoth-station/thoth-application/pull/318
> Increase parallelism in Argo workflows even more

- core/overlays/backend-stage/argo-namespace-install.yaml
- core/overlays/middletier-stage/argo-namespace-install.yaml
Related: https://github.com/argoproj/argo/issues/1913#issuecomment-678675590
Let's see if resource handling will be better.
> Install Argo with fix-3791

- user-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/issues/1011
> Bump user-api in stage to v0.6.11

- amun/base/argo-workflows/inspection-build-with-cpu.yaml
- amun/base/argo-workflows/inspection-build.yaml
- amun/base/role.yaml
- amun/base/serviceaccount.yaml
- amun/overlays/stage/role_binding.yaml
- amun/overlays/test/role_binding.yaml
> Prepare service account for preparing environment

- slo-reporter/base/cronjob.yaml
Add missing env variables to SLO-reporter
> Add missing variable for SLO-reporter

- kebechet/overlays/stage/imagestreamtag.yaml
> Bump Kebechet to v1.0.2 in stage

- package-update/overlays/test/imagestreamtag.yaml
One pipeline run lost
Update package update with new version on quay
> Bump package-update version to 0.8.0

- OWNERS
> Add pacospace and fridex to OWNERS file

- kebechet/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/kebechet/issues/511
> Bump kebechet to v1.0.3 in stage

- slo-reporter/base/cronjob.yaml
> Fix pre-commit issues reported

- kebechet/overlays/stage/imagestreamtag.yaml
Reverts thoth-station/thoth-application#331
> Revert "Bump kebechet to v1.0.3 in stage"

- core/overlays/backend-stage/configmaps.yaml
- core/overlays/middletier-stage/configmaps.yaml
- core/overlays/test/configmaps.yaml
I tried to debug why workflows do not get deleted. It looks like service account has correct perms and all the rest looks configured correctly. Let's try to experiment with `secondsAfterCompletion` and see if it helps.
> Try to setup secondsAfterCompletion to clean up workflows

- kebechet/overlays/stage/imagestreamtag.yaml
> Bump Kebechet to version 1.0.4 in stage

- adviser/base/argo-workflows/dependency-monkey.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
Related: https://github.com/thoth-station/common/pull/955
> Introduce a way to parametrize predictor configuration in DM

- adviser/base/argo-workflows/advise.yaml
- adviser/base/openshift-templates/adviser.yaml
Related: thoth-station/common#955
> Introduce a way to parametrize adviser's predictor

- adviser/base/argo-workflows/dependency-monkey.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
> Allow users to pick predictor to be used

- adviser/base/openshift-templates/adviser.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
- adviser/base/openshift-templates/provenance-checker.yaml
- buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
- kebechet/base/openshift-templates/kebechet.yaml
- package-extract/base/openshift-templates/package-extract.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
> Provide secondsAfterCompletion in all workflows

- adviser/base/openshift-templates/adviser.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
- adviser/base/openshift-templates/provenance-checker.yaml
- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
- buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
- init-job/base/argo-workflows/initializer.yaml
- kebechet/base/openshift-templates/kebechet.yaml
- mi-scheduler/base/openshift-templates/mi-run-template.yaml
- package-extract/base/openshift-templates/package-extract.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Fix `pod deleted` issues in workflows.
Related: https://github.com/argoproj/argo/issues/3918 https://github.com/argoproj/argo/issues/1913#issuecomment-685795749
> Set rebumitPendingPods to all the workflows

- adviser/base/openshift-templates/adviser.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
- adviser/base/openshift-templates/provenance-checker.yaml
- buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
- init-job/base/argo-workflows/initializer.yaml
- kebechet/base/openshift-templates/kebechet.yaml
- mi-scheduler/base/openshift-templates/mi-run-template.yaml
- package-extract/base/openshift-templates/package-extract.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Related: https://github.com/thoth-station/thoth-application/pull/358
> Move resubmit pending pods to task definitions

- adviser/base/argo-workflows/advise.yaml
- adviser/base/argo-workflows/dependency-monkey.yaml
- adviser/base/argo-workflows/investigate-unresolved-package.yaml
- adviser/base/argo-workflows/kebechet-run-results.yaml
- adviser/base/argo-workflows/provenance-check.yaml
- adviser/base/argo-workflows/trigger-integration.yaml
- amun/base/argo-workflows/inspection-build-with-cpu.yaml
- amun/base/argo-workflows/inspection-build.yaml
- amun/base/argo-workflows/inspection-run-with-cpu.yaml
- amun/base/argo-workflows/inspection-run.yaml
- core/base/argo-workflows/send-message.yaml
- graph-sync/base/argo-workflows/sync-template.yaml
- init-job/base/argo-workflows/initialize-schema.yaml
- init-job/base/argo-workflows/register-indexes.yaml
- init-job/base/argo-workflows/solve-core-packages.yaml
- init-job/base/argo-workflows/solve-data-science-packages.yaml
- kebechet/base/argo-workflows/kebechet.yaml
- mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
- package-extract/base/argo-workflows/package-extract.yaml
- qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
- revsolver/base/argo-workflows/revsolver-template.yaml
- security-indicators/base/argo-workflows/aggregator-template.yaml
- security-indicators/base/argo-workflows/bandit-template.yaml
- security-indicators/base/argo-workflows/cloc-template.yaml
- security-indicators/base/argo-workflows/download-package-template.yaml
- solver/base/argo-workflows/parse-solver-inputs.yaml
- solver/base/argo-workflows/solver-template.yaml
Related: https://github.com/thoth-station/thoth-application/pull/358 https://github.com/thoth-station/thoth-application/pull/361
> Add resubmitPendingPods to all templates in workflow

- adviser/base/openshift-templates/adviser.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
- adviser/base/openshift-templates/provenance-checker.yaml
- buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
- init-job/base/argo-workflows/initializer.yaml
- kebechet/base/openshift-templates/kebechet.yaml
- mi-scheduler/base/openshift-templates/mi-run-template.yaml
- package-extract/base/openshift-templates/package-extract.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Reverts thoth-station/thoth-application#361
See https://github.com/thoth-station/thoth-application/pull/362#issuecomment-686335601
> Revert "Move resubmit pending pods to task definitions"

- adviser/base/openshift-templates/provenance-checker.yaml
- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
Reverts thoth-station/thoth-application#358
See https://github.com/thoth-station/thoth-application/pull/362#issuecomment-686335601
> Revert "Set rebumitPendingPods to all the workflows"

- adviser/base/openshift-templates/adviser.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
- buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
- kebechet/base/openshift-templates/kebechet.yaml
- mi-scheduler/base/openshift-templates/mi-run-template.yaml
- package-extract/base/openshift-templates/package-extract.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
... they should be present in WorkflowTemplates
Related: https://github.com/thoth-station/thoth-application/pull/362
> Remove resubmitPendingPods from openshift templates

- amun/base/argo-workflows/inspection-build-with-cpu.yaml
- amun/base/argo-workflows/inspection-run-with-cpu.yaml
- graph-sync/base/argo-workflows/sync-template.yaml
- init-job/base/argo-workflows/initialize-schema.yaml
- init-job/base/argo-workflows/register-indexes.yaml
- init-job/base/argo-workflows/solve-core-packages.yaml
- init-job/base/argo-workflows/solve-data-science-packages.yaml
- mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
- package-extract/base/argo-workflows/package-extract.yaml
- revsolver/base/argo-workflows/revsolver-template.yaml
Related-To: https://github.com/thoth-station/thoth-application/pull/362/
> fix spelling

- solver/base/argo-workflows/solver-template.yaml
Related-To: https://github.com/thoth-station/slo-reporter/issues/79
Add solver workflow metrics
> Add workflow metrics for solver

- slo-reporter/overlays/test/configmap.yaml
Test environment email should arrive only to Thoth Team.
> Send test environment SLO report to Thoth Team only

- solver/base/argo-workflows/solver-template.yaml
> Increase solver CPU resources and time allocated

- adviser/overlays/stage/imagestreamtag.yaml
Reverts thoth-station/thoth-application#370
> Revert "Bump adviser to v0.16.0 in stage"

- adviser/base/openshift-templates/adviser.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
- adviser/base/openshift-templates/provenance-checker.yaml
- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
- buildlog-parser/base/openshift-templates/buildlogParser-template.yaml
- init-job/base/argo-workflows/initializer.yaml
- kebechet/base/openshift-templates/kebechet.yaml
- mi-scheduler/base/openshift-templates/mi-run-template.yaml
- package-extract/base/openshift-templates/package-extract.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- revsolver/base/argo-workflows/revsolver-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- solver/base/argo-workflows/solver-template.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
> Give 50 minutes to all workflows to finish

- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
> Clean up inspections after 3 days and increase active seconds

- amun/overlays/amun-inspection/configmaps.yaml
... to utilize cluster resources better and speed up the batch
> Increase parallelism for the current inspection batch

- amun/overlays/amun-inspection/configmaps.yaml
See https://github.com/thoth-station/thoth-application/pull/378
> Increase parallelism even more

- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
> Try to clean up workflows as soon as possible

- core/overlays/middletier-stage/configmaps.yaml
> Set default TTL in middletier to 10 seconds

- core/overlays/stage/secrets.enc.yaml
- core/overlays/test/secrets.enc.yaml
Kafka broken errors
- kafka deployment is updated in thoth12 cluster, new certs are updated in secrets. 
updated kafka certs for stage and test
> updated kafka certs for stage and test

- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
- amun/base/openshift-templates/inspection-workflow.yaml
I saw some inspection got stuck overnight. We might eventually have this parametrized.
> Decrease inspection deadline

- graph-refresh/base/cronjob.yaml
> Schedule graph-refresh each hour

- user-api/base/role.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/389
> Allow user-api to retrieve pod logs

- core/overlays/stage/secrets.enc.yaml
- core/overlays/test/secrets.enc.yaml
Related-to: #386 
fixed the wrong kafka certs for stage and test
patch the certs for kafka deployment
> patch the certs for kafka deployment

- solver/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/solver/pull/608 https://github.com/thoth-station/solver/issues/611
> Use solver in version 1.6.1 in stage environment

- solver/overlays/stage/imagestreamtag.yaml
- solver/overlays/test/imagestreamtag.yaml
> Bump solver version to 1.6.2

- amun/overlays/amun-inspection/configmaps.yaml
> Decrease parallelism to 1 for the current batch

- core/overlays/backend-stage/configmaps.yaml
increase parallelism to 6 for backend.
bump parallelism for backend namespace
> bump parallelism for backend namespace

- adviser/base/argo-workflows/kebechet-run-results.yaml
- adviser/base/argo-workflows/trigger-integration.yaml
- adviser/base/openshift-templates/adviser.yaml
Related-To: https://github.com/thoth-station/workflow-helpers/pull/67
Modify variable name
> Change variable name

- core/base/argo-workflows/send-messages.yaml
- solver/base/argo-workflows/parse-solved-package.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Correct missing env variables and indentation
> Correct env variables and indentation

- solver/base/kustomization.yaml
include all argo workflows for solver in kustomize
> include all argo workflows for solver in kustomize

- core/base/kustomization.yaml
include all argo workflows for core to kustomize
> include all argo workflows for core to kustomize

- kebechet/overlays/stage/imagestreamtag.yaml
Bump kebechet 
Depends on https://github.com/thoth-station/kebechet/pull/538
> Bumped kebechet to 1.05

- solver/base/argo-workflows/parse-solved-package.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/408
Remove variable not required
> Remove variable not required

- core/overlays/backend-stage/configmaps.yaml
> Increase parallelism in backend namespace

- revsolver/base/argo-workflows/revsolver-template.yaml
- solver/base/argo-workflows/solver-template.yaml
> Retry solver and revsolver to bypass possible networking issues

- prow/overlays/thoth-station/config.yaml
> Add thoth repos to be checked

- nepthys/overlays/ocp/imagestreamtag.yaml
> Bump nepthys version in ocp to 0.2.0

- amun/base/openshift-templates/inspection-with-cpu-workflow.yaml
Fixes: #428 #352 
- Removed bits of #311
wait for the kafka configuration option for amun
> wait for the kafka configuration option for amun

- amun/overlays/amun-inspection/argo-namespace-install.yaml
wc in amun-inspection crashlooping due to oom
patch resource for the wc
> patch resource for the wc

- security-indicators/base/openshift-templates/security-indicators.yaml
> Improve readability

- security-indicators/base/argo-workflows/aggregator-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
> Rename output and more readability

- metrics-exporter/overlays/stage/imagestreamtag.yaml
> Bump version of metrics-exporter to v0.8.10

- core/overlays/middletier-stage/configmaps.yaml
Based on the quota increase to utilize resources in a more efficient manner.
> Increase parallelism in middletier-stage

- core/overlays/backend-stage/configmaps.yaml
Based on the quota increase to utilize resources in a more efficient manner.
> Increase parallelism in backend-stage

- package-releases/base/cronjob.yaml
- package-releases/base/kustomization.yaml
- package-releases/overlays/test/cronjob.yaml
- package-releases/overlays/test/kustomization.yaml
Depends-On: https://github.com/thoth-station/package-releases-job/issues/450
Fixes: https://github.com/thoth-station/thoth-application/issues/422
> initial modifications for turning to producer

- graph-refresh/overlays/test/cronjob.yaml
- graph-refresh/overlays/test/imagestreamtag.yaml
To deploy new graph-refresh-job to thoth-test-core
> Updated cronjob to use producer

- security-indicators/base/argo-workflows/aggregator-template.yaml
- security-indicators/base/argo-workflows/bandit-template.yaml
- security-indicators/base/argo-workflows/cloc-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- Add metrics
- Improve readability
> Add metrics and improve readability

- adviser/base/openshift-templates/adviser.yaml
Related: https://github.com/thoth-station/adviser/issues/1230
> Hardcode predictor config to workaround parsing issue

- core/overlays/middletier-stage/configmaps.yaml
Feels like we are utilizing 60 - 75% now.
> Increase parallelism in middletier even more

- adviser/base/openshift-templates/adviser.yaml
Reverts thoth-station/thoth-application#448
> Revert "Hardcode predictor config to workaround parsing issue"

- .thoth.yaml
- version.py
Add thoth config to support version releases
> Add thoth config

- nepthys/overlays/ocp/imagestreamtag.yaml
Bump version v0.2.1 for nepthys
> Bump version v0.2.1 for nepthys

- kebechet/overlays/prod/imagestreamtag.yaml
- kebechet/overlays/stage/imagestreamtag.yaml
- kebechet/overlays/test/imagestreamtag.yaml
Bump version v1.0.6 for kebechet
> Bump version v1.0.6 for kebechet

- kebechet/overlays/prod/imagestreamtag.yaml
- kebechet/overlays/stage/imagestreamtag.yaml
- kebechet/overlays/test/imagestreamtag.yaml
Revert kebechet to release fixes
> Revert ":ship: Bump version v1.0.6 for kebechet (#460)"

- core/overlays/stage/configmaps.yaml
- core/overlays/test/configmaps.yaml
- slo-reporter/base/cronjob.yaml
> Adjust env variable

- kebechet/overlays/stage/imagestreamtag.yaml
Depends on - https://github.com/thoth-station/kebechet/pull/557
> Bumped kebechet to 1.0.7

- kebechet/overlays/stage/imagestreamtag.yaml
Reverts thoth-station/thoth-application#463
> Revert "Bumped kebechet to 1.0.7"

- core/overlays/test/argo-namespace-install.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/372
> Update argo to v.2.11.0

- kebechet/overlays/stage/imagestreamtag.yaml
> Update kebechet to 1.0.8

- nepthys/base/cronjob.yaml
nepthys running into oom issues
updated the resource requirement for nepthys.
bump up resource for nepthys.
It would work with 1.5 gi memory as well, but uses most of it. 
> bump up resource for nepthys

- amun/base/deploymentconfig.yaml
> Propagate deployment-name and Amun API url to Amun deploymentconfig

- metrics-exporter/overlays/stage/imagestreamtag.yaml
> bump metrics-exporter stage to v0.8.12

- adviser/base/argo-workflows/advise.yaml
- adviser/base/openshift-templates/adviser.yaml
- adviser/base/openshift-templates/dependency-monkey.yaml
- adviser/base/openshift-templates/provenance-checker.yaml
- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- solver/base/argo-workflows/solver-template.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Fixes: https://github.com/thoth-station/slo-reporter/issues/79
> Introduce workflow metrics for quality and latency

- core/overlays/test/argo-namespace-install.yaml
fix the argo image stream lookup policy
> fix the argo imagestream lookup policy

- kebechet/base/openshift-templates/kebechet.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
- security-indicators/base/openshift-templates/security-indicators.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Requirements for metrics > 20 to be scrapred by Prometheus ( that scrapes every 20 seconds ), with 25 seconds we should be fine.
> Minor adjustments and add metrics for qeb-hwt and kebechet

- nepthys/overlays/ocp/imagestreamtag.yaml
Bump version v0.2.2 for nepthys
> Bump version v0.2.2 for nepthys

- adviser/base/argo-workflows/provenance-check.yaml
removed isis-url requirement.
provenance clear non required configmap requirements
> provenance clear non required configmap requirements

- adviser/base/argo-workflows/trigger-integration.yaml
- adviser/base/configmap.yaml
- adviser/base/kustomization.yaml
fix configmap qeb-hwt-workflow usage
Related-to: #487
> fix configmap qeb-hwt-workflow usage

- package-update/base/cronjob.yaml
- package-update/overlays/test/cronjob.yaml
schedule package-update to run in stage
> schedule package-update to run in stage

- revsolver/base/openshift-templates/revsolve_and_sync-template.yaml
include labels for revsolver workflow
> include labels for revsolver workflow

- package-update/overlays/stage/kustomization.yaml
- package-update/overlays/stage/thoth-notification.yaml
- package-update/overlays/test/kustomization.yaml
- package-update/overlays/test/thoth-notification.yaml
- package-update/overlays/test/unsuspend-cronjob.yaml
maintain consistency in package update manifest files
> maintain consistency in package update manifest files

- investigator/overlays/stage/role_binding.yaml
Argo cd application is falling for stage
fix misspelled namespace name
> fix misspelled namespace name

- investigator/overlays/stage/role.yaml
updated role for investigator to view configmaps
> updated role for investigator to view configmaps

- core/overlays/stage/imagestreamtags.yaml
> Bump investigator to v0.4.12

- graph-refresh/base/cronjob.yaml
> Increase learning rate for Thoth (more messages)

- kebechet/base/openshift-templates/kebechet.yaml
> Correct name of metrics

- user-api/overlays/test/deploymentconfig.yaml
- user-api/overlays/test/kustomization.yaml
> Add parameters to test Kafka user-api producer

- investigator/base/deploymentconfig.yaml
> Add backend namespace env to investigator to schedule workflows

- user-api/base/role.yaml
- user-api/overlays/stage/kustomization.yaml
- user-api/overlays/stage/put-into-backend-namespace.yaml
- user-api/overlays/stage/role-binding.yaml
Fixes: #459 
allow user-api to reach pod logs in backend.
patch roles for user-api to pull logs
> patch roles for user-api to pull logs

- solver/overlays/test/kustomization.yaml
patch up kustomize config for solver
> patch up kustomize config for solver

- core/overlays/stage/configmaps.yaml
- core/overlays/stage/imagestreamtags.yaml
- core/overlays/test/configmaps.yaml
- graph-refresh/overlays/stage/imagestreamtag.yaml
- management-api/overlays/stage/imagestreamtag.yaml
- metrics-exporter/base/deploymentconfig.yaml
- metrics-exporter/overlays/stage/imagestreamtag.yaml
- slo-reporter/base/cronjob.yaml
- slo-reporter/overlays/stage/imagestreamtag.yaml
Bump slo-reporter investigator, messaging and metrics-exporter to newer version for alarms and messaging versions.
> Move to stage newer versions

- core/overlays/stage/configmaps.yaml
- core/overlays/test/configmaps.yaml
- metrics-exporter/base/deploymentconfig.yaml
> Adjust env name

- slo-reporter/overlays/stage/kustomization.yaml
remove the pre-fixed namespace
> remove the pre-fixed namespace

- prow/overlays/thoth-station/config.yaml
Fixes: #524 
include idh repo into prow config
> include idh repo into prow config

- investigator/base/deploymentconfig.yaml
> Do not schedule revsolver

- security-indicators/base/argo-workflows/download-package-template.yaml
> Remove test from image

- core/overlays/stage/imagestreamtags.yaml
> Bump investigator to v0.5.3

- core/overlays/stage/configmaps.yaml
- slo-reporter/base/cronjob.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/536
> Add parameter to CM in stage

- graph-refresh/base/cronjob.yaml
> Reduce scheduling from graph-refresh

- advise-reporter/base/cronjob.yaml
- core/overlays/backend-stage/configmaps.yaml
- core/overlays/middletier-stage/configmaps.yaml
- core/overlays/prod/backend-prod/configmaps.yaml
- core/overlays/prod/middletier-prod/configmaps.yaml
- core/overlays/quicklab/configmaps.yaml
- core/overlays/test/configmaps.yaml
- package-update/base/cronjob.yaml
- package-update/overlays/prod/cronjob.yaml
- package-update/overlays/prod/imagestreamtag.yaml
- package-update/overlays/stage/cronjob.yaml
- package-update/overlays/stage/imagestreamtag.yaml
- package-update/overlays/test/cronjob.yaml
bump package-update resources and image tag
> bump package-update resources and image tag

- investigator/base/deploymentconfig.yaml
set initial delay for readiness probe for investigator consumer
> set initial delay for readiness probe for investigator consumer

- qeb-hwt-github-app/overlays/stage/configmap.yaml
- qeb-hwt-github-app/overlays/stage/imagestreamtag.yaml
- qeb-hwt-github-app/overlays/stage/job-generate-name.yaml
- qeb-hwt-github-app/overlays/stage/kustomization.yaml
- qeb-hwt-github-app/overlays/stage/put-into-backend-namespace.yaml
- qeb-hwt-github-app/overlays/stage/put-into-infra-namespace.yaml
- qeb-hwt-github-app/overlays/stage/secret-generator.yaml
- qeb-hwt-github-app/overlays/stage/secrets.enc.yaml
- qeb-hwt-github-app/overlays/stage/thoth-notification.yaml
- qeb-hwt-github-app/overlays/stage/ultrahook-deployment.yaml
- qeb-hwt-github-app/overlays/test/configmap.yaml
- qeb-hwt-github-app/overlays/test/imagestreamtag.yaml
- qeb-hwt-github-app/overlays/test/job-generate-name.yaml
- qeb-hwt-github-app/overlays/test/kustomization.yaml
- qeb-hwt-github-app/overlays/test/secret-generator.yaml
- qeb-hwt-github-app/overlays/test/secrets.enc.yaml
- qeb-hwt-github-app/overlays/test/thoth-notification.yaml
- qeb-hwt-github-app/overlays/test/ultrahook-deployment.yaml
Related-to: #549 
separate overlays based on the environment
https://github.com/thoth-station/thoth-application/pull/549#issuecomment-705383335
> separate overlays based on environment

- core/overlays/stage/configmaps.yaml
- core/overlays/stage/secrets.enc.yaml
update stage with kafka in thoth02 cluster
> update stage with kafka in thoth02 cluster

- qeb-hwt-github-app/overlays/test/kustomization.yaml
Added kustomize changes to utilize test templates
> Added customize change

- graph-refresh/overlays/stage/imagestreamtag.yaml
- package-releases/base/cronjob.yaml
- package-releases/overlays/stage/imagestreamtag.yaml
Add metrics for producers of messages
> More metrics

- advise-reporter/overlays/stage/kustomization.yaml
- advise-reporter/overlays/test/kustomization.yaml
Add files to kustomize to apply patches respect to base
> Add files to kustomize

- core/overlays/stage/imagestreamtags.yaml
- qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
- qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml
- user-api/overlays/stage/imagestreamtag.yaml
Needs - 
https://github.com/thoth-station/workflow-helpers/releases/tag/v0.1.17
and 
https://github.com/thoth-station/investigator/releases/tag/v0.5.5
> Moved new templates to base

- kebechet/base/argo-workflows/kebechet-run-url.yaml
- kebechet/base/openshift-templates/kebechet-run-url.yaml
- kebechet/overlays/prod/kustomization.yaml
- kebechet/overlays/stage/kustomization.yaml
Added kebechet run-url templates. 
Related - https://github.com/thoth-station/common/issues/1009
> Added Kebechet run url templates

- nepthys/overlays/ocp/imagestreamtag.yaml
> Bump nepthys to 0.2.3

- core/overlays/test/configmaps.yaml
- core/overlays/test/secrets.enc.yaml
switch to kafka backed with amq streams for test instance
> switch to kafka backed with amq streams for test instance

- nepthys/overlays/ocp/imagestreamtag.yaml
bump up nepthys version to v0.2.4
> bump up nepthys version to v0.2.4

- core/overlays/test/configmaps.yaml
- core/overlays/test/secrets.enc.yaml
- deployed the kafka deployment on to ocp cluster.
http://kafdrop-route-aicoe.apps.ocp.prod.psi.redhat.com/
switch to ocp kafka backed by amq streams in test
> switch to ocp kafka backed by amq streams in test

- slo-reporter/overlays/stage/imagestreamtag.yaml
> Dump slo-reporter to v0.5.9 in stage

- graph-refresh/base/cronjob.yaml
Increase ingestion so that Thoth can continuously learn.
> Increase ingestion

- advise-reporter/base/cronjob.yaml
- adviser/base/argo-workflows/parse_adviser_output.yaml
- adviser/base/openshift-templates/adviser.yaml
- core/overlays/stage/common/imagestreamtags.yaml
- solver/base/openshift-templates/solve_and_sync-template.yaml
Fixes: https://github.com/thoth-station/investigator/issues/113
Depends-On: https://github.com/thoth-station/workflow-helpers/pull/155
Adjust adviser workflow tasks
> Adjust adviser workflow tasks

- kebechet/base/kustomization.yaml
include kebechet templates to the kustomize manifest
> include kebechet templates to the kustomize manifest

- core/overlays/prod/graph-prod/postgresql-metrics-exporter.yaml
- core/overlays/test/postgresql-metrics-exporter.yaml
patch up the apiversion for postgresql metrics deployment
> patch up the apiversion for postgresql metrics deployment

- kebechet/base/argo-workflows/kebechet-administrator.yaml
- kebechet/base/kustomization.yaml
- kebechet/base/openshift-templates/kebechet-administrator.yaml
- kebechet/overlays/stage/kustomization.yaml
Related - https://github.com/thoth-station/workflow-helpers/issues/148
Added Kebechet administrator workflow templates
Would need access to database, which I have added in the argo workflow.
> Add Kebechet administrator

- slo-reporter/overlays/stage/imagestreamtag.yaml
> bump slo-reporter to v0.6.0

- core/base/configmaps.yaml
- core/overlays/ocp4-stage/common/configmaps.yaml
- core/overlays/prod/common/configmaps.yaml
- core/overlays/stage/common/configmaps.yaml
- core/overlays/test/configmaps.yaml
solvers confimap consistency across the environments
> solvers confimap consistency across the environments

- core/overlays/stage/common/configmaps.yaml
- core/overlays/test/configmaps.yaml
Fixes: #588 
update the configmap with correct qebhwt URLs
> update the configmap with correct qebhwt urls

- investigator/overlays/test/deploymentconfig.yaml
- investigator/overlays/test/kustomization.yaml
https://github.com/thoth-station/messaging/issues/319
closes https://github.com/thoth-station/investigator/issues/346
Change env variables to reflect confluent kafka implementation
> confluent kafka deployment changes

- cve-update/overlays/test/cronjob.yaml
- cve-update/overlays/test/kustomization.yaml
To test changes we made in https://github.com/thoth-station/cve-update-job/pull/374
Related-To: https://github.com/thoth-station/cve-update-job/issues/373
> make cve-update kafka producer

- cve-update/overlays/test/cronjob.yaml
Fix the valye of `KAFKA_TOPIC_CONSUMER_ENABLE_AUTO_COMMIT`
> change bool to str value

- core/overlays/stage/common/configmaps.yaml
- core/overlays/stage/common/secrets.enc.yaml
- cve-update/overlays/test/cronjob.yaml
migrate stage deployment to use ocp kafka
> migrate stage deployment to use ocp kafka

- adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/1511
> Bump adviser to 0.19.1 in stage

- graph-refresh/base/cronjob.yaml
There are moments where Thoth is not learning. Let's increase while we have 1 solver to learn more.
> Increase packages considered while we have 1 solver running

- advise-reporter/base/cronjob.yaml
- advise-reporter/overlays/stage/imagestreamtag.yaml
> Bump advise-reporter version to v0.4.6 in stage

- adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/1531
> Bump adviser to v0.20.0 in stage

- nepthys/overlays/ocp/imagestreamtag.yaml
> bump up nepthys version

- core/overlays/ocp4-stage/common/configmaps.yaml
- core/overlays/prod/common/configmaps.yaml
- core/overlays/stage/common/configmaps.yaml
- core/overlays/test/configmaps.yaml
> Amun API URL should include version

- core/overlays/stage/common/imagestreamtags.yaml
bump up investigator and messaging versions
> bump up investigator and messaging versions

- investigator/base/deploymentconfig.yaml
update the investigator deployment config wrt to new changes
> update the investigator deploymentconfig wrt to new chnages

- core/overlays/stage/common/imagestreamtags.yaml
- investigator/base/deploymentconfig.yaml
would like to stabilize the kafka instance.
revert back to old faust based investigator
> revert back to old faust based investigator

- adviser/overlays/stage/imagestreamtag.yaml
https://github.com/thoth-station/adviser/pull/1548
> Bump adviser to version 0.20.1 in stage

- user-api/overlays/test/imagestreamtag.yaml
See issue reported in thoth-station/user-api#1133
> Downgrade user-api to v0.6.20 in stage environment

- amun/base/argo-workflows/inspection-build-with-cpu.yaml
- amun/base/argo-workflows/inspection-build.yaml
> Use here-strings instead of here documents

- amun/base/argo-workflows/inspection-build-with-cpu.yaml
- amun/base/argo-workflows/inspection-build.yaml
> Avoid expansion of envariables in here-documents

- amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
- amun/overlays/stage/amun-api/secrets.enc.yaml
updated argo artifact secrets for amun instance
> updated argo artifact secrets for amun instance

- core/overlays/ocp4-stage/middletier-stage/configmaps.yaml
- core/overlays/stage/middletier-stage/configmaps.yaml
Update resource quota so we want to use it to its full extent. 
update parallelism for middletier stage
> update parallelism for middletier stage

- prow/overlays/thoth-station/config.yaml
closes https://github.com/thoth-station/invectio/issues/82
> add pre-commit & pytest for invectio

- kebechet/base/argo-workflows/kebechet-run-url.yaml
- kebechet/base/argo-workflows/kebechet.yaml
- kebechet/base/openshift-templates/kebechet-run-url.yaml
- kebechet/base/openshift-templates/kebechet.yaml
Related to - https://github.com/thoth-station/kebechet/issues/585
Depends on - #639
> Added Env variables needed for Githubapp

- kebechet/overlays/stage/secrets.enc.yaml
- kebechet/overlays/test/secrets.enc.yaml
update kebechet secret with github app requirements
> update kebechet secret with github app requirements

- kebechet/overlays/test/imagestreamtag.yaml
> Bump Kebechet in test

- kebechet/base/openshift-templates/kebechet-run-url.yaml
- kebechet/overlays/test/imagestreamtag.yaml
Fixed entry point in the template
> Keb GitHub

- adviser/base/argo-workflows/advise.yaml
> Reduce beam width to reduce OOM risk

- adviser/base/openshift-templates/adviser.yaml
> Beam reduce

- adviser/base/argo-workflows/advise.yaml
> Decrease liveness to 20 mins for adviser

- adviser/base/argo-workflows/advise.yaml
- adviser/base/openshift-templates/adviser.yaml
> Give adviser more memory and restore old configuration

- adviser/base/argo-workflows/advise.yaml
> Bump adviser to 16Gi

- adviser/base/argo-workflows/advise.yaml
> Raise adviser requests to 20Gi memory

- core/overlays/stage/common/configmaps.yaml
set other solvers to be solved
> set other solvers to be solved

- solver/base/imagestreams.yaml
- solver/overlays/ocp4-stage/imagestreamtag.yaml
- solver/overlays/prod/imagestreamtag.yaml
- solver/overlays/stage/imagestreamtag.yaml
- solver/overlays/test/imagestreamtag.yaml
stick to solvers based on f32 and ubi8
> stick to solvers based on f32 and ubi8

- adviser/base/openshift-templates/adviser.yaml
Fixes: https://github.com/thoth-station/thamos/issues/614
> Add missing THOTH_ADVISER_DEV option

- adviser/overlays/stage/imagestreamtag.yaml
> Bump adviser to v0.21.0 in stage

- kebechet/overlays/stage/imagestreamtag.yaml
Kebechet updated in stage 
Tested on test - http://argo-ui-thoth-test-core.apps.ocp.prod.psi.redhat.com/workflows/thoth-test-core/kebechet-run-url-f73ee6b6?tab=workflow&nodeId=kebechet-run-url-f73ee6b6-3005651942
> Bump kebechet in stage

- kebechet/overlays/stage/imagestreamtag.yaml
- kebechet/overlays/test/imagestreamtag.yaml
> Bumped kebechet

- adviser/base/argo-workflows/advise.yaml
Reduce time for adviser runs, at least for now so we get results sooner.
> Reduce time after which adviser is cut off

- kebechet/overlays/test/imagestreamtag.yaml
> Test pr 610

- core/overlays/stage/common/imagestreamtags.yaml
- investigator/base/deploymentconfig.yaml
update stage investigator to the latest version
> update stage investigator to the latest version

- core/overlays/stage/common/imagestreamtags.yaml
- investigator/base/deploymentconfig.yaml
Reverts thoth-station/thoth-application#673
Due issues in investigator scheduling of adviser and kebechet run. 
Related-to: https://github.com/thoth-station/investigator/issues/383
> Revert "update stage investigator to the latest version"

- kebechet/overlays/stage/imagestreamtag.yaml
- kebechet/overlays/test/imagestreamtag.yaml
> Updated kebechet image

- qeb-hwt-github-app/overlays/test/imagestreamtag.yaml
qebhwt app is failing due to some missing parameter in octomachinery call. the pull-request to work through it. 
Include fix-test image to check on the qebhwt issue
> Include fix-test image to check on the qebhwt issue

- adviser/overlays/stage/imagestreamtag.yaml
https://github.com/thoth-station/adviser/issues/1595
> Bump adviser to version 0.21.1 in stage environment

- advise-reporter/overlays/stage/cronjob.yaml
- core/overlays/ocp4-stage/common/configmaps.yaml
- cve-update/overlays/stage/cronjob.yaml
- graph-refresh/overlays/stage/cronjob.yaml
- package-releases/overlays/stage/cronjob.yaml
- slo-reporter/base/cronjob.yaml
- slo-reporter/overlays/ocp4-stage/cronjob.yaml
- slo-reporter/overlays/stage/cronjob.yaml
- solver/overlays/ocp4-stage/imagestreamtag.yaml
- solver/overlays/stage/imagestreamtag.yaml
Switch data aggregating cronjob in ocp , pass the baton to ocp4
Related-to: #504
> Switch data aggregating cronjob in ocp , pass the baton to ocp4

- graph-refresh/base/cronjob.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/602
Reason:
> Reduce workflows to avoid Kafka limit for messages (Data Driven Engineering)

- slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
- slo-reporter/overlays/stage/imagestreamtag.yaml
> Bump SLO-reporter version to 0.7.0

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
> Bump workflow-helpers version in stage to v0.3.1

- graph-schema-update/base/imagestream.yaml
- graph-schema-update/base/kustomization.yaml
- graph-schema-update/base/openshift-templates/schemaUpdateJob-template.yaml
- graph-schema-update/overlays/ocp4-stage/job-generate-name.yaml
- graph-schema-update/overlays/ocp4-stage/kustomization.yaml
- graph-schema-update/overlays/ocp4-stage/put-into-infra-namespace.yaml
- graph-schema-update/overlays/ocp4-stage/thoth-notification.yaml
- graph-schema-update/overlays/prod/job-generate-name.yaml
- graph-schema-update/overlays/prod/kustomization.yaml
- graph-schema-update/overlays/prod/put-into-infra-namespace.yaml
- graph-schema-update/overlays/prod/thoth-notification.yaml
- graph-schema-update/overlays/stage/job-generate-name.yaml
- graph-schema-update/overlays/stage/kustomization.yaml
- graph-schema-update/overlays/stage/put-into-infra-namespace.yaml
- graph-schema-update/overlays/stage/thoth-notification.yaml
- graph-schema-update/overlays/test/job-generate-name.yaml
- graph-schema-update/overlays/test/kustomization.yaml
- graph-schema-update/overlays/test/thoth-notification.yaml
Successfully run in test to update schema async
Related-To: https://github.com/thoth-station/storages/issues/2080
> Add graph-schema-update

- graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
- graph-sync/overlays/stage/imagestreamtag.yaml
> Bump graph-sync to v0.8.0

- adviser/base/argo-workflows/advise.yaml
> Add more memory to adviser

- graph-refresh/base/cronjob.yaml
- investigator/base/deploymentconfig.yaml
> Disable all SI analysis

- graph-sync/overlays/stage/imagestreamtag.yaml
> bump graph-sync in stage to v0.8.1

- kebechet/overlays/stage/imagestreamtag.yaml
- kebechet/overlays/test/imagestreamtag.yaml
https://github.com/thoth-station/kebechet/pull/642
> Kebechet bump in test

- graph-refresh/overlays/ocp4-stage/cronjob.yaml
- package-releases/overlays/ocp4-stage/cronjob.yaml
- package-update/overlays/ocp4-stage/cronjob.yaml
Fixes: #701 
work in progress.
pause the data generation component for maintenance
> pause the data generation component for maintenance

- graph-refresh/overlays/ocp4-stage/cronjob.yaml
- package-releases/overlays/ocp4-stage/cronjob.yaml
- package-update/overlays/ocp4-stage/cronjob.yaml
Related-to: #701 
play the data generation components the maintenance is done
successfully completing.
```
Name:                solver-rhel-8-py38-eed2defc
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Succeeded
Conditions:          
Completed           True
Created:             Fri Dec 04 17:59:45 +0530 (3 minutes ago)
Started:             Fri Dec 04 17:59:45 +0530 (3 minutes ago)
Finished:            Fri Dec 04 18:02:46 +0530 (7 seconds ago)
Duration:            3 minutes 1 seconds
ResourcesDuration:   2m34s*(1 cpu),9m58s*(100Mi memory)
Parameters:          
ceph_bucket_prefix: data
ceph_bucket_name:  thoth
ceph_host:         s3.upshift.redhat.com
deployment_name:   ocp4-stage …
```
> play the data generation components the maintenance is done

- adviser/base/argo-workflows/kebechet-run-results.yaml
fix the referencing to the correct image for kebechet workflow
> fix the referencing to the correct image for kebechet workflow

- kebechet/overlays/test/imagestreamtag.yaml
Wait till quay gets image - https://quay.io/repository/thoth-station/kebechet-job?tab=tags
Related - https://github.com/thoth-station/kebechet/pull/649
> Bumped kebechet in test

- kebechet/overlays/ocp4-stage/imagestreamtag.yaml
- kebechet/overlays/stage/imagestreamtag.yaml
Update kebechet in stage
Tested on test cluster, seems to work normally!
> Bumped in stage

- core/overlays/ocp4-stage/middletier-stage/configmaps.yaml
Related-to: #701 
increase the workflow parallelism for middletier
we are utilizing 65-70% of the resource, let try to consume more.
> increase the workflow parallelism for middletier

- graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
- graph-sync/overlays/stage/imagestreamtag.yaml
- graph-sync/overlays/test/imagestreamtag.yaml
> Bumped graph sync job

- graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
- graph-sync/overlays/stage/imagestreamtag.yaml
> bump-graph-sync-to-0.8.4

- adviser/base/openshift-templates/adviser.yaml
patch the use of wrong secret in adviser workflow
> patch the use of wrong secret in adviser workflow

- mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
- mi-scheduler/base/openshift-templates/mi-run-template.yaml
https://github.com/thoth-station/mi-scheduler/pull/58
New `mi-kebechet-analyse-workflow`
Removes old processing step of mi workflow
Old `mi-worfklow` was renamed to `mi-anaylse-workflow`
> Add kebechet workflow, remove old processing step

- graph-refresh/base/cronjob.yaml
> Increase workflows scheduled

- core/overlays/ocp4-stage/graph-stage/postgresql-metrics-exporter.yaml
use imagestream instead of direct pull from quay
> use imagestream instead of direct pull from quay

- core/overlays/cnv-prod/common/secrets.enc.yaml
updated secrets for cnv prod kafka apps
> updated secrets for cnv prod kafka apps

- core/overlays/test/postgresql.yaml
utilize max storage size for the database in test 
> utilize max storage size for database

- metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
- metrics-exporter/overlays/stage/imagestreamtag.yaml
> Bump metrics-exporter to v0.9.0 in stage

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
> Bump workflow-helper to v0.3.3

- management-api/overlays/ocp4-stage/imagestreamtag.yaml
- management-api/overlays/stage/imagestreamtag.yaml
bump up the version of management-api for stage systems
> bump up the version of management-api for stage systems

- management-api/overlays/ocp4-stage/imagestreamtag.yaml
- management-api/overlays/stage/imagestreamtag.yaml
bump up the latest version of management-api for stage systems
> bump up the latest version of management-api for stage systems

- core/overlays/cnv-prod/graph-prod/postgresql.yaml
increase pvc size for the production database
our database requires more space for the updated data that happened due to the year-end data ingestion.
> increase pvc size for the production database

- advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
- advise-reporter/overlays/stage/imagestreamtag.yaml
> bump adviser-reporter to v0.5.0

- metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
- metrics-exporter/overlays/stage/imagestreamtag.yaml
> Bump metrics-exporter in stage to v0.9.1

- user-api/overlays/test/deploymentconfig.yaml
- user-api/overlays/test/kustomization.yaml
https://github.com/thoth-station/user-api/pull/1195
> deployment uses new env for config

- management-api/overlays/ocp4-stage/imagestreamtag.yaml
- management-api/overlays/stage/imagestreamtag.yaml
bump up the latest version of management-api
> bump up the latest version of management-api

- amun/overlays/cnv-prod/amun-inspection/argo-namespace-install.yaml
- amun/overlays/ocp4-stage/amun-inspection/argo-namespace-install.yaml
- amun/overlays/stage/amun-inspection/argo-namespace-install.yaml
fix of argocli with respect to the deployment
argo sync is failing to recognize the imagestream path and trying to use absolute path.
> fix of argocli with respect to the deployment

- amun/overlays/stage/amun-inspection/argo-namespace-install.yaml
debug the out-of-sync issue with argocli image
> debug the out-of-sync issue with argocli image

- advise-reporter/overlays/test/cronjob.yaml
- core/overlays/test/argo-workflows/send-message.yaml
- core/overlays/test/argo-workflows/send-messages.yaml
- core/overlays/test/kustomization.yaml
- package-releases/overlays/test/cronjob.yaml
- package-update/overlays/test/cronjob.yaml
https://github.com/thoth-station/package-update-job/pull/185
https://github.com/thoth-station/package-releases-job/pull/530
https://github.com/thoth-station/advise-reporter/pull/151
> update to latest messaging

- adviser/overlays/cnv-prod/imagestreamtag.yaml
- adviser/overlays/ocp4-stage/imagestreamtag.yaml
- adviser/overlays/prod/imagestreamtag.yaml
- adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/1621
> Bump adviser to v0.22.0

- advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
- advise-reporter/overlays/stage/imagestreamtag.yaml
> Bump advise reporter stage to v0.5.1

- graph-refresh/overlays/test/cronjob.yaml
https://github.com/thoth-station/graph-refresh-job/pull/548/
> update env in cron template

- user-api/overlays/ocp4-stage/imagestreamtag.yaml
- user-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/issues/1202
> Bump user-api to v0.11.1 in stage environments

- graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
- graph-sync/overlays/stage/imagestreamtag.yaml
> Bump graph-sync to v0.9.0 in stage

- graph-sync/base/argo-workflows/sync-template.yaml
Adjust all env variables for metric
> Adjust all envs

- management-api/overlays/ocp4-stage/imagestreamtag.yaml
- management-api/overlays/stage/imagestreamtag.yaml
> Bump management api stage to v0.10.0

- kafka/base/kustomization.yaml
- kafka/base/route.yaml
- kafka/base/service.yaml
- kafka/base/thoth-kafka.yaml
- kafka/overlays/README.md
- kafka/overlays/ocp-stage/deployment.yaml
- kafka/overlays/ocp-stage/kustomization.yaml
- kafka/overlays/ocp4-stage/deployment.yaml
- kafka/overlays/ocp4-stage/kustomization.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/508
support the deployment of Kafka for thoth
> support the deployment of kafka for thoth

- slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
- slo-reporter/overlays/stage/imagestreamtag.yaml
> Bump slo-reporter stage to v0.8.1

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
Related: https://github.com/thoth-station/thoth-application/pull/743
> Bump investigator to v0.8.2 in stage environments

- package-releases/overlays/ocp4-stage/imagestreamtag.yaml
- package-releases/overlays/stage/imagestreamtag.yaml
> Bump package release to v0.9.0

- build-watcher/base/configmap.yaml
- build-watcher/base/deploymentconfig.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/773
> Propagate new environment variables to build-watcher deployment

- advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
- amun/overlays/cnv-prod/amun-api/configmaps.yaml
- core/overlays/cnv-prod/backend-prod/configmaps.yaml
- core/overlays/cnv-prod/common/imagestreamtags.yaml
- core/overlays/cnv-prod/middletier-prod/configmaps.yaml
- management-api/overlays/cnv-prod/imagestreamtag.yaml
- metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
- package-releases/overlays/cnv-prod/imagestreamtag.yaml
- slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
upgrade of prod with stage versions
> upgrade of prod with stage versions

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
> Bump investigator stage to v0.9.0

- investigator/base/deploymentconfig.yaml
upgrade the investigator deploymentconfig
Fixes: https://github.com/thoth-station/investigator/issues/435
> upgrade the investigator deploymentconfig

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
- management-api/overlays/ocp4-stage/imagestreamtag.yaml
- management-api/overlays/stage/imagestreamtag.yaml
- metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
- metrics-exporter/overlays/stage/imagestreamtag.yaml
Bump components to stage with new metric feature for metrics-exporter, investigator and management-api
> Bump components versions to stage

- graph-refresh/overlays/ocp4-stage/cronjob.yaml
- package-releases/overlays/ocp4-stage/cronjob.yaml
- package-update/overlays/ocp4-stage/cronjob.yaml
suspend all data ingestion producers
Related-to: #797
> suspend all data ingestion producers

- sefkhet-abwy/base/deploymentconfig.yaml
- sefkhet-abwy/base/imagestream.yaml
- sefkhet-abwy/base/route.yaml
- sefkhet-abwy/base/service.yaml
- sefkhet-abwy/overlays/cnv-prod/configmap.yaml
- sefkhet-abwy/overlays/cnv-prod/imagestreamtag.yaml
- sefkhet-abwy/overlays/cnv-prod/kustomization.yaml
- sefkhet-abwy/overlays/cnv-prod/secrets.enc.yaml
- sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
- sefkhet-abwy/overlays/ocp/kustomization.yaml
- sefkhet-abwy/overlays/ocp/ultrahook.yaml
restructure sefkhet-abwy to separate prod and stage
Related-to: #800
> restructure sefkhet-abwy to separate prod and stage

- README.md
updated the docs for creating a new component
More docs updates are along the way. :train:
> updated the docs for creating a new component

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
> Bump workflow-helpers stage to v0.4.0

- graph-schema-update/base/openshift-templates/graph-schema-update-job-template.yaml
- kebechet/base/argo-workflows/kebechet-administrator.yaml
- solver/base/argo-workflows/parse-solver-output.yaml
Related-To: https://github.com/thoth-station/workflow-helpers/pull/197
Related-To: https://github.com/thoth-station/metrics-exporter/issues/529
> Add env variables for metrics

- slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
- slo-reporter/overlays/stage/imagestreamtag.yaml
> Bump SLO reporter stage to v0.8.2

- package-extract/overlays/ocp4-stage/imagestreamtag.yaml
- package-extract/overlays/stage/imagestreamtag.yaml
> Bump package-extract to v1.1.0 in stage

- slo-reporter/overlays/cnv-prod/configmap.yaml
- slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
- slo-reporter/overlays/ocp4-stage/configmap.yaml
Bump SLO reporter in prod to v0.8.2
change email recipient in stage to go to thoth-aicoe team
Related-To: https://github.com/thoth-station/thoth-application/issues/817
> Bump SLO reporter in prod and change email recipient in stage

- metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
- metrics-exporter/overlays/stage/imagestreamtag.yaml
- metrics-exporter/overlays/test/imagestreamtag.yaml
> Bump metrics-exporter to v0.10.1

- package-extract/base/argo-workflows/package-extract.yaml
Fixes: https://github.com/thoth-station/package-extract/issues/439
> Provide APP_SCRIPT envornmnet variable to run the application

- kebechet/overlays/ocp4-stage/imagestreamtag.yaml
- kebechet/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/s2i-thoth/issues/133
> Bump Kebechet to v1.2.4

- slo-reporter/overlays/cnv-prod/imagestreamtag.yaml
- slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
- slo-reporter/overlays/stage/imagestreamtag.yaml
> Bump SLO-reporter to v0.8.3 in stage and prod

- management-api/overlays/ocp4-stage/imagestreamtag.yaml
- management-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/management-api/issues/685
> Bump Management API in stage

- adviser/overlays/ocp4-stage/imagestreamtag.yaml
- adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/1643
> Bump adviser to v0.23.0 in stage

- advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
- advise-reporter/overlays/stage/imagestreamtag.yaml
> Bump advise-reporter to have all metrics

- thoth_release_procedure.md
Fixes: https://github.com/thoth-station/thoth-application/issues/822
> Create a document documenting the release procedure

- adviser/base/argo-workflows/parse-provenance-checker-output.yaml
- adviser/base/kustomization.yaml
- adviser/base/openshift-templates/provenance-checker.yaml
- core/overlays/cnv-prod/common/imagestreamtags.yaml
- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/818
> Extend provenance checker workflow with new steps

- package-extract/overlays/ocp4-stage/imagestreamtag.yaml
- package-extract/overlays/stage/imagestreamtag.yaml
> Bump package-extract to v1.1.2 in stage

- graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
- graph-refresh/overlays/stage/imagestreamtag.yaml
- graph-refresh/overlays/test/imagestreamtag.yaml
bump up the latest version of graph-refresh
> bump up the latest version of graph-refresh

- user-api/overlays/ocp4-stage/imagestreamtag.yaml
- user-api/overlays/stage/imagestreamtag.yaml
> Bump User API to v0.17.0 in stage environment

- advise-reporter/overlays/test/imagestreamtag.yaml
- graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
- graph-sync/overlays/stage/imagestreamtag.yaml
bump the version of graph-sycn in stage 
Already tested in the test env.
>  bump the version of graph-sycn in stage 

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
- core/overlays/stage/common/imagestreamtags.yaml
upgrade: bump the version of messaging in stage
> upgrade: bump the version of messaging in stage

- thoth_s2i_procedure.md
Fixes: 00https://github.com/thoth-station/thoth-application/issues/825
> Document Thoth's S2I and solver procedure

- core/overlays/cnv-prod/graph-prod/postgresql.yaml
upgrade prod database size
Related-to : #709
> upgrade prod database size

- investigator/overlays/ocp4-stage/deploymentconfig.yaml
- investigator/overlays/ocp4-stage/kustomization.yaml
debug argo worflow limits with investigator limits
Related-to: #797
> debug argo worflow limits with investigator limits

- amun/overlays/test/deploymentconfig.yaml
- amun/overlays/test/inspection-with-cpu-workflow.yaml
- amun/overlays/test/inspection-workflow.yaml
- amun/overlays/test/kustomization.yaml
Change deployment to point at test tag and update templates to have send-messages in workflow. This is to test changes in #398 and should be reverted after merging changes
> Debug amun api

- user-api/overlays/ocp4-stage/imagestreamtag.yaml
- user-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/issues/1247
Related: https://github.com/thoth-station/thoth-application/pull/873
> Bump User API to v0.18.0 in stage

- package-update/overlays/ocp4-stage/imagestreamtag.yaml
- package-update/overlays/stage/imagestreamtag.yaml
Thanks to @harshad16 for debugging and the bugfix.
Related: https://github.com/thoth-station/package-update-job/issues/187
Related: https://github.com/thoth-station/package-update-job/pull/198
> Update package-update-job to v0.8.7 in stage

- package-releases/overlays/ocp4-stage/cronjob.yaml
- package-update/overlays/ocp4-stage/cronjob.yaml
Update cronjob for the components with variable changes
> Update cronjob for the components with variable changes

- core/overlays/ocp4-stage/common/configmaps.yaml
- graph-refresh/overlays/ocp4-stage/cronjob.yaml
Debug the workflow limit with graph-refresh job
#797
> Debug the workflow limit with graph-refresh job

- core/overlays/ocp4-stage/common/configmaps.yaml
- graph-refresh/overlays/ocp4-stage/cronjob.yaml
revert debug change for the workflow limit test with graph-refresh job
#797
> revert debug change for the workflow limit test with graph-refresh job

- metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
- metrics-exporter/overlays/prod/imagestreamtag.yaml
- metrics-exporter/overlays/stage/imagestreamtag.yaml
> Bump metrics-exporter to v0.11.0

- prow/overlays/cnv-prod/config.yaml
https://github.com/operate-first/apps/pull/217
> add kustomize-build presubmit job to op1st/apps repo ʕʘ̅͜ʘ̅ʔ

- package-extract/base/argo-workflows/package-extract.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/887
> Fix path to container image analysis results

- grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
- grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
- grafana-dashboard/overlays/cnv-prod/thoth-service-metrics.json
use right datasource for cnv grafana dashboard
> use right datasource for cnv grafana dashboard

- slo-reporter/overlays/cnv-prod/secrets.enc.yaml
update slo-reporter secrets for cnv moc cluster
> update slo-reporter secrets for cnv moc cluster

- slo-reporter/overlays/cnv-prod/configmap.yaml
```
python_http_client.exceptions.ForbiddenError: HTTP Error 403: Forbidden
```
> Adjust parameters in CM

- slo-reporter/overlays/cnv-prod/configmap.yaml
> test domain to send email

- prow/overlays/cnv-prod/config.yaml
- prow/overlays/cnv-prod/imagestreamtags.yaml
- prow/overlays/cnv-prod/label-sync-cronjob.yaml
> use an imagestreamtag for integration-tests

- integration-tests/base/cronjob.yaml
- integration-tests/base/kustomization.yaml
- integration-tests/overlays/ocp4-stage/cronjob.yaml
- integration-tests/overlays/ocp4-stage/kustomization.yaml
- integration-tests/overlays/ocp4-stage/put-into-infra-namespace.yaml
- integration-tests/overlays/ocp4-stage/secret-generator.yaml
- integration-tests/overlays/ocp4-stage/secrets.enc.yaml
- integration-tests/overlays/test/cronjob.yaml
- integration-tests/overlays/test/kustomization.yaml
- integration-tests/overlays/test/secret-generator.yaml
- integration-tests/overlays/test/secrets.enc.yaml
- integration-tests/overlays/test/thoth-notification.yaml
update integration test setup manifests
> update integration test setup manifests

- integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
- integration-tests/overlays/test/imagestreamtag.yaml
> Bump integration-tests to use s2i application

- core/overlays/ocp4-stage/common/configmaps.yaml
switch on all solver in the stage env
> switch on all solver in the stage env

- user-api/base/configmap.yaml
- user-api/base/deploymentconfig.yaml
> User API does not use Amun

- management-api/base/deploymentconfig.yaml
- management-api/overlays/ocp4-stage/configmap.yaml
- management-api/overlays/ocp4-stage/kustomization.yaml
- management-api/overlays/stage/configmap.yaml
- management-api/overlays/stage/kustomization.yaml
- management-api/overlays/test/configmap.yaml
- management-api/overlays/test/kustomization.yaml
Related: https://github.com/thoth-station/management-api/pull/704 (needs a release)
> Validate responses by Management API in stage and test environments

- user-api/base/deploymentconfig.yaml
- user-api/overlays/ocp4-stage/configmap.yaml
- user-api/overlays/ocp4-stage/kustomization.yaml
- user-api/overlays/stage/configmap.yaml
- user-api/overlays/stage/kustomization.yaml
- user-api/overlays/test/configmap.yaml
- user-api/overlays/test/kustomization.yaml
Fixes: https://github.com/thoth-station/user-api/issues/1253
Related: https://github.com/thoth-station/user-api/pull/1254
Release: https://github.com/thoth-station/user-api/pull/1258
> Validate User API responses in stage and test

- adviser/base/argo-workflows/advise.yaml
- adviser/base/argo-workflows/dependency-monkey.yaml
- adviser/base/argo-workflows/provenance-check.yaml
> Enable preparing environment in adviser container

- .github/ISSUE_TEMPLATE/sprint-prod-release.md
Include sprint cycle release template
> Include sprint cycle release template

- amun/overlays/cnv-prod/amun-inspection/configmaps.yaml
- amun/overlays/ocp4-stage/amun-inspection/configmaps.yaml
set amun inspection time-to-live for 15min
> set amun inspection time-to-live for 15min

- slo-reporter/overlays/cnv-prod/secrets.enc.yaml
secrets are base64 encoded
secrets needs to be base64 encoded.
> secrets are base64 encoded

- integration-tests/overlays/ocp4-stage/cronjob.yaml
- integration-tests/overlays/test/cronjob.yaml
> Enable integration tests

- integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/integration-tests/issues/126
> Bump integration-tests to v0.6.0 in stage environment

- grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
Related-To: https://github.com/thoth-station/thoth-application/issues/938
> Correct labels to use templating

- amun/base/deploymentconfig.yaml
Related: https://github.com/thoth-station/integration-tests/issues/129
> Increase resources for Amun API

- prow/overlays/cnv-prod/config.yaml
Fixes: https://github.com/thoth-station/integration-tests/issues/125
> Adjust command for integration-tests in Prow

- management-api/base/deploymentconfig.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/950
> Provide Amun inspection namespace to management-api

- integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
- integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/integration-tests/issues/139
> Bump integration tests to v0.7.0

- user-api/overlays/cnv-prod/imagestreamtag.yaml
> Bump user-api to v0.19.3 in prod

- graph-refresh/overlays/cnv-prod/cronjob.yaml
enable learning on the prod server
> enable learning on the prod server

- core/overlays/cnv-prod/common/configmaps.yaml
learn ubi8-py38 stack on prod cluster
> learn ubi8-py38 stack on prod cluster

- advise-reporter/overlays/cnv-prod/thoth-notification.yaml
- adviser/overlays/cnv-prod/thoth-notification.yaml
- buildlog-parser/overlays/cnv-prod/thoth-notification.yaml
- chat-notification/overlays/cnv-prod/thoth-notification.yaml
- core/overlays/cnv-prod/backend-prod/thoth-notification.yaml
- core/overlays/cnv-prod/frontend-prod/thoth-notification.yaml
- core/overlays/cnv-prod/graph-prod/thoth-notification.yaml
- core/overlays/cnv-prod/infra-prod/thoth-notification.yaml
- core/overlays/cnv-prod/middletier-prod/thoth-notification.yaml
- cve-update/overlays/cnv-prod/thoth-notification.yaml
- graph-backup-job/overlays/cnv-prod/thoth-notification.yaml
- graph-refresh/overlays/cnv-prod/thoth-notification.yaml
- graph-schema-update/overlays/cnv-prod/thoth-notification.yaml
- graph-sync/overlays/cnv-prod/thoth-notification.yaml
- investigator/overlays/cnv-prod/thoth-notification.yaml
- kebechet/overlays/cnv-prod/thoth-notification.yaml
- management-api/overlays/cnv-prod/thoth-notification.yaml
- metrics-exporter/overlays/cnv-prod/thoth-notification.yaml
- package-extract/overlays/cnv-prod/thoth-notification.yaml
- package-releases/overlays/cnv-prod/thoth-notification.yaml
- package-update/overlays/cnv-prod/thoth-notification.yaml
- qeb-hwt-github-app/overlays/cnv-prod/thoth-notification.yaml
- revsolver/overlays/cnv-prod/thoth-notification.yaml
- security-indicators/overlays/cnv-prod/thoth-notification.yaml
- slo-reporter/overlays/cnv-prod/thoth-notification.yaml
- solver/overlays/cnv-prod/thoth-notification.yaml
- user-api/overlays/cnv-prod/thoth-notification.yaml
Update the cnv prod argocd url with the latest
> Update the cnv prod argocd url with the latest

- integration-tests/base/cronjob.yaml
> Configure liveness probe for integration-tests

- integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
https://github.com/thoth-station/integration-tests/issues/152
> Bump integration-tests to v0.7.1 in stage

- integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
> Bump integration-tests to v0.7.1 in prod

- package-extract/base/openshift-templates/package-extract.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/946
> Add flag to optionally sync results of package-extract

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
Bump version v0.9.2 for investigator stage
> Bump version v0.9.2 for investigator stage

- sefkhet-abwy/overlays/cnv-prod/imagestreamtag.yaml
- sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
Bump version v0.21.0 for sefkhet-abwy
> Bump version v0.21.0 for sefkhet-abwy

- core/overlays/cnv-prod/common/imagestreamtags.yaml
Bump version v0.9.2 for investigator prod
> Bump version v0.9.2 for investigator prod

- core/overlays/ocp4-stage/common/imagestreamtags.yaml
> Bump investigator to v0.10.0 in stage

- user-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/issues/1288
> Bump user-api to v0.20.1 in stage environment

- adviser/overlays/ocp4-stage/argo-workflows/advise.yaml
- adviser/overlays/ocp4-stage/argo-workflows/dependency-monkey.yaml
- adviser/overlays/ocp4-stage/argo-workflows/provenance-check.yaml
- adviser/overlays/ocp4-stage/kustomization.yaml
> Use data stored on Ceph in adviser containers in stage

- user-api/base/deploymentconfig.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/991
We boot 6 workers on 1 CPU which does not sound correct.
> Adjust web concurrency for user-api

- slo-reporter/overlays/ocp4-stage/cronjob.yaml
- slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
```
File "app.py", line 357, in <module>
main()
File "app.py", line 347, in main
run_slo_reporter(
File "app.py", line 275, in run_slo_reporter
configuration = Configuration(start_time=start_time, end_time=end_time, number_days=number_days, dry_run=dry_run)
File "/opt/app-root/src/thoth/slo_reporter/configuration.py", line 78, in __init__
self.sender_address = os.environ["SENDER_ADDRESS"]
File "/usr/lib64/python3.8/os.py", line 675, in __getitem__
raise KeyError(key) from None
KeyError: 'SENDER_ADDRESS'
```
> Update ocp4 stage slo-reporter
