slo-reporter/base/cronjob.yaml, slo-reporter/overlays/test/configmap.yaml, slo-reporter/overlays/test/secrets.enc.yaml
Signed-off-by: <hnalla@redhat.com>
https://github.com/thoth-station/slo-reporter/pull/5
update thanos token secret required by slo-reporter
The value is taken from thanos-reader secret in thoth-test-core
slo-reporter uses thanos-token to connect with thanos deployment.
=> update thanos token secret required by slo-reporter

init-job/overlays/test/imagestreamtag.yaml
Allow imagestream to auto update image
Allows openshift image stream to pull image tag from base registry periodically to keep it refreshed.
Reference: 
--schedule flag
https://docs.openshift.com/container-platform/3.11/dev_guide/managing_images.html#adding-tag
Technically, 
whenever a project is updated with a new feature, a new tag is released based on that, 
so Thoth bot would work together to bring that change to the cluster. 
with the new tag, the tag get updated in thoth-application which enables argo to update the cluster. 
the flow works well when we keep on going incrementally on the tag. 
However as we sometimes work on stabilizing one tag for example v0.6.0-dev, as argocd already provided on the open shift, I m not sure, if …
=> Allow imagestream to auto update image

core/overlays/test/configmaps.yaml, core/overlays/test/secrets.enc.yaml
Kafka setup in the thoth12 cluster
As the Kafka application is moved to different application hence, it could cause breakage due to missing of any resources.
Kafka application is moved to the thoth12 cluster as the thoth01 cluster was dropping down due to tekton application.
=> Kafka setup in the thoth12 cluster

metrics-exporter/overlays/stage/kustomization.yaml, metrics-exporter/overlays/stage/role_bindings.yaml
adding role bindings so that metrics-exporter can read-only from all namespaces
Depends-On: https://github.com/thoth-station/thoth-application/pull/34
=> adding role bindings

core/overlays/stage/kustomization.yaml, core/overlays/stage/roles/kustomization.yaml, core/overlays/stage/roles/metrics-exporter-reader.yaml
this role can be used by metrics-exporter to get view-access into all namespaces
This role has a very small read-only set of cabapilities
=> added a metrics-exporter-reader role to every stage namespace

core/overlays/test/argo-namespace-install.yaml
#44 
these change would add a role which can watch, create, delete and patch pods, this role is bonded to argo-server for  OnPodCompletion - delete pods immediately when pod is completed 
The role permission issue was observed in the cluster. 
```
time="2020-06-23T18:33:09Z" level=error msg="Failed to delete pod thoth-test-core/volumes-pvc-mzgs6-19516656 for gc: pods \"volumes-pvc-mzgs6-19516656\" is forbidden: User \"system:serviceaccount:thoth-test-core:argo-server\" cannot delete resource \"pods\" in API group \"\" in the namespace \"thoth-test-core\""
```
=> Provide workflow-role permission to agro-server sa

package-extract/base/openshift-templates/package-extract.yaml
sync fail due to no required params
fixes the argo sync up issue.
=> sync fail due to no required params

graph-refresh/base/kustomization.yaml, graph-refresh/base/role.yaml, graph-refresh/base/rolebindings.yaml, graph-refresh/base/serviceaccount.yaml
include serviceaccount and roles for apps fucntion
Fixes: https://github.com/thoth-station/graph-refresh-job/issues/398
Pull request contains serviceaccount and roles creation with binding them together, so graph-refresh-job can function.
=> include serviceaccount and roles for apps fucntion

graph-refresh/base/role.yaml, graph-refresh/base/rolebindings.yaml
use only required roles for graph-refresh-job
#58 
https://github.com/thoth-station/thoth-application/pull/77#issuecomment-655122673
https://github.com/thoth-station/thoth-application/pull/77#issuecomment-655123737
The application needs permissions to create the processed template, configmaps(graph-refresh-job roles), and workflows(argo-admin roles).
Tested this on test namespace in ocp cluster.
=> use only required roles for graph-refresh-job

cve-update/base/buildconfig.yaml, cve-update/base/cronjob.yaml, cve-update/base/imagestream.yaml, cve-update/base/kustomization.yaml, cve-update/overlays/stage/imagestreamtag.yaml, cve-update/overlays/stage/job-generate-name.yaml, cve-update/overlays/stage/kustomization.yaml, cve-update/overlays/stage/thoth-notification.yaml, cve-update/overlays/test/imagestreamtag.yaml, cve-update/overlays/test/job-generate-name.yaml, cve-update/overlays/test/kustomization.yaml, cve-update/overlays/test/thoth-notification.yaml
setup basic for cve-update application in ocp
#58 
Include cve-update-job  deployment via argocd
=> setup basic for cve-update application in ocp

adviser/base/openshift-templates/adviser.yaml
It might be still too large, let's observe any changes.
See https://thoth-station.ninja/docs/developers/adviser/deployment.html#beam-and-it-s-width
=> Decrease beam width for adviser

mi-scheduler/base/cronjob.yaml
This PR fixes absent `metadata.name` from cronjob yaml in #67
=> Add metadata.name to cronjob

core/overlays/test/argo-namespace-install.yaml
enable argoserver sa to access secrets
`secrets "argo-artifact-repository-secrets" is forbidden: User "system:serviceaccount:thoth-test-core:argo-server" cannot get resource "secrets" in API group "" in the namespace "thoth-test-core"`
Role would enable serviceaccount argo-server to list secrets and access them.
=> enable argoserver sa to access secrets

amun/base/argo-workflows/inspection-build-with-cpu.yaml, amun/base/argo-workflows/inspection-build.yaml
Fix storing of dockerfile artifact
Fixes: #100 
The copying content of Dockerfile doesn't require bash error checking.
=> Fix storing of dockerfile artifact

amun/overlays/test/configmaps.yaml
change from block indicator to normal string
The block indicator:
```
keyFormat: >-
{{workflow.parameters.ceph_bucket_prefix}}/
{{workflow.parameters.deployment_name}}/
inspections/
{{workflow.name}}
```
was creating spaces at the beginning.
as the string is still comparatively small, changed it to inline
=> change from block indicator to normal string

mi-scheduler/base/imagestream.yaml, mi-scheduler/overlays/test/imagestreamtag.yaml
imagestream required for mi scheduler workflows
The mi-scheduler cronjob was configured to wrong image.
=> imagestream required for mi scheduler workflows

mi-scheduler/base/cronjob.yaml, mi-scheduler/base/role.yaml, mi-scheduler/base/role_binding.yaml, mi-scheduler/base/serviceaccount.yaml
perms for mi scheduler to lookup on configmaps
```
"status":"Failure","message":"configmaps \\"mi-scheduler\\" is forbidden: User \\"system:serviceaccount:thoth-test-core:default\\" cannot get resource \\"configmaps\\" in API group \\"\\" in the namespace \\"thoth-test-core\\""
```
=> perms for mi scheduler to lookup on configmaps

adviser/overlays/test/secrets.enc.yaml
:lock: kebechet secret required for adviser
Fixes: #129 
Include kebechet needed secrets with the adviser.
kebechet secret are presently add to the adviser , we can further discuss on which other components need them.
=> kebechet secret required for adviser

mi-scheduler/base/cronjob.yaml
`mi-scheduler` runs in infra namespace and it has to know which one is that
`mi-scheduler` then submits workflows for mi project, which is run in middletier, so that namespace specification is needed as well
=> Add middletier and infra namespaces vars

core/overlays/test/kustomization.yaml
patch imagestream in kustomize for argo
Argo cd application test-thoth-core, didn't update imagestream in cluster, when the changes were made in git.
Included imagestreamtags to the Kustomize config, so argocd can see the difference in the image.
The imagestream tag would be patched when argocd application updates.
=> patch imagestream in kustomize for argo

mi-scheduler/base/role.yaml
mi-scheduler need perms to view configmaps
#139 #140
=> mi-scheduler need perms to view configmaps

mi-scheduler/base/cronjob.yaml
`mi-scheduler` also uses the GH API for repository inspection (if it is archived, if it exists, or scan all repos of an organization)
therefore new env var with sesheta-srcops github-access-token was added to the `mi-scheduler` cronjob
=> Add GH access token to cronjob

mi-scheduler/base/role.yaml
The `mi-scheduler` cronjob now uses `github-access-token` from `sesheta-srcops` secrets
=> Add secrets to resources for `mi-scheduler`

core/overlays/graph-stage/postgresql.yaml
better read-write connection.
change pvc storageclass from dynamic-nfs to standard
use ceph based storage for Postgresql in stage
=> use ceph based storage for postgresql

management-api/base/role_binding.yaml
Fixes: #159 
argo and argo-admin roles are required for scheduling workflows.
role_binding for management-api to schedule workflows
=> role_binding for management-api to schedule workflows

adviser/base/argo-workflows/dependency-monkey.yaml, adviser/base/argo-workflows/provenance-check.yaml
Fixes:
```
CreateContainerConfigError: couldn't find key prometheus-pushgateway-host in ConfigMap thoth-test-core/thoth
```
=> Fix configmap reference for Prometheus configuration

package-extract/overlays/stage/kustomization.yaml, package-extract/overlays/stage/put-into-infra-namespace.yaml
Fixes: #155 
The templates are placed in the infra stage.
place the package extract template in infra-stage
=> place the package extract template in infra-stage

amun/overlays/test/configmaps.yaml, core/overlays/test/configmaps.yaml
Otherwise, Dependency Monkey stores result in a file called `amun-api.thoth-test-core.svc` as it fails to detect service URL.
=> Amun API URL used in dependency monkey needs scheme

build-watcher/README.md, build-watcher/base/configmap.yaml, build-watcher/base/deploymentconfig.yaml, build-watcher/base/imagestreamtag.yaml, build-watcher/base/kustomization.yaml, build-watcher/base/role.yaml, build-watcher/base/role_binding.yaml, build-watcher/base/serviceaccount.yaml, build-watcher/overlays/amun-api/configmap.yaml, build-watcher/overlays/amun-api/imagestreamtag.yaml, build-watcher/overlays/amun-api/job-generate-name.yaml, build-watcher/overlays/amun-api/kustomization.yaml, build-watcher/overlays/amun-api/thoth-notification.yaml, build-watcher/overlays/test/buildconfig.yaml, build-watcher/overlays/test/configmap.yaml
migrated build-watcher to deploy with kustomize and agrocd
Related-to: https://github.com/thoth-station/thoth-application/issues/58
Includes manifests required for deployment of build-watcher.
As build-watcher would be a component that can be deployed to any namespace, tried to move the required information  in to the configmap for easy change by the user.
=> migrated build-watcher to deploy with kustomize and agrocd

advise-reporter/base/configmap.yaml, adviser/base/configmap.yaml, management-api/base/configmap.yaml, qeb-hwt-github-app/base/configmap.yaml, user-api/base/configmap.yaml, user-api/base/deploymentconfig.yaml
We no longer support use_argo configuration option to switch to old legacy workload-operator implementation.
=> Drop use-argo from configmaps

mi-scheduler/base/role.yaml
mi-scheduler cronjob currently still fails. A part of the error is:
```User \\"system:serviceaccount:thoth-test-core:mi-scheduler\\" cannot list resource \\"templates\\" in API group \\"template.openshift.io\\" in the namespace \\"thoth-test-core\\"","reason":"Forbidden","details":{"group":"template.openshift.io","kind":"templates"},"code":403}\n'```
and this could mean that the role currently set is not enough.
mi-scheduler has `list` added to the verbs and also apigroup `template.openshift.io` specified (https://github.com/thoth-station/thoth-application/blob/6818ef5fee948f46d56c116ad6e9a0e3bdd4bff6/mi-scheduler/base/role.yaml#L11-L17), however the openshift says otherwise.
was texting w/ @fridex and he suggested adding `view`, so maybe that could help
```2020-07-29 11:04:13,771   1 …
```
=> Add view verb

amun/overlays/test/configmaps.yaml, core/overlays/graph-stage/postgresql.yaml, mi-scheduler/base/role.yaml
upgrade postgresql pvc
from 32Gi to 64Gi, we have 120 Gi storage limit in the clusters.
=> upgrade postgresql pvc

amun/base/role.yaml
amun workflow requires pod logs access
`Error from server (Forbidden): pods "inspection-test-name-e1fa146d-1-build" is forbidden: User "system:serviceaccount:thoth-test-core:amun-api-workflow" cannot get resource "pods/log" in API group "" in the namespace "thoth-test-core"
`
give role perms for pods/logs.
=> amun workflow requires pod logs access

amun/base/role.yaml
amun workflow requires pods patch access
Forgot to add this in pervious PR: #190
=> amun workflow requires pods patch access

amun/base/argo-workflows/inspection-run-with-cpu.yaml, amun/base/argo-workflows/inspection-run.yaml, amun/overlays/amun-inspection/argo-namespace-install.yaml, amun/overlays/stage/kustomization.yaml, amun/overlays/stage/secrets.enc.yaml, amun/overlays/test/buildconfig.yaml
- This error was caused by workflow-controller-config not containing:  `containerRuntimeExecutor: "k8sapi"`
```
pods "inspection-test-bad96503-2767987541" is forbidden: unable to validate against any security context constraint: [spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used]
```
- Images are to be present in correct namespace.
- missing secrets
include new secrets, updates kustomize and configmaps
amun stage deployment fixes
=> amun stage deployment fixes

core/overlays/middletier-stage/argo-namespace-install.yaml
upgrade workflow-controller with more memory
workflow controller is crash looping in middletier
=> upgrade workflow-controller with more memory

core/overlays/middletier-stage/argo-namespace-install.yaml
use quay based images for argo server and workflow controller in middletier
dockerhub is restricting the number times an image pulls
=> use quay based images for argo workflow controller

solver/base/openshift-templates/solve_and_sync-template.yaml
Let's decrease solver TTL so that solvers finish faster and we can check number of solvers pending.
=> Decrease solver TTL

solver/base/openshift-templates/solve_and_sync-template.yaml
Solver fails to send the topic message to Kafka.
allow workflows to access kafka crt from secrets.
provide kafka-secrets for solver send message
=> provide kafka-secrets for solver send message

core/overlays/backend-stage/argo-namespace-install.yaml, core/overlays/backend-stage/argo-ui-route.yaml, core/overlays/backend-stage/argo-workflow-controller-metrics.yaml, core/overlays/backend-stage/configmaps.yaml, core/overlays/backend-stage/kustomization.yaml, core/overlays/middletier-stage/argo-ui-route.yaml, core/overlays/middletier-stage/kustomization.yaml, core/overlays/stage/configmaps.yaml, core/overlays/stage/imagestreamtags.yaml, core/overlays/test/configmaps.yaml
setup backend namespace with argo workflow controller
Related-To: #187 
- include workflow-controller manifest in backend-namespace to setup argo
- update configmaps and kustomize.yaml
- setup backend namespace for adviser workflow to execute.
- allow all the data to be stored in ocp-{stage|test} ceph bucket.
=> setup backend namespace with argo workflow controller

advise-reporter/base/cronjob.yaml, core/overlays/test/configmaps.yaml
Fixes: https://github.com/thoth-station/advise-reporter/issues/57
Add missing variables to run advise-reporter
=> Add missing env variables for advise-reporter

user-api/overlays/stage/role-binding.yaml
Allow the user-api to schedule workflow in backend
fixes: #235 
user-api serviceaccount is added with role_binding to use agro-admin role to create workflow in backend.
adviser workflows are scheduled in the backend namespace.
=> Allow the user-api to schedule workflow in backend

kebechet/base/kustomization.yaml, kebechet/overlays/stage/kustomization.yaml, kebechet/overlays/test/kustomization.yaml
argocd application for `stage-thoth-kebechet` is having issues creating.
- used base kustomize to define argo workflow and openshift templates.
manifest files in different directory are not fetched directly
=> manifest files in different directory are not fetched directly

kebechet/base/kustomization.yaml
Fix the wrong spelling of the directory
missed the `s` in openshift-templates. causing issues in argocd kebechet stage application.
=> Fix the wrong spelling of the directory

core/overlays/stage/imagestreamtags.yaml, core/overlays/test/imagestreamtags.yaml
investigater image is required by adviser in stage
`Failed to pull image "image-registry.openshift-image-registry.svc:5000/thoth-backend-stage/investigator:latest": rpc error: code = Unknown desc = Error reading manifest latest in image-registry.openshift-image-registry.svc:5000/thoth-backend-stage/investigator: manifest unknown: manifest unknown`
included investigator image to be deployed in stage.
=> investigater image is required by adviser in stage

adviser/base/argo-workflows/trigger-integration.yaml, qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
Fix mis-match of workflow-helper env vars
workflow failed after a adviser run: `/opt/app-root/src/app.sh: line 13: THOTH_WORKFLOW_TASK: THOTH_WORKFLOW_TASK is not selected!`
workflow helper requires `THOTH_WORKFLOW_TASK` 
https://github.com/thoth-station/workflow-helpers/blob/ac25943b8aecd060461bd90648a979c8332445c6/app.sh#L13
=> Fix mis-match of workflow-helper env vars

user-api/overlays/stage/role-binding.yaml
thamos log requires user-api to have access for pod logs
thamos log fails as user-api dont have permission to access pod-logs in backend namespace.
=> thamos log requires user-api to have access for pod logs

advise-reporter/base/deploymentconfig.yaml
Provided required env vars for advise-reporter-consumer
Fixes: #244 
- Add thoth-environment and other required env-vars.
- Advise-reporter-consumer is crashlooping due to unavailable env-vars, included them with this update.
=> Provided required env vars for advise-reporter-consumer

amun/overlays/stage/imagestreamtag.yaml, amun/overlays/test/kustomization.yaml
deploy amun-api tag v0.7.6 to stage cluster
- updated new version
- functioning in test.
=> deploy amun-api tag v0.7.6 to stage cluster

adviser/overlays/stage/imagestreamtag.yaml
Depends-On: https://github.com/thoth-station/adviser/issues/1112
=> Bump adviser version to 0.14.0 in stage env

amun/overlays/test/kustomization.yaml, amun/overlays/test/secret-generator.yaml, management-api/overlays/stage/kustomization.yaml, management-api/overlays/stage/secret-generator.yaml, management-api/overlays/test/kustomization.yaml, management-api/overlays/test/secret-generator.yaml, user-api/overlays/stage/kustomization.yaml, user-api/overlays/stage/secret-generator.yaml, user-api/overlays/test/kustomization.yaml, user-api/overlays/test/secret-generator.yaml
Argo-cd was unable to decrypt the encrypted tls certs.
- Added a secret generator kustomize file, which uses ksops to decrypt the encrypt of sops content.
ensure tls cert are decrypted by argo
=> ensure tls cert are decrypted by argo

amun/overlays/amun-inspection/argo-namespace-install.yaml
... also pull images from quay.io not to hit dockerhub limits.
=> Use Argo 2.9.5 for Amun

core/overlays/stage/imagestreamtags.yaml, core/overlays/test/imagestreamtags.yaml, graph-refresh/overlays/stage/imagestreamtag.yaml, graph-refresh/overlays/test/imagestreamtag.yaml
Related-to: https://github.com/thoth-station/graph-refresh-job/issues/449
Bump image version for core images
=> Bump image version for core images

amun/overlays/stage/imagestreamtag.yaml
Depends-On: https://github.com/thoth-station/amun-api/issues/541
=> Bump Amun API in stage version to 0.9.1

amun/base/kustomization.yaml, amun/base/roles/kustomization.yaml, amun/overlays/amun-api/kustomization.yaml, amun/overlays/amun-api/metrics-exporter-reader.yaml, amun/overlays/amun-inspection/kustomization.yaml, amun/overlays/amun-inspection/metrics-exporter-reader.yaml
metrics-exporter-reader role is added to both amun-api and amun-inspection namespaces.
move the metric exporter role to individual applications
=> move the metric exporter role to individual applications

adviser/base/argo-workflows/kebechet-run-results.yaml
2Gi feels like too much for this task
=> Lower requirements for kebechet-run-results

core/overlays/backend-stage/configmaps.yaml
Related-to: #294 
- reduce resource requirement for argoexec through workflow-controller-configmaps.
https://github.com/argoproj/argo/blob/c352f69d95ce6cb72bbd1f464655b6ba519b8b87/docs/workflow-controller-configmap.yaml#L109
lower argoexec resource requirement
lets test this in backend stage,if the observation make our requirement then we can replicate every namespace with this.
=> lower argoexec resource requirement

kebechet/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/kebechet/pull/496
See automatically image in quay based on the kebechet repo push https://quay.io/repository/thoth-station/kebechet-job?tab=tags see https://github.com/thoth-station/kebechet/pull/496 for more info.
=> Bump Kebechet in stage to v0.6.1

adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/1143
=> Bump adviser to v0.15.0 in stage environment

kebechet/overlays/stage/imagestreamtag.yaml
Fixes: https://github.com/thoth-station/kebechet/issues/497
=> Propagate Kebechet in version 0.6.2 to stage

slo-reporter/base/cronjob.yaml
```
INFO:thoth.slo_reporter:Considering interval for metrics of 1 day/s.
INFO:thoth.slo_reporter:THOTH_EVALUATION_METRICS_NUMBER_DAYS set to 1.
INFO:thoth.slo_reporter:Interval: 2020-08-26 - 2020-08-27
INFO:thoth.slo_reporter.sli_report:Thoth Service Level Indicators Update Day (2020-08-27)
File "app.py", line 328, in <module>
main()
File "app.py", line 323, in main
day_of_week=day_of_week,
File "app.py", line 255, in run_slo_reporter
sli_report = SLIReport(configuration=configuration)
File "/opt/app-root/src/thoth/slo_reporter/sli_report.py", line 64, in __init__
SLIPyPIKnowledgeGraph._SLI_NAME: SLIPyPIKnowledgeGraph(configuration=self.configuration)._aggregate_info(),
File …
```
=> Correct variable name

adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/pull/1149
=> Bump adviser version in stage to v0.15.1

user-api/overlays/stage/imagestreamtag.yaml
=> Bump user-api to v0.6.14 in stage environment

management-api/overlays/stage/imagestreamtag.yaml
=> Bump management-api to v0.6.4 in stage

user-api/overlays/stage/imagestreamtag.yaml
See https://github.com/thoth-station/user-api/pull/1039
=> Bump User API to v0.6.15 in stage

management-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/management-api/issues/560
=> Bump management-api to v0.7.0 in stage

management-api/overlays/stage/imagestreamtag.yaml
Reverts thoth-station/thoth-application#348
I will try to revert this, inspections do not run, no workflows are scheduled. Checking if this update could cause it.
=> Revert "Bump management-api to v0.7.0 in stage"

management-api/overlays/stage/imagestreamtag.yaml
See fix in https://github.com/thoth-station/thoth-application/pull/350
=> Revert "Revert "Bump management-api to v0.7.0 in stage""

adviser/base/openshift-templates/adviser.yaml, adviser/base/openshift-templates/dependency-monkey.yaml
```
Failed: invalid spec: templates.dependency-monkey.tasks.dm templates.dm inputs.parameters.THOTH_ADVISER_PREDICTOR_CONFIG was not supplied
```
=> Fix propagation of predictor and predictor config to argo dag

metrics-exporter/overlays/stage/imagestreamtag.yaml
=> Bump metrics-exporter version to v0.8.7 in stage

kebechet/base/openshift-templates/kebechet.yaml, qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml, revsolver/base/openshift-templates/revsolve_and_sync-template.yaml, security-indicators/base/openshift-templates/security-indicators.yaml, solver/base/openshift-templates/solve_and_sync-template.yaml
We do not need to keep objects in the cluster, they can be garbage collected. Otherwise, they occupy quota. All the relevant information regarding failures are reported into Sentry.
=> Always perform garbage collection of pods

adviser/overlays/stage/imagestreamtag.yaml
https://github.com/thoth-station/adviser/issues/1167
=> Bump adviser to v0.16.0 in stage

solver/base/argo-workflows/parse-solver-inputs.yaml, solver/base/openshift-templates/solve_and_sync-template.yaml
Related-To: https://github.com/thoth-station/workflow-helpers/pull/52
Modify logic to have component name and service name sending a Kafka message
Need new release of workflow-helpers
=> Modify templates for component name and service

amun/overlays/amun-inspection/configmaps.yaml
... as amun inspections run builds, Argo has no control on resources used by
builds. This leads to issues when a workflow is stuck waiting for a build that
failed because of resources available in the cluster.
=> Reduce workflow parallelism to 1 in amun-inspection-stage

core/overlays/middletier-stage/configmaps.yaml
It looks like workflow-controller goes into some deadlock after some time - pods are not scheduled due to resources but also, the finished ones do not proceed. I suspect it's some bug in resources handling. Let's try to decrease parallelism.
=> Reduce parallelism in thoth-middletier-stage

adviser/overlays/stage/imagestreamtag.yaml
https://github.com/thoth-station/adviser/pull/1171#issue-481594416
=> Bump adviser to version 0.16.0 in stage

user-api/base/role.yaml
Related-to: #390 
- patch the roles as pod/logs are not created  
patch the roles for pods logs
=> patch the roles for pods logs

core/overlays/stage/imagestreamtags.yaml
```
adviser-ebbaf505-2915049997: 2020-09-14 07:04:30,056   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
adviser-ebbaf505-2915049997: 2020-09-14 07:04:30,056   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
adviser-ebbaf505-2915049997:   File "select_thoth_integration.py", line 56, in trigger_integration_workflow
adviser-ebbaf505-2915049997:     f"Not all inputs to trigger finished webhook are provided: {parameters}"
adviser-ebbaf505-2915049997: 
adviser-ebbaf505-2915049997: thoth.workflow_helpers.exception.TriggerFinishedWebhookInputsMissing: Not all inputs to trigger finished webhook are provided: {'workflow_name': 'adviser-ebbaf505', 'github_base_repo_url': None, …
```
=> Bump workflow helpers version to v0.1.7

core/base/argo-workflows/send-messages.yaml, solver/base/argo-workflows/parse-solved-package.yaml, solver/base/argo-workflows/parse-solver-inputs.yaml, solver/base/openshift-templates/solve_and_sync-template.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/413
Use the correct name of the file to avoid overlapping paths.
Reference: https://github.com/thoth-station/workflow-helpers/blob/cf94990bbddaecb98175bc39abbbf40a32dc04c3/parse_solved_package.py#L148
=> Use correct output file name

user-api/overlays/stage/imagestreamtag.yaml
=> Bump user-api to v0.6.16 in stage

metrics-exporter/overlays/stage/imagestreamtag.yaml, metrics-exporter/overlays/test/imagestreamtag.yaml
Bump metrics-exporter version to v0.8.8
=> Bump metrics-exporter version to v0.8.8

core/overlays/test/imagestreamtags.yaml
Related-To: https://github.com/thoth-station/adviser/issues/1178
Bump version of graph-sync job
=> Bump graph-sync version to v0.7.3

user-api/overlays/stage/imagestreamtag.yaml
... this is also probably the last release that is without Kafka support.
=> Bump User API to v0.16.7 in stage environment

adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/1226
Fixes: https://github.com/thoth-station/thoth-application/issues/445
=> Bump adviser version to 0.17.0 in stage

graph-backup-job/overlays/stage/cronjob.yaml, graph-backup-job/overlays/stage/imagestreamtag.yaml, graph-backup-job/overlays/stage/job-generate-name.yaml, graph-backup-job/overlays/stage/kustomization.yaml, graph-backup-job/overlays/stage/thoth-notification.yaml, graph-backup-job/overlays/test/imagestreamtag.yaml, graph-backup-job/overlays/test/job-generate-name.yaml, graph-backup-job/overlays/test/kustomization.yaml, graph-backup-job/overlays/test/thoth-notification.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/353
- setup kustomize manifest to handle graph-backup with argocd
setup kustomize manifest to handle graph-backup with argocd
=> setup kustomize manifest to handle graph-backup with argocd

version.py
See https://github.com/thoth-station/thoth-application/releases/tag/2020.09.17
With this change, next `New calendar release` issue will trigger computing changelog based on the changes since the last tagged version (that is `2020.09.17`). See https://github.com/thoth-station/kebechet/tree/master/kebechet/managers/version#available-package-release-commands
=> Adjust version string based on the last version identifier

graph-sync/overlays/stage/imagestreamtag.yaml, security-indicators/overlays/stage/imagestreamtag.yaml
Related-To: https://github.com/thoth-station/adviser/issues/1178
Bump versions for SI workflow to start collecting SI about packages
=> Move SI workflow to stage to start collecting SI

metrics-exporter/base/deploymentconfig.yaml
```
Error: couldn't find key instance-metrics-exporter-frontend in ConfigMap thoth-test-core/prometheus
```
Depends-On: https://github.com/thoth-station/metrics-exporter/pull/521
=> Use infra env variable

graph-refresh/overlays/test/cronjob.yaml
Add env variables to test not sending messages for revsolver and si unanalyzed
Depends on - https://github.com/thoth-station/graph-refresh-job/pull/496
Related - https://github.com/thoth-station/graph-refresh-job/issues/488
=> Stop revsolver and security messages

core/overlays/test/argo-namespace-install.yaml
would like to rely on the internal registry
include imagestream with refrencepolicy:local
enable argocli and wc to use local images
=> enable argocli and wc to use local images

amun/overlays/amun-inspection/argo-namespace-install.yaml, core/overlays/backend-stage/argo-namespace-install.yaml, core/overlays/backend-stage/kustomization.yaml, core/overlays/middletier-stage/argo-namespace-install.yaml, core/overlays/middletier-stage/kustomization.yaml, metrics-exporter/overlays/stage/imagestreamtag.yaml
- use argo v2.11.0 in stage deployment
- Bump version v0.8.13 for metrics-exporter stage
=> update argo workloads and metrics-exporter

package-update/base/kustomization.yaml
argo application is falling due this.
route and service are removed as they don't exist anymore.
remove non used manifest from kustomize manifest
=> remove non used manifest from kustomize manifest

kebechet/overlays/prod/imagestreamtag.yaml, kebechet/overlays/stage/imagestreamtag.yaml, kebechet/overlays/test/imagestreamtag.yaml
:ship: Bump version v1.0.9 for kebechet
Related-To: https://github.com/thoth-station/user-api/issues/1080
=> Bump version v1.0.9 for kebechet

qeb-hwt-github-app/overlays/ocp/imagestreamtag.yaml, user-api/overlays/stage/imagestreamtag.yaml
Bump versions to schedule workflows correctly with new thoth-common
=> Bump versions for qeb-hwt and user-api

adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/1298
=> Bump adviser to v0.18.0 in stage

graph-refresh/base/cronjob.yaml
```
020-09-25 17:22:51,112] [1] [ERROR] [^Worker]: Error: ConfigurationError('Infra namespace is required in order to list solvers',) 
File "/opt/app-root/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
self.loop.run_until_complete(self._starting_fut)
File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
return future.result()
File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 736, in start
await self._default_start()
File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
await self._actually_start()
File "/opt/app-root/lib/python3.6/site-packages/mode/services.py", line 767, …
```
=> add missing variables to list solvers

management-api/overlays/stage/imagestreamtag.yaml
=> Bump management-api to v0.7.2 to update schema

core/overlays/stage/imagestreamtags.yaml, metrics-exporter/overlays/stage/imagestreamtag.yaml
stage overlays changes for `core` and `metrics-exporter` imagestreams
```
name: quay.io/thoth-station/investigator:v0.5.1
name: quay.io/thoth-station/metrics-exporter:v0.8.15
name: quay.io/thoth-station/messaging:v0.7.10
```
=> Bump multiple component releases to stage

metrics-exporter/overlays/stage/imagestreamtag.yaml
=> Bump metrics-exporter version to v0.8.16

core/overlays/stage/imagestreamtags.yaml, security-indicators/base/argo-workflows/download-package-template.yaml, security-indicators/base/openshift-templates/security-indicators.yaml, solver/base/openshift-templates/solve_and_sync-template.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/507
- Introduce new SI workflow modified to handle SI packages that cannot be analyzed by SI workflow due to missing distro.
finalizing work done with @KPostOffice 
nominal behaviour of SI workflow
```
STEP                                    TEMPLATE                           PODNAME                                 DURATION  MESSAGE
✔ security-indicator-daf9123a          security-indicators                                                                                                                 
├-✔ download-package                   download-package/download-package  security-indicator-daf9123a-2672485178  41s …
```
=> Thoth does not SI analyze package that do not provide distro

core/overlays/stage/configmaps.yaml
`Error: couldn't find key user-api-url in ConfigMap thoth-frontend-stage/prometheus`
=> Add missing parameter in core CM

core/base/configmaps.yaml, core/overlays/stage/configmaps.yaml, core/overlays/test/configmaps.yaml, qeb-hwt-github-app/overlays/ocp/configmap.yaml, qeb-hwt-github-app/overlays/ocp/kustomization.yaml
`CreateContainerConfigError: configmap "qeb-hwt-workflow" not found` in trigger integration task in adviser workflow
=> Move CM to core so it is available to adviser and qeb-hwt

advise-reporter/base/cronjob.yaml, advise-reporter/overlays/stage/cronjob.yaml, advise-reporter/overlays/stage/imagestreamtag.yaml, advise-reporter/overlays/test/cronjob.yaml
Activate advise reporter in stage
=> Activate advise reporter in stage

metrics-exporter/base/role.yaml
Fixes: #555 
- roles are added for metrics-exporter.
allow metrics exporter to get imagestreams
=> allow metrics exporter to get imagestreams

adviser/base/argo-workflows/investigate-unresolved-package.yaml
One task in adviser workflow fails:
```
THOTH_ADVISER_LIBRARY_USAGE: {"report": {"template": ["template.version.__version__"]}, "version": "0.0.7"}
THOTH_ADVISER_REQUIREMENTS_FORMAT: pipenv
THOTH_ADVISER_RECOMMENDATION_TYPE: security
THOTH_ADVISER_RUNTIME_ENVIRONMENT: {"hardware": {"cpu_family": null, "cpu_model": null}, "operating_system": {"name": "ubi", "version": "8"}, "python_version": "3.6", "cuda_version": null, "name": "ubi8", "platform": null}
THOTH_ADVISER_METADATA: {"github_event_type": null, "github_check_run_id": null, "github_installation_id": null, "github_base_repo_url": null, "origin": "git@github.com:pacospace/thamos-advise-security.git", "re_run_adviser_id": null, "source_type": "CLI"} …
```
=> Add missing variable for adviser to send messages

nepthys/overlays/ocp/imagestreamtag.yaml
Related-to: #563 
The kebechet release management is stuck in the pipeline, the consumer is having trouble scheduling these workflows.
causing hindrance in the release cycle. Following issue is stuck https://github.com/thoth-station/nepthys/issues/42
For the time being, this dev image is developed for the successful execution of the application.
updated the imagestream to new version of image.
bump nepthys image version v0.2.2-dev
=> bump nepthys image version v0.2.2-dev

advise-reporter/base/cronjob.yaml, adviser/base/argo-workflows/investigate-unresolved-package.yaml, core/base/argo-workflows/send-message.yaml, core/base/argo-workflows/send-messages.yaml, core/overlays/stage/configmaps.yaml, core/overlays/test/configmaps.yaml, graph-refresh/base/cronjob.yaml, investigator/base/deploymentconfig.yaml, package-releases/base/cronjob.yaml, package-update/base/cronjob.yaml, user-api/base/deploymentconfig.yaml
updated the environment variable required for kafka connection.
setup kafka-protocol env var for all kafka using applications
This variable is required in any application using `thoth-messaging>0.7.11`
=> setup kafka-protocol env var for all kafka using applications

adviser/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/pull/1504
=> Bump adviser to v0.19.0 in stage

adviser/base/argo-workflows/advise.yaml
Fixes: https://github.com/thoth-station/common/issues/1004
=> Set logging to WARNING for sentry_sdk.errors logger

adviser/base/argo-workflows/advise.yaml
Related: https://github.com/thoth-station/adviser/pull/1527
With  https://github.com/thoth-station/adviser/pull/1527 we implemented https://github.com/thoth-station/adviser/issues/1526. When running adviser in deployment, we expect the first liveness probe to send SIGUSR1 signal which tells predictor to perform the exploitation phase as it will soon be terminated. The second signal SIGINT is handled by the resolver to stop the resolution process and report back any results computed so far. With SIGUSR1 and subsequent SIGINT signals, we are able to start the exploitation phase (if it haven't been reached until that point) before the adviser terminates and deliver better results that were found until that point.
=> Add additional wait before the resolver is terminated

management-api/overlays/stage/imagestreamtag.yaml
Fixes: thoth-station/storages#2072
=> Bump management-api to v0.8.0 in stage

management-api/overlays/stage/imagestreamtag.yaml
=> Bump management-api to v0.8.1 in stage

user-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/issues/1130
=> Bump user-api to v0.7.0 in stage environment

user-api/overlays/stage/imagestreamtag.yaml
Reverts thoth-station/thoth-application#621
See issue reported in https://github.com/thoth-station/user-api/issues/1133
=> Revert "Bump user-api to v0.7.0 in stage environment"

amun/base/argo-workflows/inspection-build-with-cpu.yaml, amun/base/argo-workflows/inspection-build.yaml
Related: #624 
```
+ results=/mnt/build/
+ mkdir -p /mnt/build/
+ kubectl logs inspection-test-dca0953e-1-build
+ jq .
+ cat registry.access.redhat.com/ubi8/python-36, batch_size: 1, build: '{requests:' '{cpu:' 1, hardware: '{cpu_family:' 6, cpu_model: 94, physical_cpus: 32, processor: 'Intel-Xeon-Processor-Skylake-IBRS},' memory: '1Gi}},' environment: '[{name:' string, value: 'string}],' files: '[{content:' string, path: 'string}],' identifier: test, package_manager: micropipenv, packages: '[vim],' python: '{requirements:' '{},' requirements_locked: '{}},' python_packages: '[pipenv],' run: '{requests:' '{cpu:' 1, hardware: '{cpu_family:' 6, cpu_model: 94, physical_cpus: 32, processor: 'Intel-Xeon-Processor-Skylake-IBRS},' memory: '512Mi}},' script: '#!/usr/bin/bash\necho "Here should be …
```
=> Fix expansion of env variables

amun/base/argo-workflows/inspection-build-with-cpu.yaml, amun/base/argo-workflows/inspection-build.yaml
```
+ results=/mnt/build/
+ mkdir -p /mnt/build/
+ kubectl logs inspection-test-8641726c-1-build
+ cat '"Here' should be run 'tests..."n, update: true, upgrade_pip: false, @created: 2020-11-09T12:54:44.755753}'
+ jq .
cat: '"Here': No such file or directory
cat: should: No such file or directory
cat: be: No such file or directory
cat: run: Is a directory
cat: 'tests..."n, update: true, upgrade_pip: false, @created: 2020-11-09T12:54:44.755753}': No such file or directory
```
Related: #624 #625
=> Another try to fix expansion

user-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/pull/1138
=> Bump User API to v0.8.0 in stage

core/overlays/stage/common/imagestreamtags.yaml, core/overlays/test/imagestreamtags.yaml
update investigator stage to v0.5.6 to run with messaging v0.7.13
=> update investigator stage to v0.5.6 to run with messaging v0.7.13

graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml, graph-refresh/overlays/stage/imagestreamtag.yaml
bump up graph-refresh job to v0.2.9
With updated investigator, now it consumes topics with versions. The graph-refresh-job is also to be updated to the same level of messaging to have unresolved packages consumed.
=> bump up graph-refresh job to v0.2.9

package-update/overlays/ocp4-stage/imagestreamtag.yaml, package-update/overlays/stage/imagestreamtag.yaml
bump up package-update job to v0.8.4
With updated investigator, now it consumes topics with versions. The package-update-job is also to be updated to the same level of messaging to have packages consumed.
=> bump up package-update job to v0.8.4

adviser/base/argo-workflows/advise.yaml, adviser/base/openshift-templates/adviser.yaml
... it still feels like keeping 10,000 candidates is more than enough.
=> Decrease beam width to 10000

security-indicators/base/argo-workflows/cloc-template.yaml
https://github.com/thoth-station/thoth-application/issues/659
env for cloc package dir was not set even though it was passed causing the step to try to download the package
=> set package dir for si cloc

adviser/base/argo-workflows/advise.yaml
See https://github.com/thoth-station/adviser/issues/1575#issuecomment-735771164
=> Reduce adviser memory to 2Gi

management-api/overlays/ocp4-stage/imagestreamtag.yaml, management-api/overlays/stage/imagestreamtag.yaml
bump up management-api app version to v0.8.2
Related-to: https://github.com/thoth-station/management-api/issues/636
=> bump up management-api app version to v0.8.2

qeb-hwt-github-app/overlays/stage/kustomization.yaml
switch to ocp4 qebhwt webhook receiver from ocp
The webhook receiver are causing racing condition.
=> switch to ocp4 qebhwt webhook receiver from ocp

prow/overlays/thoth-station/config.yaml
Package module doesn't require build-check
Related-to: https://github.com/thoth-station/storages/pull/2129
=> Package module dont require build-check

kebechet/overlays/ocp4-stage/imagestreamtag.yaml
https://github.com/thoth-station/kebechet/pull/642
=> Bump kebechet to v1.2.1 in ocp4

kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Reverts thoth-station/thoth-application#698
Lets revert this back, so that we can release fixes.
=> Revert "Bump kebechet to v1.2.1 in ocp4"

core/overlays/ocp4-stage/common/configmaps.yaml
Fixes: https://github.com/thoth-station/qeb-hwt/issues/137
patch the correct url in qebhwt workflow configmap
the URL was missed while migrating.
=> patch the correct url in qebhwt workflow configmap

amun/overlays/cnv-prod/amun-api/kustomization.yaml, chat-notification/overlays/cnv-prod/kustomization.yaml, core/overlays/cnv-prod/common/kustomization.yaml, management-api/overlays/cnv-prod/kustomization.yaml, user-api/overlays/cnv-prod/kustomization.yaml
Related-To: #709 
disable enlisting of encrypted secret and routes for cnv deployment
ksops setup for operate-first argocd is in progress, till then we would disable these.
=> disable enlisting of encrypted secret and routes for cnv deployment

core/overlays/stage/common/configmaps.yaml, graph-refresh/overlays/stage/cronjob.yaml
Enable ocp stage to solve fedora solvers
With end of the year, we would like to dedicate this period for data aggregation. Allowing ocp stage to solver fedora based solvers and ocp4 would take on ubi.
=> Enable ocp stage to solve fedora solvers

graph-refresh/base/cronjob.yaml, mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Alarms are activated as Thoth is not learning for more than 30 minutes. This is because Thoth workflows are solved very fast and there are not enough workflows scheduled each hour. Let's increase them more.
=> Increase workflows

core/overlays/stage/middletier-stage/configmaps.yaml
Increase the amount of workflow to run in parallel for ocp middletier
let workflows consume all the available resource.
=> Increase the amount of workflow to run in parallel for ocp middletier

package-releases/overlays/stage/cronjob.yaml
enable package release in ocp cluster
as graph-refresh workflow are finished before the next set start, there is enough resources to accommodate package-releases as well.
=> enable package release in ocp cluster

core/overlays/ocp4-stage/common/imagestreamtags.yaml, core/overlays/stage/common/imagestreamtags.yaml
Bump version to v0.3.2. This will solve bug in Qeb-Hwt.
=> Bump workflows helpers to v0.3.2

amun/overlays/cnv-prod/amun-api/role_binding.yaml, graph-refresh/overlays/cnv-prod/rolebindings.yaml, investigator/overlays/cnv-prod/role_binding.yaml, management-api/overlays/cnv-prod/role-binding.yaml, revsolver/overlays/cnv-prod/rolebinding.yaml, user-api/overlays/cnv-prod/role-binding.yaml
```
"workflows.argoproj.io is forbidden: User \"system:serviceaccount:thoth-infra-prod:investigator\" cannot create resource \"workflows\" in API group \"argoproj.io\" in the namespace \"thoth-backend-prod\": RBAC: [clusterrole.rbac.authorization.k8s.io \"argo\" not found
```
namespace specific roles are used in cnv cluster
In the cnv cluster, we defined namespace specific roles, rather than relying upon cluster roles. 
https://github.com/thoth-station/thoth-application/blob/ab0b69fef0370c19554092aa438432e53255831a/core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml#L17
https://github.com/thoth-station/thoth-application/blob/ab0b69fef0370c19554092aa438432e53255831a/core/overlays/cnv-prod/backend-prod/argo-namespace-install. …
=> namespace specific roles are used in cnv cluster

management-api/overlays/test/imagestreamtag.yaml
=> Bump management-api to v0.9.0

user-api/overlays/test/imagestreamtag.yaml
=> Bump user-api to v0.10.0 in test environment

management-api/base/role.yaml
Fixes: #741 
updated management-api role to allow creating jobs
Allow management-api serviceaccount to be able to create jobs through openshift api call.
=> updated management-api role to allow creating jobs

grafana-dashboard/README.md, grafana-dashboard/base/kustomization.yaml, grafana-dashboard/overlays/cnv-prod/argocd.json, grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json, grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json, grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json, grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json, grafana-dashboard/overlays/cnv-prod/thoth-user-api-metrics.json, grafana-dashboard/overlays/cnv-prod/thoth-workflow-controllers-metrics.json
Fixes: #738 
store the grafana dashboard json for maintainability
we can use them directly for importing into the grafana instance, instead using local json patchs.
=> store the grafana dashboard json for maintainability

core/overlays/test/configmaps.yaml, graph-backup-job/overlays/test/cronjob.yaml, graph-backup-job/overlays/test/kustomization.yaml, kebechet/overlays/test/configmap.yaml, qeb-hwt-github-app/overlays/test/configmap.yaml
use ocp4-test deployment for test and turn on graph backup
Related-to: #745
=> use ocp4-test deployment for test and turn on graph backup

user-api/overlays/test/role-binding.yaml
Fixes: #762 
set the role binding for user-API to get pod logs
=> set the rolebinding for user-api to get pod logs

graph-backup-job/overlays/test/kustomization.yaml
fix the kustomize manifest for properly propagating cronjob
=> fix the kustomize manifest for properly propogating cronjob

core/overlays/cnv-prod/common/configmaps.yaml
use the direct service hostname for s3 connection
=> use the direct service hostname for s3 connection

core/overlays/ocp4-stage/backend-stage/argo-namespace-install.yaml, core/overlays/ocp4-stage/middletier-stage/argo-namespace-install.yaml, core/overlays/test/argo-namespace-install.yaml
upgrade argo components to v2.12.5 to tackle ttl issues
Related-to: #797 
As stated in the description of #797, the v2.12.5 has worked for other teams, we would like to use and test this. 
as the issue is happening in the openshift 4.5, starting with that cluster.
=> upgrade argo components to v2.12.5 to tackle ttl issues

sefkhet-abwy/overlays/cnv-prod/secrets.enc.yaml
re-encrypt sefkhet secrets with updates sops
Related-to: #800 
as moc argocd deploys the cnv-prod overlays, the encryption must be done along with there gpg keys.
=> re-encrypt sefkhet secrets with updates sops

prow/overlays/cnv-prod/plugins.yaml
@HumairAK @tumido @harshad16 
/sig devops
=> setting lgtm_acts_as_approve: false for all our repos

prow/base/imagestreams.yaml, prow/base/label_sync_job.yaml, prow/overlays/cnv-prod/imagestreamtags.yaml, prow/overlays/cnv-prod/kustomization.yaml, prow/overlays/cnv-prod/label-sync-cronjob.yaml, prow/overlays/cnv-prod/labels.yaml, prow/overlays/cnv-prod/plugins.yaml
add cronjob to sync all the labels, this superseds new_label_normalizer from Sefkhet-Abwy
=> add cronjob to sync all the labels

graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml, graph-backup-job/overlays/stage/imagestreamtag.yaml
Related-To: https://github.com/thoth-station/metrics-exporter/issues/529
=> Bump graph-backup-job stage to v0.8.0 to have metrics

core/overlays/ocp4-stage/common/imagestreamtags.yaml, core/overlays/stage/common/imagestreamtags.yaml
In this way we can update schema in stage! Test schema is already updated: https://grafana.datahub.redhat.com/dashboard/db/thoth-service-metrics?refresh=30s&orgId=1&var-env=ocp4-test
=> Bump workflow helpers to v0.4.1

user-api/overlays/test/deployment-trigger.yaml
use a postsync hook job for deployment trigger
https://github.com/AICoE/aicoe-cd/issues/233#issuecomment-767672303
we can test if resource hook can help us with triggering deploymentconfig.
=> use a postsync hook job for deployment trigger

graph-sync/overlays/ocp4-stage/imagestreamtag.yaml, graph-sync/overlays/stage/imagestreamtag.yaml
This is needed for Thoth S2I scenario to properly work.
=> Bump graph-sync to v0.10.0 in stage

metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml, metrics-exporter/overlays/stage/imagestreamtag.yaml
Related-To: https://github.com/thoth-station/metrics-exporter/issues/529
=> Bump metrics-exporter stage to v0.10.2

graph-sync/overlays/ocp4-stage/imagestreamtag.yaml, graph-sync/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/storages/issues/2205
=> Bump graph-sync to v0.10.1 to address solver syncing issues

kebechet/base/argo-workflows/kebechet-run-url.yaml, kebechet/base/openshift-templates/kebechet-run-url.yaml
thoth-station/kebechet#584
Add param to templates for kebechet metadata.
This should be okay to add to base because old versions of Kebechet won't be looking for it and a default value was provided so it shouldn't fail
=> add keb metadata for internal trigger context

adviser/overlays/ocp4-stage/imagestreamtag.yaml, adviser/overlays/stage/imagestreamtag.yaml
This change will bring the selective pre-releases feature to stage environments. See [docs for more info](https://thoth-station.ninja/docs/developers/adviser/experimental_features.html#selectively-enabling-pre-releases).
=> Bump adviser to v0.24.1 in stage environments

prow/overlays/cnv-prod/config.yaml
Reverts thoth-station/thoth-application#867
This pull request depended upon https://github.com/operate-first/apps/pull/217 , which isn't merged.
=> Revert "add kustomize-build presubmit job to op1st/apps repo ʕʘ̅͜ʘ̅ʔ"

prow/overlays/cnv-prod/config.yaml
https://github.com/thoth-station/integration-tests/issues/95
/hold until v0.3.1 is available at https://quay.io/repository/thoth-station/integration-tests?tag=latest&tab=tags
/sig devops
=> using latest release of integration-tests

user-api/overlays/ocp4-stage/imagestreamtag.yaml, user-api/overlays/stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/pull/1258
=> Bump User API to v0.19.0 in stage environments

integration-tests/base/configmap.yaml, integration-tests/base/cronjob.yaml, integration-tests/base/imagestream.yaml, integration-tests/base/kustomization.yaml, integration-tests/overlays/ocp4-stage/configmap.yaml, integration-tests/overlays/ocp4-stage/imagestreamtag.yaml, integration-tests/overlays/ocp4-stage/kustomization.yaml, integration-tests/overlays/ocp4-stage/put-into-infra-namespace.yaml, integration-tests/overlays/ocp4-stage/thoth-notification.yaml, integration-tests/overlays/test/configmap.yaml, integration-tests/overlays/test/imagestreamtag.yaml, integration-tests/overlays/test/kustomization.yaml, integration-tests/overlays/test/thoth-notification.yaml
Depends-On: https://github.com/thoth-station/integration-tests/pull/109
With this change, we will be able to deploy integration tests as an s2i application run as a cronjob periodically. We can run it inside any namespace in the internal network (as integration tests send email to mailing lists) to verify the application works correctly. The cronjob can be run each per deployment we want to run integration tests against.
=> Add integration tests

advise-reporter/overlays/cnv-prod/imagestreamtag.yaml, adviser/overlays/cnv-prod/imagestreamtag.yaml, core/overlays/cnv-prod/common/imagestreamtags.yaml, graph-refresh/overlays/cnv-prod/imagestreamtag.yaml, graph-sync/overlays/cnv-prod/imagestreamtag.yaml, kebechet/overlays/cnv-prod/imagestreamtag.yaml, management-api/overlays/cnv-prod/imagestreamtag.yaml, metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml, package-extract/overlays/cnv-prod/imagestreamtag.yaml, package-update/overlays/cnv-prod/imagestreamtag.yaml, user-api/overlays/cnv-prod/imagestreamtag.yaml
Bump of version for prod release 15.02.2021
This is the production release for sprint cycle 15.02.2021
With this release, we would be updating thoth-components with the following feature updates and fixes.
[x]  **Advise-reporter**
- Add metrics database(https://github.com/thoth-station/advise-reporter/pull/158)
[x]  **Adviser**
- Do not enable cut pre-releases step if selective pre-releases are allowed(https://github.com/thoth-station/adviser/pull/1657)
- Thoth's additional features can be None(https://github.com/thoth-station/adviser/pull/1660)
- Add a pipeline unit recommending Thoth's s2i as a base (https://github.com/thoth-station/adviser/pull/1635)
- Implement a pipeline unit which checks GPU and CUDA supplied …
=> Bump of version for prod release 15.02.2021

integration-tests/base/configmap.yaml, integration-tests/base/cronjob.yaml
Credits go to @harshad16, thanks for spotting this.
The environment variable is called `MAIL_REPORT`: https://github.com/thoth-station/integration-tests/blob/3e6cd68c48023d24858e46fed4caebaa7c5881bf/app.py#L32
=> Rename environment variable for sending integration test reports

adviser/overlays/test/argo-workflows/advise.yaml, adviser/overlays/test/argo-workflows/dependency-monkey.yaml, adviser/overlays/test/argo-workflows/provenance-check.yaml, adviser/overlays/test/kustomization.yaml
Related: https://github.com/thoth-station/thoth-application/pull/912
Related: https://github.com/thoth-station/thoth-application/issues/902
This PR will enable using prepared input files downloaded from Ceph in test environment.
=> Use prepared files in adviser container runs

prow/overlays/cnv-prod-test-prods/crier_rbac.yaml, prow/overlays/cnv-prod-test-prods/deck_rbac.yaml, prow/overlays/cnv-prod-test-prods/kustomization.yaml, prow/overlays/cnv-prod-test-prods/sinker_rbac.yaml
This should be deployed via a separate argocd app, target namespace: opf-ci-test-pods
It does not include any changes to Prow config, this is for a later PR
=> all the roles and rolebindungs to use the test-pods namespace

slo-reporter/overlays/cnv-prod/configmap.yaml, slo-reporter/overlays/cnv-prod/cronjob.yaml
Kustomize patch is causing a env var to be picked from two places, which shouldn't happen.
```
- name: SMTP_SERVER
valueFrom:
configMapKeyRef:
key: smtp-server
name: slo-reporter
secretKeyRef:
key: smtp-server
name: slo-reporter
```
smtp server information to be picked from configmap
=> smtp server information to be picked from configmap

integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump integration tests to v0.5.0

adviser/overlays/ocp4-stage/imagestreamtag.yaml
Depends-On: https://github.com/thoth-station/adviser/pull/1703
=> Bump adviser to v0.25.1 in stage environment

integration-tests/base/configmap.yaml, integration-tests/base/cronjob.yaml
Related: https://github.com/thoth-station/integration-tests/pull/136/
=> Enable generating report in integration-tests

integration-tests/overlays/cnv-prod-ocp4-stage/README.rst, integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml, integration-tests/overlays/cnv-prod-ocp4-stage/cronjob.yaml, integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml, integration-tests/overlays/cnv-prod-ocp4-stage/job-generate-name.yaml, integration-tests/overlays/cnv-prod-ocp4-stage/kustomization.yaml, integration-tests/overlays/cnv-prod-ocp4-stage/secret-generator.yaml, integration-tests/overlays/cnv-prod-ocp4-stage/secrets.enc.yaml, integration-tests/overlays/cnv-prod-ocp4-stage/thoth-notification.yaml
Depends-On: https://github.com/thoth-station/thoth-application/pull/944
Related: https://github.com/thoth-station/integration-tests/pull/137/
Related: https://github.com/thoth-station/thoth-application/pull/947
This pull request depends on https://github.com/thoth-station/thoth-application/pull/944. I will rebase once #944 gets in or will be adjusted.
WIth this change we will not run integration tests that require amun-inspection namespace or middletier namespace as these are occupied by workflows running in these namespaces.
=> Select only relevant integration-tests in cnv-prod

management-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/thoth-application/pull/949
=> Bump management-api to v0.14.0 in stage environment

integration-tests/base/configmap.yaml, integration-tests/base/cronjob.yaml, integration-tests/overlays/ocp4-stage/configmap.yaml
With https://github.com/thoth-station/integration-tests/pull/137/ we are able to selectively run/disable selected tests based on tags. Let's do not run integration tests that require middletier resources in stage as stage is running ingestion in thoth-middletier-stage so tests fail.
=> Do not run integration tests requiring middletier namespace

management-api/overlays/cnv-prod/imagestreamtag.yaml, management-api/overlays/prod/imagestreamtag.yaml
Related: https://github.com/thoth-station/thoth-application/pull/953
Related: #949
=> Bump management-api to v0.14.0 in prod

user-api/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump user-api to v0.19.3 in stage

adviser/overlays/cnv-prod/imagestreamtag.yaml
Bump version v0.25.1 for adviser prod
Related-to: https://github.com/thoth-station/thoth-application/issues/924
=> Bump version v0.25.1 for adviser prod

integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml
For now, we can run only integration-tests triggering workload in backend namespace. This way, only advise scenarios will be triggered (to trigger demo stacks).
=> Run integration tests that use backend namespace

integration-tests/base/cronjob.yaml
As integration tests return non-zero exit code if any scenario fails, the job keeps restarting. We can run integration tests just once.
=> Adjust restart policy for integration tests

adviser/overlays/ocp4-stage/kustomization.yaml, adviser/overlays/ocp4-stage/put-into-amun-inspection-namespace.yaml, management-api/overlays/ocp4-stage/role-binding.yaml
**Depends-On**: 
https://github.com/thoth-station/common/pull/1104
https://github.com/thoth-station/management-api/pull/695
Related-to: https://github.com/thoth-station/thoth-application/issues/629
migrate dependency monkey run in amun-inspection
moving dependency moneky execution from middletier to amun-inspection for our resource consumption needs.
=> migrate dependency monkey run in amun-inspection

user-api/base/configmap.yaml, user-api/base/deploymentconfig.yaml
Increase cache expiration on user-api for Francesco's demo. We can eventually move this to to application configmap and expose as a metric.
=> Increase cache expiration on user-api

user-api/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump user-api to v0.19.4 in stage

management-api/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump management-api to v0.15.0 in stage environment

management-api/overlays/cnv-prod/imagestreamtag.yaml
=> Bump management-api to v0.15.0 in prod environment

package-extract/base/openshift-templates/package-extract.yaml
```
when '1 == '1'' evaluated false
```
=> Fix syncing condition for package-extract

user-api/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump user-api to v0.20.2 in stage environment

user-api/overlays/cnv-prod/imagestreamtag.yaml
Related: https://github.com/thoth-station/thoth-application/pull/985
Related: https://github.com/thoth-station/thoth-application/pull/982/
=> Bump user-api to v0.20.2 in prod environment

management-api/base/role.yaml, management-api/overlays/cnv-prod/role-binding.yaml, management-api/overlays/ocp4-stage/role-binding.yaml
Enable management-api to query back logs of dependency-monkey
Related-to: https://github.com/thoth-station/management-api/issues/725
=> Enable management-api to query back logs of dependency-monkey

integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml
Reverts thoth-station/thoth-application#967
We can revert this after Francesco's demo.
=> Revert "Run integration tests that use backend namespace"

integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump integration-tests to v0.8.0 in stage environment

integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump integration-tests to v0.8.0 in prod environment

mi-scheduler/base/cronjob.yaml, mi-scheduler/overlays/cnv-prod/cronjob.yaml, mi-scheduler/overlays/ocp4-stage/cronjob.yaml, mi-scheduler/overlays/test/cronjob.yaml
Fixes https://github.com/thoth-station/mi-scheduler/issues/59
This PR adds a new cronjob specific for kebechet repositories analysis.
There should be now two standalone cronjobs, one kebechet and other general GH repo analysis
=> Add kebechet cronjob

prow/overlays/cnv-prod/config.yaml, prow/overlays/cnv-prod/imagestreamtags.yaml
Updated the image and remove required_context for optional arg
Related-to: https://github.com/thoth-station/thoth-application/issues/747
the issue seems to be here:
https://github.com/thoth-station/thoth-application/blob/75b26a11c8b2b0677df198c1c391c53ee081b7c5/prow/overlays/cnv-prod/config.yaml#L214
we have defined the `aicoe-ci/prow/kustomize-build` as a required context,
however the way it is declared to run as , only on changes of few yaml files. that mean it cant be required 
https://github.com/operate-first/apps/blob/4070832a9848898f529da0c0604cc1e1a61f9e2f/.prow.yaml#L5
Reference: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#context-policy-options
=> Updated the image and remove required_context for optional arg

.prow.yaml, prow/overlays/cnv-prod/config.yaml
manage pr checks with prow jobs
Related-to: #747
prowjobs are not required to be defined on the context_plicy of the tide, as they are default required.
Reference: https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#context-policy-options
=> manage pr checks with prow jobs

prow/overlays/cnv-prod/config.yaml
Remove branch protection for operate-first org
operate-first admins would create branch protection for individual repos if necessary.
=> Remove branch protection for operate-first org

metrics-exporter/base/deploymentconfig.yaml
```
172.22.2.1 - - [16/Mar/2021:18:56:09 +0000] "GET /metrics HTTP/1.1" 200 16048 "-" "kube-probe/1.19"
KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
File "/opt/app-root/lib64/python3.8/site-packages/thoth/messaging/admin_client.py", line 81, in check_connection
a.list_topics(timeout=timeout)
cimpl.KafkaException: KafkaError{code=_TRANSPORT,val=-195,str="Failed to get metadata: Local: Broker transport failure"}
```
=> allow metrics-exporter to check Kafka connection

management-api/overlays/cnv-prod/imagestreamtag.yaml, management-api/overlays/ocp4-stage/imagestreamtag.yaml
Bump up version for management-api v0.15.1
This one has updated storage which has a new alembic version.
=> Bump up version for management-api v0.15.1

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml, mi-scheduler/base/openshift-templates/mi-run-template.yaml
Adding missing `KNOWLEDGE_PATH` parameter specifications.
This probably caused issue of workfows not launching.
```
{"name": "thoth.common.openshift", "levelname": "WARNING", "module": "openshift", "lineno": 292, "funcname": "set_template_parameters", "created": 1616148911.1132526, "asctime": "2021-03-19 10:15:11,113", "msecs": 113.25263977050781, "relative_created": 34725.74305534363, "process": 1, "message": "Requested to assign parameter 'KNOWLEDGE_PATH' (value 'thoth-test-core/thoth-sli-metrics/kebechet-update-manager/thoth-station/source-management') to template but template does not provide the given parameter, forcing..."}
```
=> Add missing knowledge_path parameter

prow/overlays/cnv-prod/config.yaml, prow/overlays/cnv-prod/plugins.yaml
n/a
this sets up CI for Minecraft project on op1st
=> :sparkles: add the #B4mad Minecraft project

mi-scheduler/base/openshift-templates/mi-run-template.yaml
Removes unnecessary env var from `mi` openshift template.
See #1090
=> Remove mi-scheduler env from run-mi template

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml, mi-scheduler/base/cronjob.yaml, mi-scheduler/base/openshift-templates/mi-run-template.yaml
Fixes thoth-logging within `mi` and `mi-scheduler` in accordance to https://github.com/thoth-station/common#logging-setup
=> Fix logging to use THOTH_ADJUST_LOGGING

mi-scheduler/base/cronjob.yaml
parameters are not part of mi scheduler cronjob
parameters are components of openshift templates and cant be used in cronjob.
=> parameters are not part of mi scheduler cronjob

mi-scheduler/base/cronjob.yaml
The component name was invalid (https://github.com/thoth-station/mi-scheduler/blob/edbd39c0940457332e6dc95c783746947689a543/app.py#L30)
srry my mistake!
=> Fix incorrect name of mi-scheduler in logging envvar

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
Currently, the workflows are failing because of the reaching GH API rate limit, due to high number of parallel workflows.
Limit parallel workflows to only 2
=> Add max number of workflows limit

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml, mi-scheduler/base/cronjob.yaml, mi-scheduler/base/openshift-templates/mi-run-template.yaml
Other parameters can be specified to mi cli as well (e.g. boolean flags like `-t` or `-m`).
I suggest using passed string as additional configuration, so for analysis that includes basic `mi` statistics with also `kebechet` ones,  you would e.g. have:
`ADDITIONAL_CONFIGURATION="-tm"`
=> Add ADDITIONAL_CONFIGURATION to passed parameters

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml, mi-scheduler/base/openshift-templates/mi-run-template.yaml
Related to https://github.com/thoth-station/common/pull/1141#discussion_r600814175
and https://github.com/thoth-station/mi/pull/348
Kebechet inspection flag (`-t` or `--thoth`) can be now set using envvar, which is more explicit.
=> Change thoth flag to be setup with envvar

adviser/base/argo-workflows/advise.yaml, adviser/base/argo-workflows/dependency-monkey.yaml
```
File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 560, in validate_dict
raise er.DictInvalid('expected a dictionary', path)
voluptuous.error.DictInvalid: expected a dictionary
During handling of the above exception, another exception occurred:
File "/opt/app-root/src/thoth/adviser/prescription/v1/prescription.py", line 94, in validate
PRESCRIPTION_SCHEMA(prescription)
File "/opt/app-root/lib64/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__
raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: expected a …
```
=> Give full path to perscription file

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
When running `mi-analysis` workflows, I observed this error
```
Usage: cli.py [OPTIONS]
Try 'cli.py --help' for help.
Error: Invalid value for '--thoth' / '-t': ${inputs.parameters.mi_thoth} is not a valid boolean
```
Which was probably due to incorrect parameter extraction used in template.
=> Fix parameter setup from ${..} to {{..}}

prow/overlays/cnv-prod/config.yaml
enable max time for prow jobs via sinker
Related-to: https://github.com/operate-first/support/issues/159
=> enable max time for prow jobs via sinker

management-api/overlays/cnv-prod/role-binding.yaml, management-api/overlays/ocp4-stage/role-binding.yaml, user-api/overlays/cnv-prod/role-binding.yaml, user-api/overlays/ocp4-stage/role-binding.yaml
access the logs in different namespace than api
Fixes: #1126 
Use the role binding to allow API to access log of the pods in different namespace.
=> access the logs in different namespace than api

adviser/base/openshift-templates/adviser.yaml
=> Run graph-sync in advises only when authenticated

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml, mi-scheduler/base/configmaps.yaml
Related to #1115 
The `parallelism` specification was indeed incorrect, and the right way to reduce number of parallel workflows that can run is to use `semaphore`
=> Fix parallel limit to use semaphore instead of parallelism

amun/overlays/cnv-prod/amun-inspection/argo-namespace-install.yaml, amun/overlays/ocp4-stage/amun-inspection/argo-namespace-install.yaml, amun/overlays/prod/amun-inspection/argo-namespace-install.yaml, core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml, core/overlays/cnv-prod/middletier-prod/argo-namespace-install.yaml
use argo v2.12.5 in prod deployment
The argo versom v2.12.5 works well in the stage , upgrading it to the prod.
=> use argo v2.12.5 in prod deployment

prescription-sync-job/overlays/cnv-prod/cronjob.yaml, prescription-sync-job/overlays/ocp4-stage/cronjob.yaml
Related: https://github.com/thoth-station/prescriptions/pull/16/
Related: https://github.com/thoth-station/adviser/pull/1806
Let's suspend prescription-sync-job in stage and prod environments. We will move to a new schema that introduces breaking change. I will enable the cronjob once the new adviser version will be available in stage/prod environments.
=> Suspend prescription-sync-job in prod and stage

adviser/overlays/cnv-prod/imagestreamtag.yaml
bump up adviser to 0.27.0 for zero-prod
=> bump up adviser to 0.27.0 for zero-prod

core/overlays/zero-test/argo-role.yaml, core/overlays/zero-test/kustomization.yaml
set the role for argo-admin and argo for workflows
```
Forbidden: workflows.argoproj.io is forbidden: User "system:serviceaccount:thoth-test-core:argo-server" cannot list resource "workflows" in API group "argoproj.io" in the namespace "thoth-test-core": RBAC: [role.rbac.authorization.k8s.io "argo-admin" not found, role.rbac.authorization.k8s.io "argo" not found]:  Reloa
```
=> set the role for argo-admin and argo for workflows

prow/overlays/cnv-prod/config.yaml, prow/overlays/cnv-prod/secrets.enc.yaml
set prow ssh cerds for private repo support
Related-to: https://github.com/aicoe-aiops/vulnerability-analysis/pull/40
This would enable prow to use the ssh method when necessary, like serving the private repos.
=> set prow ssh cerds for private repo support

prescription-sync-job/overlays/ocp4-stage/cronjob.yaml
Requires `thoth-adviser>0.27.0` available in deployment.
=> Enable prescription sync job in stage environment

user-api/overlays/ocp4-stage/imagestreamtag.yaml
=> Bump User API to v0.24.1 in stage environment

adviser/base/argo-workflows/advise.yaml
Related: https://github.com/thoth-station/adviser/pull/1826
Related: https://github.com/thoth-station/thoth-application/issues/1182
Pass `constraints.txt` file to the adviser container. This can be safely merged, will be picked only once the adviser is bumped in the deployment (backwards compatible change).
=> Pass constraints.txt as an input to adviser

slo-reporter/overlays/zero-prod-ocp4-stage/secrets.enc.yaml
update secrets based on the zero prod cluster
Related-to: #1184 
Not needed
As the slo-reporter runs in stage cluster, talking to the prod cluster, it requires the creds of the ceph of prod.
this might also fix the related issue.
=> update secrets based on the zero prod cluster

advise-reporter/overlays/cnv-prod/imagestreamtag.yaml, advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
Bump adviser reporter to v0.7.4, using new logic to identify errors when report is missing from adviser document:
=> Bump advise-reporter-v0.7.4

kebechet/base/openshift-templates/kebechet.yaml, kebechet/overlays/test/kebechet.yaml
Fixes: https://github.com/thoth-station/investigator/issues/496
I added KEBECHET_SLUG to the OpenShift template to keep the above error from occuring. It is not currently being used in `prod` or `stage` but I added it to the base as they have a more recent version of `thoth-common` which attempts to set the template parameter.
=> add Kebechet slug to openshift templates (default null)

adviser/base/openshift-templates/adviser.yaml
When running an advise workflow without authentication being set, the kebechet-run-results task should not be executed. Even though the task has a dependency on trigger-integration, argo evaluates `when` conditional for this task which results to an error. The workflow should not be marked as failed if the advise task succeeds but the kebechet-run-results conditional is evaluated as false.
The screenshot shows failed advise task, but if the advise succeeds, the kebechet-run-results fails with the same error marking the whole workflow as failed:
=> Run kebechet-run-results only if authentication was done

user-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/pull/1407
=> Bump user-api to v0.25.0 in stage environment

adviser/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/pull/1838
=> Bump adviser to v0.29.0 in stage environment

core/overlays/cnv-prod/backend-prod/configmaps.yaml
Reduce the time to live 15 mins instead
Fixes: https://github.com/thoth-station/thoth-application/issues/1202
set archiving log true, for longer log retention without the issue of pod logs.
Reduce the time to live 15 mins instead
=> Reduce the time to live 15 mins instead

mi-scheduler/overlays/cnv-prod/imagestreamtag.yaml, mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml, mi-scheduler/overlays/test/imagestreamtag.yaml
https://github.com/thoth-station/mi/issues/399
=> Update mi-scheduler imagestream to tag v2.5.2

adviser/base/openshift-templates/adviser.yaml
quotes added to the when expression for correct value substitution
Fixes: #1232 
Related-to: https://github.com/thoth-station/integration-tests/issues/79
following the hint provided by the workflow validator :detective:
=> quotes added to the when expression for correct value substitution

adviser/base/openshift-templates/adviser.yaml
fix the quotes in advise when expression
Related-to: #1232 
```
STEP                                      TEMPLATE                                   PODNAME                                          DURATION  MESSAGE
✔ adviser-210504221704-67ab86817d55fa26  adviser                                                                                                                                                                                                              
├-✔ advise                               advise/advise                              adviser-210504221704-67ab86817d55fa26-560437830  15s                                                                                                                      
├-○ …
```
=> fix the quotes in advise when expression

core/overlays/cnv-prod/common/configmaps.yaml, core/overlays/ocp4-stage/common/configmaps.yaml, core/overlays/quicklab/configmaps.yaml, core/overlays/test/configmaps.yaml, core/overlays/zero-test/configmaps.yaml
Let's add graph namespace to configmaps to have it accessible in a deployment.
=> Add graph-namespace to configmaps

management-api/base/role.yaml, management-api/overlays/cnv-prod/kustomization.yaml, management-api/overlays/cnv-prod/role-binding.yaml
Fix accessing pod log from amun namespace by management-api
Fixes: https://github.com/thoth-station/management-api/issues/745
Rechecked on the log issue, it seems that the role was getting overridden, this would fix it.
=> Fix accessing pod log from amun namespace by management-api

user-api/base/role.yaml, user-api/overlays/cnv-prod/kustomization.yaml, user-api/overlays/cnv-prod/role-binding.yaml
Fix accessing pod log from different namespace by user-api
Fixes: https://github.com/thoth-station/user-api/issues/1413
Rechecked on the user-api pod logs accessibility issue. 
It was getting overwritten while applying on deployment time.
This separation would fix this issue.
=> Fix accessing pod log from different namespace by user-api

purge-job/base/openshift-templates/purge.yaml
Remove explicit stating the default value from purge templates
amun sync failing due this.
=> Remove explicit stating the default value from purge templates

management-api/overlays/ocp4-stage/kustomization.yaml, management-api/overlays/ocp4-stage/role-binding.yaml
Fix accessing pod log from amun namespace by management-api in stage
Related-to: #1243 
sorry, missed this in the #1243
=> Fix accessing pod log from amun namespace by management-api in stage

user-api/base/role.yaml, user-api/overlays/cnv-prod/kustomization.yaml, user-api/overlays/cnv-prod/role-binding.yaml, user-api/overlays/ocp4-stage/kustomization.yaml, user-api/overlays/ocp4-stage/role-binding.yaml
correct the role name for user-api pods log access
Related-to: #1244 
sorry, I forgot to fix this in the #1244.
=> correct the role name for user-api pods log access

advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml, advise-reporter/overlays/test/imagestreamtag.yaml, amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml, amun/overlays/ocp4-stage/amun-api/message-imagestream.yaml, amun/overlays/test/imagestreamtag.yaml, amun/overlays/test/message-imagestream.yaml, core/overlays/ocp4-stage/common/imagestreamtags.yaml, core/overlays/test/imagestreamtags.yaml, core/overlays/zero-test/imagestreamtags.yaml, graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml, management-api/overlays/test/imagestreamtag.yaml, mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml, revsolver/overlays/test/imagestreamtag.yaml, solver/overlays/ocp4-stage/imagestreamtag.yaml, user-api/overlays/ocp4-stage/imagestreamtag.yaml, user-api/overlays/test/imagestreamtag.yaml
Sync the image that was missed in the automation
This version of the image in the test and stage were missed to sync due to cluster issues, automation failure.
All these are the latest available versions.
=> Sync the image that was missed in the automation

core/overlays/cnv-prod/common/imagestreamtags.yaml, core/overlays/ocp4-stage/common/imagestreamtags.yaml, core/overlays/test/imagestreamtags.yaml, core/overlays/zero-test/imagestreamtags.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/1231
=> Bump workflow helpers to v0.8.0 to fix provenance workflow

amun/overlays/ocp4-stage/amun-api/kustomization.yaml
set the workflow template in the inspection namespace
```
invalid spec: templates.main.tasks.create-inspection-complete-message template reference create-inspection-complete-message.create-inspection-complete-message not found
```
=> set the workflow template in the inspection namespace

prow/overlays/cnv-prod/config.yaml
allow cyborg to simple merge pr instead of squash for aiops
Fixes: https://github.com/thoth-station/thoth-application/issues/1110
This would make the cyborg simply merge the pr instead of squash.
=> allow cyborg to simple merge pr instead of squash for aiops

prow/overlays/cnv-prod/config.yaml
allow cyborg to simple merge pr instead of squash for thoth-station
During scrum we spoke about having pull requests being merged by simple and not being squashed as lot of pull request in thoth-station captures multiple features.
=> allow cyborg to simple merge pr instead of squash for thoth-station

prow/add-ist, prow/base/imagestreams.yaml, prow/overlays/cnv-prod/config.yaml, prow/overlays/cnv-prod/imagestreamtags.yaml
I turned the decorator utility images into imagestreamtags, so that we can save some pull-time on each job execution
/sig devops
/kind feature
=> turn the utility images into imagestreamtags

management-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/management-api/issues/762
=> Bump management-api to v0.17.1 in stage environment

cve-update/base/cronjob.yaml
Related: https://github.com/thoth-station/cve-update-job/pull/410
=> Supply Prometheus URL to CVE update job

kebechet/base/argo-workflows/kebechet-run-url.yaml, kebechet/base/argo-workflows/kebechet.yaml
When we run Kebechet we need the whole authenticated workflow to run
=> add 'thamos_token' for user-api authentication

cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/cve-update-job/pull/412
=> Bump CVE update job to v0.3.0 in stage environment

solver/overlays/cnv-prod/imagestreamtag.yaml
Older thoth-solver releases have a bug when dependencies are not handled properly on OOM.
=> Use solver v1.9.0 in prod environment

management-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/management-api/pull/772
=> Bump management-api to v0.17.2 in stage environment

mi-scheduler/base/cronjob.yaml, mi-scheduler/overlays/cnv-prod/cronjob.yaml, mi-scheduler/overlays/ocp4-stage/cronjob.yaml, mi-scheduler/overlays/test/cronjob.yaml
Related to https://github.com/thoth-station/kebechet/issues/546#issuecomment-851455082
New merge cronjob, that aggregates all the data `mi` has collected about kebechet
=> Add merge cronjob

metrics-exporter/overlays/cnv-prod/resources_patch.yaml
Reduce the cpu limit for metrics-exporter
=> Reduce the cpu limit for metrics-exporter

adviser/base/argo-workflows/advise.yaml
Related: https://github.com/thoth-station/thoth-application/issues/1516
As discussed on the call, we can pass solvers to the adviser and let the adviser decide whether the given runtime environment has solvers enabled in the configmap. If they will not be present there, adviser can warn about the fact in a separate pipeline unit. This might be better to maintain than having two configuration entries for solvers enabled & solvers deprecated.
=> Pass configured solvers in a deployment to adviser

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
None
`mi` workflows were suspended because the one that was running waited too long for GH API limit to be reset (which is once per hour).
This PR should extend the timeout time up to one hour
=> Add increased timeout seconds

management-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/management-api/issues/777
=> Bump management-api to v0.17.3 in stage environment

slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml
```
Error: configmap "thoth" not found
```
Env variable was accidentally introduced by ??  and broke the SLO reporter that did not collect data from prod in the last week. I will retrigger it 7 days retrieval from Thanos, if available, to get data back.
=> Fix env variable breaking cronjob SLO reporter

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml, mi-scheduler/base/openshift-templates/mi-run-template.yaml
Related to #1641 
Specify `activeDeadlineSeconds` under the `analyse` step, instead in general namespace
=> Set timeoute under the step specification

triage-party/overlays/zero-prod/kustomization.yaml, triage-party/overlays/zero-prod/pcache.yaml
Deployment failed because of incorrect storage type
- [ x ] Deployment for Test and Stage `AICoE/aicoe-cd` and Prod `operate-first/argocd-apps`.
When manually deployed it failed because the storage instance was Ceph instead of noobaa.
=> deploy triage-party #1649

prescription-sync-job/overlays/cnv-prod/cronjob.yaml
Requires `thoth-adviser>0.27.0` available in deployment.
=> Enable prescription sync job in prod environment

adviser/overlays/cnv-prod/imagestreamtag.yaml, adviser/overlays/ocp4-stage/imagestreamtag.yaml
Related hotfixes:
Related: https://github.com/thoth-station/adviser/pull/1913
Related: https://github.com/thoth-station/adviser/pull/1905
=> Bump adviser to v0.33.2 in prod and stage environments

prescription-sync-job/overlays/cnv-prod/cronjob.yaml, prescription-sync-job/overlays/ocp4-stage/cronjob.yaml, prescription-sync-job/overlays/test/cronjob.yaml
Related: https://github.com/thoth-station/prescription-sync-job/pull/7
Related: https://github.com/thoth-station/adviser/issues/1908
=> Suspend prescription-sync-job in all deployments

core/overlays/cnv-prod/common/configmaps.yaml
Enable fedora34 python 3.9 data ingestion in prod
=> Enable fedora34 python 3.9 data ingestion in prod

triage-party/base/deployment.yaml
set the required env vars for triage-party
Related-to: https://github.com/thoth-station/thoth-application/issues/1649
=>  set the required env vars for triage-party

adviser/base/argo-workflows/advise.yaml
Related: https://github.com/thoth-station/thoth-application/pull/1695/
As new prescriptions with directory structure are not backwards compatible with old, single file, prescriptions, let's disable old ones. Once the transition is made, we can enable prescriptions with directory structure https://github.com/thoth-station/thoth-application/pull/1695/.
=> Disable prescriptions before adding prescriptions with dir structure

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml, metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
New metrics exporter with metric on number of CVE.
=> Bump metrics-exporter to v0.15.0

graph-sync/overlays/cnv-prod/imagestreamtag.yaml
Fixes: https://github.com/thoth-station/storages/issues/2355
=> Bump graph-sync-job to v0.10.9 in prod environment

adviser/overlays/cnv-prod/imagestreamtag.yaml, adviser/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/prescriptions/pull/31
v0.0.0 does not exist, let's start using v0.0.1 in deployments.
=> Make prescriptions v0.0.1 available in stage and prod environments

adviser/overlays/cnv-prod/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/pull/1924
Related: https://github.com/thoth-station/thoth-application/pull/1706
=> Bump adviser container to v0.34.0 in prod environment

kebechet/overlays/cnv-prod/kustomization.yaml, kebechet/overlays/ocp4-stage/kustomization.yaml
```
{"name": "__main__", "levelname": "WARNING", "module": "consumer", "lineno": 197, "funcname": "_worker", "created": 1624273232.1878748, "asctime": "2021-06-21 11:00:32,187", "msecs": 187.87479400634766, "relative_created": 114727.7638912201, "process": 1, "message": "Application misconfiguration - number of templates available in namespace 'thoth-infra-prod' is 0, should be 1: label selector: 'template=kebechet-administrator', name: None"}
```
Missing template in thoth-infra namespaces
=> Add missing template for Kebechet administrator

mi-scheduler/base/openshift-templates/mi-run-template.yaml
Related to #1723 
Repository parameter is not optional, when using `mi` for data merge action
=> Make repository parameter not required

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml, metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Related-To: https://github.com/thoth-station/metrics-exporter/issues/704
The new release is without long running queries, moved to graph-metrics-exporter component, this will avoid issues previously encountered.
=> Bump metrics-expoter to v0.16.0

adviser/base/argo-workflows/advise.yaml
fix of the volume usage in the workflow
```
time="2021-06-22T14:47:59.753Z" level=info msg="
DAG adviser-210622144758-3c1f7e02554603e-3173750276 deemed errored due to task 
adviser-210622144758-3c1f7e02554603e.advise error: volume 'prescriptions' not found in workflow spec" 
namespace=thoth-backend-prod workflow=adviser-210622144758-3c1f7e02554603e
```
volume description lives on the same indentation level as template in workflow
Reference: https://github.com/argoproj/argo-workflows/blob/master/examples/volumes-emptydir.yaml
=> fix of the volume usage in the workflow

mi-scheduler/base/cronjob.yaml
None
Cronjobs does not use the latest deployments, therefore it is now explicitly specified
=> Add latest tags to cronjobs

adviser/base/openshift-templates/adviser.yaml, package-extract/base/openshift-templates/package-extract.yaml
As we keep logs on Ceph, we can decrease TTL and cleanup pods sooner.
Related: https://github.com/thoth-station/thoth-application/issues/325
=> Decrease TTL to 300 for pods

graph-metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml, graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Metrics pushed to pushgateway have environment in labels
=> bump graph-metrics-exporter to v0.5.1

graph-refresh/overlays/cnv-prod/cronjob.yaml, package-releases/overlays/cnv-prod/cronjob.yaml, package-update/overlays/cnv-prod/cronjob.yaml
Related-to: https://github.com/thoth-station/thoth-application/issues/1766
pause the data ingestion for the storage issue
Due to the old storage module, the older sync job don't have the capability to update the dependsOn table in database.
This is to fix that in the storage and update other modules.
Till then we should pause the ingestion.
=> pause the data ingestion for the storage issue

package-extract/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/package-extract/pull/454
=> Bump package-extract to v1.2.0 in stage environment

mi-scheduler/base/cronjob.yaml
Related to https://github.com/thoth-station/mi-scheduler/pull/156
=> Add thoth deployment name envvar from thoth configmap

management-api/overlays/cnv-prod/imagestreamtag.yaml, management-api/overlays/ocp4-stage/imagestreamtag.yaml
See: https://github.com/thoth-station/thoth-application/issues/1792
=> Bump mng-api v0.17.6

mi-scheduler/overlays/zero-test/imagestreamtag.yaml
=> update mi-scheduler to the newest v1.6.1 version

prow/overlays/cnv-prod/plugins.yaml
As seen on https://github.com/operate-first/common/pull/7 sometimes it's necessary to override CI tests. This plugins helps maintainers with that.
https://prow.operate-first.cloud/command-help#override
=> feat: Enable override to bypass failing CI if necessary

prow/overlays/cnv-prod/config.yaml
Seems like Tide was not enabled in AICoE/meteor repo https://github.com/AICoE/meteor/pull/39
This is fixing it. Also switches for meteor and common repo to requiring both `lgtm` and `approved` labels.
=> feat: Enable tide on meteor and require approved on common

mi-scheduler/base/configmaps.yaml
Related to https://github.com/thoth-station/mi-scheduler/issues/155
=> Add operate-first as an organization

grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json, metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml, metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
- new metrics for kebechet users per manager
- logic to not collect metrics if schema is not update
=> Bump metric-exporter to v0.17.0

kebechet/overlays/cnv-prod/imagestreamtag.yaml
patch back the stable version 1.2.4
Related-to: https://github.com/thoth-station/kebechet/issues/774
revert the stable version
=> patch back the stable version 1.2.4

graph-refresh/base/cronjob.yaml
=> Increase liveness probe seconds on graph-refresh job

management-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/thoth-application/issues/1872
=> Bump management-api to v0.17.9 in stage

core/overlays/cnv-prod/common/imagestreamtags.yaml
This should allow scheduling adviser again. Current errors, solved in v0.14.1:
```
{"name": "__main__", "levelname": "WARNING", "module": "consumer", "lineno": 196, "funcname": "_worker", "created": 1629184645.1864533, "asctime": "2021-08-17 07:17:25,186", "msecs": 186.45334243774414, "relative_created": 1078239.2547130585, "process": 1, "message": "schedule_adviser() got an unexpected keyword argument 'github_event_type'"}
```
=> Bump investigator to v0.14.2 to fix bugs

graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/storages/pull/2420
Related: https://github.com/thoth-station/graph-sync-job/issues/610
=> Bump graph-sync to v0.10.13 in stage environment

package-releases/base/cronjob.yaml
It looks like we require more time to check all the packages that we monitor.
=> Increase package-releases deadline to 4 hours

adviser/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/pull/2049
=> Bump adviser to v0.39.0 in stage environment

solver/base/argo-workflows/solver-template.yaml, solver/base/openshift-templates/solve_and_sync-template.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/1892
Implement a new branch of the solver workflow that will retry solver with more resources when solver fails. The solver might fail due to not enough resources needed when compiling packages from the source.
Sadly Argo does not support parametrizing resources. Also, using anchors and YAML aliases just complicated things. If anyone has a better solution not to copy-paste parts of the workflow, suggestions are welcome.
=> Branch workflow with more resources if solver fails

prow/overlays/cnv-prod/config.yaml
SSIA
Changing this because of dependabot usage.
=> feat: Add exclude branches for branchprotect on Meteor repo

graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml, graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
Related-To: https://github.com/thoth-station/graph-backup-job/issues/180
=> bump graph-backup to v0.8.7 to fix issue

package-releases/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/package-releases-job/issues/589
=> Bump package-releases-job to v0.11.0 in stage environment

integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml, integration-tests/overlays/ocp4-stage/imagestreamtag.yaml, integration-tests/overlays/test/imagestreamtag.yaml
Related: https://github.com/thoth-station/integration-tests/pull/214
See https://quay.io/repository/thoth-station/integration-tests?tab=tags
=> Bump integration-tests to v0.8.5 in all the environments

adviser/overlays/cnv-prod/imagestreamtag.yaml, core/overlays/zero-test/imagestreamtags.yaml, graph-refresh/overlays/cnv-prod/imagestreamtag.yaml, graph-sync/overlays/cnv-prod/imagestreamtag.yaml, package-releases/overlays/cnv-prod/imagestreamtag.yaml
Bump up the images based on the version update v2021.08.30
Related-to: https://github.com/thoth-station/thoth-application/issues/1882
=> Bump up the images based on the version update v2021.08.30

adviser/base/argo-workflows/kebechet-run-results.yaml, adviser/base/openshift-templates/adviser.yaml
This config was missing from kebechet run results making Kebechet authenticate using OAuth rather than GitHub app authentication
=> use GitHub app authentication present in secrets

cve-update/overlays/ocp4-stage/cronjob.yaml
Let's enable CVE update job so we sync CVEs and solve stacks affected by CVEs.
=> Enable CVE update job in stage

core/overlays/ocp4-stage/common/configmaps.yaml
Related: https://github.com/thoth-station/thoth-application/issues/1764
It looks like UBI 8 + Python 3.8 finished ingesting. Let's enable ingesting Fedora:34 + Python 3.9 data.
=> Enable ingesting Fedora:34+Python 3.9 data in stage environment

prow/overlays/smaug/config.yaml
When updating prescriptions, some branches are turned into protected. This is not excepted behavior as these branches should be deleted.
=> Exclude branches created for prescription updates

cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/cve-update-job/pull/424
=> Update cve-update job to v0.4.0 in stage environment

adviser/base/argo-workflows/advise.yaml, adviser/base/argo-workflows/dependency-monkey.yaml, adviser/base/imagestream.yaml, adviser/overlays/cnv-prod/imagestreamtag.yaml, adviser/overlays/ocp4-stage/imagestreamtag.yaml, adviser/overlays/test/imagestreamtag.yaml
Fixes: https://github.com/thoth-station/prescriptions/issues/50
=> Start using prescriptions from pickle file

kebechet/overlays/cnv-prod/imagestreamtag.yaml, kebechet/overlays/ocp4-stage/imagestreamtag.yaml
This main reason for this is to alleviate users receiving issues on their repositories on Kebechet failure
=> update Keb to latest minor version

graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml, graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml, graph-backup-job/overlays/test/imagestreamtag.yaml
Bump up the graph-backup-job to version v0.8.9
This would resolve the failing backup.
=> Bump up the graph-backup-job to version v0.8.9

metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/metrics-exporter/issues/773
=> Bump metrics-exporter to v0.18.3 in stage environment

package-releases/overlays/ocp4-stage/imagestreamtag.yaml
This patch will allow package release to identify correct versions from Pytorch indexes
=> Bump package-release in stage to v0.11.3

prow/overlays/smaug/config.yaml
setup prow on the data-driven-development repo
ci not functioning on that repo
=> setup prow on the data-driven-development repo

triage-party/base/deployment.yaml, triage-party/overlays/moc/config.yaml, triage-party/overlays/moc/pcache.yaml
#1969
No
A small update to the triage-party configuration, to:
- Add the tutorial repos
- Remove explicit storage class from PVC (suggested by operate first sre), should use the default
- Fix typo in volume name
=> Update triage-party configuration

package-releases/overlays/ocp4-stage/imagestreamtag.yaml, package-releases/overlays/test/imagestreamtag.yaml
we should be able to analyze package versions correctly from torch indexes.
=> Bump package release to v0.11.4 in test and stage

adviser/overlays/ocp4-stage/kustomization.yaml, chat-notification/overlays/ocp4-stage/kustomization.yaml, chat-notification/overlays/test/kustomization.yaml, cve-update/overlays/aws-prod/kustomization.yaml, cve-update/overlays/moc-prod/kustomization.yaml, cve-update/overlays/ocp4-stage/kustomization.yaml, cve-update/overlays/test/kustomization.yaml, graph-refresh/overlays/test/kustomization.yaml, package-releases/overlays/ocp4-stage/kustomization.yaml, package-releases/overlays/test/kustomization.yaml, pulp-pypi-sync-job/overlays/test/kustomization.yaml, solver-project-url-job/overlays/test/kustomization.yaml
Don't declare namespace value explicitly in kustomize file
Fixes: #2008
=> Don't declare namespace value explicitly in kustomize file

core/overlays/aws-prod/infra-prod/kustomization.yaml, core/overlays/aws-prod/infra-prod/service-monitor.yaml
Addresses part of [issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
- [_4/5_] create service monitor for each namespace corresponding components
Deploys this service monitor in the same way as [pr 2038](https://github.com/thoth-station/thoth-application/pull/2038/) but for balrog.
This PR adds enables our service label for metrics from thoth-infra-prod to have a new field label with the path/route of the corresponding service as the value through a service monitor deployed to balrog.
=> Infra-prod service-monitor creates field label on balrog

core/overlays/aws-prod/backend-prod/kustomization.yaml, core/overlays/aws-prod/backend-prod/service-monitor.yaml
Addresses part of [issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
- [_2/5_] create service monitor for each namespace corresponding components
Deploys this service monitor in the same way as [pr 2045](https://github.com/thoth-station/thoth-application/pull/2045/) but for balrog.
Also alphabetized the resources in the overlay.
This PR adds enables our service label for metrics from thoth-backend-prod to have a new field label with the path/route of the corresponding service as the value through a service monitor deployed to balrog.
=> Backend service-monitor creates field label on balrog

core/overlays/aws-prod/graph-prod/kustomization.yaml, core/overlays/aws-prod/graph-prod/service-monitor.yaml
Addresses part of [issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
- [_1/5_] create service monitor for each namespace corresponding components
Deploys this service monitor in the same way as [pr 2046](https://github.com/thoth-station/thoth-application/pull/2046/) but for balrog.
This PR adds enables our service label for metrics from thoth-graph-prod to have a new field label with the path/route of the corresponding service as the value through a service monitor deployed to balrog.
=> Graph service-monitor creates field label on balrog

core/overlays/aws-prod/frontend-prod/kustomization.yaml, core/overlays/aws-prod/frontend-prod/service-monitor.yaml
Addresses part of [issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
- [_3/5_] create service monitor for each namespace corresponding components
Deploys this service monitor in the same way as [pr 2043](https://github.com/thoth-station/thoth-application/pull/2043/) but for balrog.
This PR adds enables our service label for metrics from thoth-frontend-prod to have a new field label with the path/route of the corresponding service as the value through a service monitor deployed to balrog.
=> Frontend service-monitor creates field label on balrog

core/overlays/aws-prod/middletier-prod/kustomization.yaml, core/overlays/aws-prod/middletier-prod/service-monitor.yaml
Addresses [issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
- [_5/5_] create service monitor for each namespace corresponding components
Deploys this service monitor in the same way as [pr 2044](https://github.com/thoth-station/thoth-application/pull/2044/) but for balrog.
Dependencies / related PRs:
- [Frontend service Monitor](https://github.com/thoth-station/thoth-application/pull/2105)
- [Backend service Monitor](https://github.com/thoth-station/thoth-application/pull/2104)
- [Graph service Monitor](https://github.com/thoth-station/thoth-application/pull/2103)
- [Infra service Monitor](https://github.com/thoth-station/thoth-application/pull/2108)
Also alphabetized resources.
This PR adds enables our service label for metrics from thoth-middletier-prod to …
=> Middletier service-monitor creates field label on balrog

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml, prescriptions-refresh-job/base/configmap.yaml, prescriptions-refresh-job/base/kustomization.yaml
Related: https://github.com/thoth-station/prescriptions-refresh-job/pull/37
The new implementation provides a way to configure which container images should be monitored and checked for security by Quay security scanners.
=> Make monitored container images by prescriptions-refresh configurable

grafana-dashboard/overlays/aws-prod/argocd.json, grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-service-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json, grafana-dashboard/overlays/aws-prod/thoth-user-api-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-workflow-controllers-metrics.json
Partial fix of: [issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
applies grafana smaug changes:
- update the data source to openshift-monitoring in the thoth-dashboard
- update all grafana dashboards with the change of instance -> field
- update environment from zero to balrog
similar to [PR 2097](https://github.com/thoth-station/thoth-application/pull/2097) but for balrog instead of Smaug.
Don't think so but not sure
=> applying overlays for grafana dashboards to balrog

kebechet/base/argo-workflows/kebechet-run-url.yaml, kebechet/base/argo-workflows/kebechet.yaml, kebechet/base/openshift-templates/kebechet-run-url.yaml, kebechet/base/openshift-templates/kebechet.yaml
https://github.com/thoth-station/kebechet/pull/880
https://github.com/thoth-station/support/issues/73
No space left on device when cloning large repositories such as prescriptions.
This change does not break anything, but needs a new version of Kebechet to take advantage of the empty directory
=> use emptyDir for cloning git repo

grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
[Origional issue](https://github.com/thoth-station/thoth-application/issues/2029)
modifying the [recent pr for the field update](https://github.com/thoth-station/thoth-application/pull/2097/)
updating datsource name in dashboard to match the smaug datasources definition updated in [operate-first/apps pull 1271](https://github.com/operate-first/apps/pull/1271/files#diff-6bf4d5d6548dd07ee15e2f0df300d5dde1ccbcdb437196b00ae2a66353286ca9R44)
no new deployment required
In the last PR, I named the datasource smaug-openshift-monitoring, however in the definition of the datasource itself, it was deployed as aws-balrog-monitoring, so I am opening a new PR to rectify this.
=> updating name of datasource in dashboards

grafana-dashboard/overlays/aws-prod/argocd.json, grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json, grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
Addresses part 2 of [thoth-station/thoth-application issue 2029](https://github.com/thoth-station/thoth-application/issues/2029#issuecomment-961310030)
no
Removing the Thoth jobs from the dashboards as they can't be picked up by grafana due to lack of access.
=> Remove job field from the grafana dashbaord

cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/thoth-application/issues/2091
Related: https://github.com/thoth-station/cve-update-job/issues/441
Related: https://github.com/thoth-station/cve-update-job/pull/442
=> Bump cve-update to v0.5.0 in stage environment

graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
Related: https://github.com/thoth-station/graph-sync-job/issues/623
=> Bump graph-sync to v0.10.16 in stage

management-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/management-api/issues/836
=> Bump management-api to v0.17.14 in stage

metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/thoth-application/issues/2091
=> Bump metrics-exporter to v0.19.0 in stage environment

init-job/overlays/test/imagestreamtag.yaml
Related: https://github.com/thoth-station/init-job/issues/433
=> Bump init-job to v0.8.1 in stage

prow/overlays/smaug/config.yaml
=> chore: add aicoe/seraph to tide

prow/overlays/smaug/kustomization.yaml, prow/overlays/smaug/service-monitor.yaml
Addresses [issue 374](https://github.com/operate-first/support/issues/374). The service monitor should enable Grafana to access the metrics on its own.
no
Add a service monitor which scrapes the opf-ci-prow namespace and exposes those metics.
=> service monitor to expose prow metrics to smaug grafana

grafana-dashboard/overlays/moc-prod/argocd.json, grafana-dashboard/overlays/moc-prod/thoth-knowledge-graph-content-metrics.json, grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
Addresses [Thoth grafana dashboards do not show any data](https://github.com/thoth-station/thoth-application/issues/2140)
Similar to [thoth-station/thoth-application pull 2118](https://github.com/thoth-station/thoth-application/pull/2118) but for smaug dashboards.
no
Removing the non-existent jobs from smaug dashboards so that metrics can reach grafana.
=> removing jobs from smaug dashboards

kebechet/overlays/aws-prod/imagestreamtag.yaml, kebechet/overlays/moc-prod/imagestreamtag.yaml, kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Bump up the kebechet version to v1.6.4
Related-to: https://github.com/thoth-station/solver-error-classfier/issues/10
=> Bump up the kebechet version to v1.6.4

kebechet/overlays/aws-prod/imagestreamtag.yaml, kebechet/overlays/moc-prod/imagestreamtag.yaml, kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Bump up the kebechet version to v1.6.6
Related-to: https://github.com/thoth-station/kebechet/issues/917
=> Bump up the kebechet version to v1.6.6

mi-scheduler/overlays/test/imagestreamtag.yaml
Related to https://github.com/thoth-station/mi/issues/496
=> Update mi to v2.10.1

kebechet/overlays/aws-prod/imagestreamtag.yaml, kebechet/overlays/moc-prod/imagestreamtag.yaml, kebechet/overlays/ocp4-stage/imagestreamtag.yaml
Bump kebechet to version v1.6.7 for the tag issue fix
Related-to: https://github.com/thoth-station/kebechet/issues/921
=> Bump kebechet to version v1.6.7 for the tag issue fix

prow/overlays/smaug/config.yaml
For an example of a PR that is not merging see https://github.com/AICoE/donkeycar/pull/4
No
Enable prow (tide) to merge PRs in the [AICoE/donkeycar](https://github.com/AICoE/donkeycar) repository
=> Enable prow/tide for the aicoe/donkeycar repo

adviser/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/2195
=> Bump adviser to v0.48.0 in stage environment

mi-scheduler/overlays/test/imagestreamtag.yaml
https://github.com/thoth-station/mi-scheduler/issues/200
=> Update mi-scheduler to v1.7.2

user-api/overlays/moc-prod/kustomization.yaml
Disable khemenu route from the moc prod as being used on balrog
As the khemenu is being used in the balrog cluster, it causes unnecessary pods on the moc smaug cluster.
=> Disable khemenu route from the moc prod as being used on balrog

core/overlays/moc-prod/backend-prod/configmaps.yaml, core/overlays/moc-prod/middletier-prod/configmaps.yaml
Update the correct ceph host url for argo workflow controller
Related-to: https://github.com/thoth-station/thoth-application/issues/2149
As the URL was wrong, the argo event used to fail and didn't log the metrics correctly
=> Update the correct ceph host url for argo workflow controller

core/overlays/moc-prod/frontend-prod/service-monitor.yaml
Addresses [orrigional issue](https://github.com/thoth-station/thoth-application/issues/2160)
Allows fix in [thoth-application 2186](https://github.com/thoth-station/thoth-application/pull/2186)
Removing double apps from the service monitor, to change the route from which the metric is being scraped.
=> fixing field label with double apps

README.md
Documentation of changes for [Thoth station issue 2029](https://github.com/thoth-station/thoth-application/issues/2029).
Adding documentation to the current configuration of monitoring in thoth-station, as well as describing how to extend it.
=> adding documentation of Thoth-alerting

prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
Related: https://github.com/thoth-station/prescriptions-refresh-job/issues/91
=> Bump prescriptions-refresh-job to v0.5.0 in moc

adviser/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/adviser/issues/2218
=> Bump adviser to v0.49.0 in stage environment

user-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/pull/1535
=> Bump user-api to v0.29.1 in stage

package-extract/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/package-extract/pull/463
=> Bump package-extract to v1.3.0 in stage environment

core/overlays/moc-prod/graph-prod/postgresql.yaml
Patch the smaug cluster postgresql pvc to default ceph based storage
ceph based pvc storages are default in smaug cluster
=> Patch the smaug cluster postgresql pvc to default ceph based storage

graph-backup-job/overlays/moc-prod/cronjob.yaml
Freeze the db dump of smaug cluster
Smaug cluster deployment is a copy of the prod.
Taking db dump seems to be redundant.
Freezing it.
=> Freeze the db dump of smaug cluster

cve-update/overlays/aws-prod/cronjob.yaml, graph-backup-job/overlays/aws-prod/cronjob.yaml, graph-refresh/overlays/aws-prod/cronjob.yaml, package-update/overlays/aws-prod/cronjob.yaml
Freeze the data ingestion on balrog prod cluster
Related-to: https://github.com/thoth-station/thoth-application/issues/2172
As discussed in the Tech Talk the data ingestion would be carried out on stage.
So freezing the ingestion in prod
along with making the db dump of prod weekly.
=> Freeze the data ingestion on balrog prod cluster

monitoring/overlays/aws-prod/alerting-rules.yaml, monitoring/overlays/aws-prod/kustomization.yaml, monitoring/overlays/aws-prod/secret-generator.yaml, monitoring/overlays/aws-prod/secrets.enc.yaml
Partially addresses [Setup Prometheus and Grafana service for collecting the Services Metrics](https://github.com/thoth-station/thoth-application/issues/2029)
- specifically balrog --> alerts --> [x] setup the alerts rules for the openshift-monitoring alertmanager to pick up.
- no new deployment required
- Created alerting rules to use balrog routes and metrics
- Updated patch in kustomization to apply the aws/balrog for env
- moved over secret / secret generator
=> setting up balrog alerting-rules

graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
Related: https://github.com/thoth-station/graph-sync-job/issues/634
=> Bump graph-sync-job to v0.10.18 in stage environment

prow/overlays/smaug/plugins.yaml
An example of a `/transfer` request (currently not working because the plugin is not enabled): https://github.com/thoth-station/kebechet/issues/942#issuecomment-998797918
This is to enable the [transfer-issue hook plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/transfer-issue) in prow so that org members can ask prow to move issues across repos within the org
=> Enable the transfer-issue prow plugin

package-extract/base/argo-workflows/package-extract.yaml
Some container images take way too long to be analyzed and exceed limit configured.
=> Increase number of seconds allowed package-extract to run

package-extract/base/argo-workflows/package-extract.yaml
Some container image analyses fail on OOM. Increase allocated memory for package-extract.
=> Increase memory requirements for package-extract

nepthys/base/cronjob.yaml
Include investigator required env vars for the doc builds
Related-to: https://github.com/thoth-station/nepthys/issues/80#issuecomment-1000429871
The investigators require some of the env vars.
https://github.com/thoth-station/investigator/blob/b6ca87a07ae38b6d8529a227fa4d7ab48c26f399/thoth/investigator/configuration.py#L52
https://github.com/thoth-station/investigator/blob/b6ca87a07ae38b6d8529a227fa4d7ab48c26f399/thoth/investigator/configuration.py#L53
https://github.com/thoth-station/investigator/blob/b6ca87a07ae38b6d8529a227fa4d7ab48c26f399/thoth/investigator/configuration.py#L55
=> Include investigator required env vars for the doc builds

core/overlays/ocp4-stage/common/imagestreamtags.yaml, cve-update/overlays/ocp4-stage/imagestreamtag.yaml, graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml, graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml, graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml, metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml, package-releases/overlays/ocp4-stage/imagestreamtag.yaml, package-releases/overlays/test/imagestreamtag.yaml
Bump up the images based on the storgae v0.62.1 update
This is to fix the alerts.
=> Bump up the images based on the storgae v0.62.1 update

core/overlays/moc-prod/backend-prod/configmaps.yaml, core/overlays/moc-prod/middletier-prod/configmaps.yaml
Disable insecure agro artifact submission
```
time="2022-01-10T16:30:06.512Z" level=info msg="Saving from /tmp/argo/outputs/logs/main.log to s3 (endpoint: s3-openshift-storage.apps.smaug.na.operate-first.cloud, bucket: thoth, key: data/smaug-prod/argo/artifacts/kebechet-job-220110162705-933ea1c42443f860/kebechet-job-220110162705-933ea1c42443f860-3370468600/main.log)"
time="2022-01-10T16:30:06.519Z" level=warning msg="Failed to put file: 503 Service Unavailable"
time="2022-01-10T16:30:06.519Z" level=error msg="executor error: timed out waiting for the condition"
```
Just hunch, that the endpoint insecure true is causing is the issue.
=> Disable insecure agro artifact submission

prow/overlays/smaug/config.yaml
Remove the required context as the presubmit are not run always
Related-to: https://github.com/open-services-group/community/pull/6#issuecomment-1010086775
=> Remove the required context as the presubmit are not run always

amun/overlays/aws-prod/amun-api/kustomization.yaml, amun/overlays/moc-prod/amun-api/kustomization.yaml, amun/overlays/ocp4-stage/amun-api/kustomization.yaml, amun/overlays/test/kustomization.yaml
Introduce image patch for the amun deploymentconfig
Related-to: https://github.com/thoth-station/thoth-application/issues/1996
The patch of deploymentconfig was missing.
=> Introduce image patch for the amun deploymentconfig

metrics-exporter/overlays/aws-prod/imagestreamtag.yaml, metrics-exporter/overlays/moc-prod/imagestreamtag.yaml, metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
We inotruduced a new metric for Kebechet that is required in the dashboard.
=> Bump metrics-exporter to v0.20.0 for Kebechet monitoring dashboard

amun/base/deploymentconfig.yaml, amun/overlays/aws-prod/amun-api/configmaps.yaml, amun/overlays/moc-prod/amun-api/configmaps.yaml, amun/overlays/ocp4-stage/amun-api/configmaps.yaml, amun/overlays/test/configmaps.yaml
Moved the logging-no-json env var to amun cm
The amun deployment was missing the logging-no-json env var, moved it to amun configmap
=> Moved the logging-no-json env var to amun cm

triage-party/overlays/moc/config.yaml
This adds a new collection to [triage-party](https://triage-party.thoth-station.ninja) to help find issues in an inconsistent state:
- issues that have `lifecycle/active` but no assingee
- issues that have `lifecycle/active` but have not been updated for 2+ weeks (presumably not being active)
It also adds a rule in the receive queue to highlight `priority/critical-urgent` issues that have not yet been taken.
=> Add a triage-party view to highlight inconsistencies

triage-party/overlays/moc/config.yaml
This is to add the following additional boxes to triage-party:
- inconsistencies: help+important, inconsistent triage
- queue information: what's active, what's next
Also adding the helm-charts repo
=> Update triage-party configuration with more views

prow/overlays/smaug/plugins.yaml
Turn off auto reviewers in operate-first
Operate-first team doesn't want to have auto reviewers in the github org.
=> Turn off auto reviewers in operate-first

document-sync-job/base/cronjob.yaml, document-sync-job/base/imagestream.yaml, document-sync-job/base/kustomization.yaml, document-sync-job/base/secret-generator.yaml, document-sync-job/base/secrets.enc.yaml, document-sync-job/overlays/ocp4-stage/cronjob.yaml, document-sync-job/overlays/ocp4-stage/imagestreamtag.yaml, document-sync-job/overlays/ocp4-stage/kustomization.yaml, document-sync-job/overlays/ocp4-stage/thoth-notification.yaml, document-sync-job/overlays/test/cronjob.yaml, document-sync-job/overlays/test/imagestreamtag.yaml, document-sync-job/overlays/test/kustomization.yaml, document-sync-job/overlays/test/thoth-notification.yaml
Set up document sync job for the thoth-station
Successfully ran 1st alpha test.
[example-g2p7h-document-sync-job.log](https://github.com/thoth-station/thoth-application/files/7954154/example-g2p7h-document-sync-job.log)
This is sync ceph doc from the stage(ingestion) to prod(AWS)
=> Set up document sync job for the thoth-station

buildlog-parser/base/argo-workflows/buildlog-parser.yaml, buildlog-parser/overlays/moc-prod/kustomization.yaml, buildlog-parser/overlays/ocp4-stage/kustomization.yaml, buildlog-parser/overlays/test/kustomization.yaml
patch the buildlog parser image
Related-to: https://github.com/thoth-station/integration-tests/issues/225
=> patch the buildlog parser image

grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json
The dashboard was not showing data because `/` was missin in the field variable
`postgres-metrics-exporter-thoth-graph-prod.apps.balrog.aws.operate-first.cloud/` and not `postgres-metrics-exporter-thoth-graph-prod.apps.balrog.aws.operate-first.cloud`
verified from : https://thanos-querier-openshift-monitoring.apps.balrog.aws.operate-first.cloud/graph?g0.expr=pg_settings_vacuum_cost_page_hit%7Bfield%3D%22postgres-metrics-exporter-thoth-graph-prod.apps.balrog.aws.operate-first.cloud%2F%22%7D&g0.tab=1&g0.stacked=0&g0.range_input=1h&g0.max_source_resolution=0s&g0.deduplicate=1&g0.partial_response=0&g0.store_matches=%5B%5D
=> Fix postgresql grafana dashboard fieldlabel

pulp-pypi-sync-job/overlays/test/imagestreamtag.yaml
Related to [issue 33](https://github.com/thoth-station/pulp-pypi-sync-job/issues/33). 
Upping the tag of the Pulp-PYPI-sync-job in the `test` overlay to use the fix included in [Issue 33](https://github.com/thoth-station/pulp-pypi-sync-job/issues/33) stated above.
=> update pulp-pypi-sync-job image tag

document-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/document-sync-job/pull/11
=> Bump document-sync-job to v0.2.0 in stage environment

document-sync-job/base/cronjob.yaml
We have a lot of documents to sync, so let's increase the sync deadline and see how much time actually takes.
=> Increase document-sync deadline to 12 hours

document-sync-job/base/cronjob.yaml
Fixes warning produced by urllib3:
```
2022-02-04 15:30:13,351   1 WARNING  urllib3.connectionpool:305: Connection pool is full, discarding connection: s3.upshift.redhat.com. Connection pool size: 10
```
=> Adjust sync concurrency based on urllib3 connection pool configured

pulp-pypi-sync-job/base/cronjob.yaml
Checking the pod logs, we log JSON even if deployment is configured not to do so.
=> Respect JSON logging configuration

pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/pulp-pypi-sync-job/issues/37
=> Bump pulp-pypi-sync-job to v0.1.1 in stage

document-sync-job/base/cronjob.yaml
Related: https://github.com/thoth-station/thoth-application/pull/2323
The inial document sync failed on timeout. Let's increase the deadline (now 3 days) and trigger the sync again. We can make optimize the sync with https://github.com/thoth-station/thoth-application/pull/2323 once the initial sync is done.
=> Increase document sync to 3 days

document-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/document-sync-job/issues/16
Related: https://github.com/thoth-station/thoth-application/pull/2323
=> Bump document-sync to v0.3.0 in stage environment

document-sync-job/base/cronjob.yaml
It looks like more memory is needed to sync some of the docs.
=> Increase memory for document-sync-job

document-sync-job/base/cronjob.yaml
Related: https://github.com/thoth-station/document-sync-job/pull/21/
Related: https://github.com/thoth-station/document-sync-job/issues/20
Related: https://github.com/thoth-station/storages/pull/2586
Let's supply solvers that are configured in the deployment to make sure only these are properly synced to prod. Eventually with date filter applied.
=> Supply configured solvers for document-sync to sync solvers

amun/base/deploymentconfig.yaml, build-watcher/base/deploymentconfig.yaml, investigator/base/deploymentconfig.yaml, investigator_message_metrics/base/deploymentconfig.yaml, management-api/base/deploymentconfig.yaml, metrics-exporter/base/deploymentconfig.yaml, pulp-metrics-exporter/base/deploymentconfig.yaml, sefkhet-abwy-chatbot/base/deploymentconfig.yaml, sefkhet-abwy/base/deploymentconfig.yaml, user-api/base/deploymentconfig.yaml
See https://github.com/thoth-station/user-api/issues/1645#issuecomment-1031857876
It looks like the base image no longer uses 8080 by default. Let's supply `PORT` environment variable to all deployment configs we have to make sure all web servers use 8080 without any regressions.
=> Provide port configuration to all deployment configs

cve-update/overlays/aws-prod/cronjob.yaml, cve-update/overlays/moc-prod/cronjob.yaml
Let's enable cve-update job in prod deployments so that users get fresh CVE information. Otherwise we report a warning that the database has not been updated for quite some time:
```
https://thoth-station.ninja/j/cve_timestamp                                      │ CVE database of known vulnerabilities for Python packages was updated at '2022-01-12T00:06:25.489150'                                 │ ⚠️ WARNING  
```
=> Enable CVE update job in prod deployments

solver/base/openshift-templates/solve_and_sync-template.yaml, solver/overlays/test/argo-workflows/solver-template.yaml
Related: https://github.com/thoth-station/solver/issues/5111
Related: https://github.com/thoth-station/graph-refresh-job/issues/669
Related: https://github.com/thoth-station/thoth-application/issues/2272
Allow passing new environment variable for solvers, which would check indexes for possible dependencies (cross-index resolution).
=> Allow passing indexes where package dependencies should be looked up

graph-metrics-exporter/base/cronjob.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/2346
=> Add missing env variables for graph-metrics-exporter

core/overlays/aws-prod/common/secrets.enc.yaml, core/overlays/moc-prod/common/secrets.enc.yaml
Attach thanos querier secrets for metrics read
Fixes: https://github.com/thoth-station/thoth-application/issues/2304
These secrets are required for application to read metrics from the source.
=> :guardsman: Attach thanos querier secrets for metrics read

triage-party/overlays/moc/config.yaml
No
This adds rules to triage-party to show a list of issues that have `priority/backlog` or `priority/awaiting-more-evidence` so that they can be periodically reviewed.
Also restrict the `needs-triage` list to issues without a `triage/foo` label. This should not happen, but unfortunately it still does, and it clutters the view. The conflicting ones can be seen in the "inconsistencies" tab
=> Add a view for backlog refining to triage-party

amun/overlays/aws-prod/amun-api/configmaps.yaml, amun/overlays/moc-prod/amun-api/configmaps.yaml, core/overlays/aws-prod/common/configmaps.yaml
patch the prometheus url towards thanos querier
Related-to: https://github.com/thoth-station/thoth-application/issues/2357
The metrics-exporter was failing as it was looking for Prometheus instead of Thanos.
=> :fire: patch the prometheus url towards thanos querier

graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml, graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml, graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
patch due to: https://github.com/thoth-station/graph-metrics-exporter/pull/73
image already available on quay: https://quay.io/repository/thoth-station/graph-metrics-exporter?tab=tags
=> Bump graph metrics exporter to v0.6.1

triage-party/overlays/moc/config.yaml
Fixes #2363 
No
Move out two rules from the daily collection:
- The check for missing kind/ to the inconsistencies view
- Integrate issue-needs-priority into the weekly issue-needs-triage
=> triage-party: simplify the daily collection

amun/overlays/aws-prod/amun-api/imagestreamtag.yaml, amun/overlays/moc-prod/amun-api/imagestreamtag.yaml, amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Bump up the amun-api image to v0.10.1
Related-to: https://github.com/thoth-station/amun-api/issues/641
PR is in response of getting back amun-api in working condition. 
This is test and is successfully working
=> :ship: Bump up the amun-api image to v0.10.1

integration-tests/base/cronjob.yaml
Integration tests fail on liveness probe as they take more time to execute now.
=> Increase deadline for integration-tests

metrics-exporter/overlays/aws-prod/imagestreamtag.yaml, metrics-exporter/overlays/moc-prod/imagestreamtag.yaml, metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml, user-api/overlays/aws-prod/imagestreamtag.yaml, user-api/overlays/moc-prod/imagestreamtag.yaml, user-api/overlays/ocp4-stage/imagestreamtag.yaml
Bump up the images based on the version update v2022.02.28
Related-to: https://github.com/thoth-station/thoth-application/issues/2368
=> :ship: Bump up the images based on the version update v2022.02.28

adviser/base/argo-workflows/advise.yaml
Let's tweak the memory optimizer to make sure no OOMs are happening. We might interate on this configuration multiple times based on integration-tests results.
=> Adjust adviser's memory optimizer configuration

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml, prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml, prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml, prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml, prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
Avoid OOM. We can further reduce memory allocation based on metrics.
=> Increase memory for prescriptions-refresh jobs to 1Gi to avoid OOM

user-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/user-api/pull/1694
=> Bump user-api to v0.34.9 in stage environment

adviser/base/argo-workflows/advise.yaml
It looks like we have still some memory available to fill. Activate the memory optimization later.
=> Adjust adviser's memory optimizer limit

prow/README.md
Fixes https://github.com/thoth-station/support/issues/151
Following the discussion in the issue, document where to find which container images Prow uses when running tests on a repo.
=> Document where to find container images used by Prow

user-api/overlays/aws-prod/imagestreamtag.yaml, user-api/overlays/moc-prod/imagestreamtag.yaml, user-api/overlays/ocp4-stage/imagestreamtag.yaml
Bump up user-api v0.34.10 to fix current openapi issue
Related-to: https://github.com/thoth-station/user-api/issues/1696
Already tested this in test cluster
=> Bump up user-api v0.34.10 to fix current openapi issue

adviser/overlays/aws-prod/advise-resources-patch.yaml
Reduce CPU allocated per adviser run. Adviser uses 2 processes, one is CPU expensive, the other one is not that CPU expensive. 2.5 CPU look too much to allocate per an adviser run.
=> Reduce CPU used by adviser on AWS prod

prow/overlays/smaug/plugins.yaml
Fixes: #2359 
Related: https://github.com/thoth-station/core/pull/386
Make the list of repos for which the requires_matching_label plugin manages the `needs-triage` label match the [label configuration in the thot-station github org](https://github.com/thoth-station/core/blob/d1e76927ec9f46c668bd58999d55e16baa91641c/community/labels.yaml#L448).
=> [prow] remove some repos from needs-triage label management

adviser/base/argo-workflows/dependency-monkey.yaml, adviser/base/argo-workflows/kebechet-run-results.yaml, adviser/overlays/aws-prod/kustomization.yaml, adviser/overlays/moc-prod/kustomization.yaml, adviser/overlays/ocp4-stage/kustomization.yaml, adviser/overlays/test/kustomization.yaml
Fix the image patching of dm
Related-to: https://github.com/thoth-station/integration-tests/issues/253#issuecomment-1061019264
As dependency monkey should run in `amun-inspection` namespace, the image is also to be patched in that namespace.
=> Fix the image patching of dm

amun/base/openshift-templates/inspection-workflow.yaml
Do not send messages after Amun inspections. We have this part of integration off.
=> Do not send message by default after Amun inspections

adviser/overlays/aws-prod/imagestreamtag.yaml, adviser/overlays/moc-prod/imagestreamtag.yaml
Let's eventually bump adviser in prod to check the impact on the integration-test results.
=> Bump adviser to v0.52.2 in prod environment

adviser/overlays/aws-prod/imagestreamtag.yaml, adviser/overlays/moc-prod/imagestreamtag.yaml, adviser/overlays/ocp4-stage/imagestreamtag.yaml, adviser/overlays/test/imagestreamtag.yaml
/hold until container image is delivered to https://quay.io/repository/thoth-station/adviser?tab=tags
=> bump adviser to v0.52.3 in all environments

amun/base/openshift-templates/inspection-workflow.yaml
Reverts thoth-station/thoth-application#2418
The default behavior is encoded in sources:
https://github.com/thoth-station/common/blob/5c7452c5140a0105acfa6260ffa244d84c1f7431/thoth/common/openshift.py#L867-L869
We should make this configurable in templates https://github.com/thoth-station/common/pull/1231
As this change has no effect in the deployment, reverting. Let's fix sending messages step.
=> Revert "Do not send message by default after Amun inspections"

user-api/overlays/ocp4-stage/imagestreamtag.yaml
/hold
... until available https://quay.io/repository/thoth-station/user-api?tab=tags
=> Bump user-api to v0.34.11 in stage

amun/base/argo-workflows/inspection-build-with-cpu.yaml, amun/base/argo-workflows/inspection-build.yaml
Patch the amun await step with retry strategy
```
I0309 07:12:38.726905 29 request.go:621] Throttling request took 1.085638392s, request: GET:https://172.30.0.1:443/apis/operator.openshift.io/v1?timeout=32s Error from server (NotFound): builds.build.openshift.io "inspection-test-220309071204-344cac0bf58615ea-1" not found
```
The retry strategy is helping with the build get action, so it can adapt to the wait time of the build pod getting spun up. 
```
STEP                                                                                                        TEMPLATE                        PODNAME                                                   DURATION  MESSAGE
✔ inspection-test-220309080548-5117c47448386fbf …
```
=> Patch the amun await step with retry strategy

user-api/overlays/ocp4-stage/imagestreamtag.yaml
Related to https://github.com/thoth-station/user-api/pull/1714
Container image available at https://quay.io/repository/thoth-station/user-api?tab=tags&tag=0.34.12
=> Bump user-api to v0.34.12 in stage

graph-refresh/base/cronjob.yaml
Run graph-refresh every 40 mins, instead of every hour
oE/aicoe-cd` and Prod `operate-first/argocd-apps`.
The workload is getting resolved by every 40 mins, and the metrics are alerting we have compute power unused.
so making the graph-refresh job run for every 40 mins in stage cluster.
=> Run graph-refresh every 40 mins, instead of every hour

advise-reporter/overlays/aws-prod/imagestreamtag.yaml, advise-reporter/overlays/moc-prod/imagestreamtag.yaml, advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml, adviser/overlays/aws-prod/imagestreamtag.yaml, adviser/overlays/moc-prod/imagestreamtag.yaml, package-releases/overlays/aws-prod/imagestreamtag.yaml, package-releases/overlays/moc-prod/imagestreamtag.yaml, solver/overlays/aws-prod/imagestreamtag.yaml, solver/overlays/moc-prod/imagestreamtag.yaml, user-api/overlays/aws-prod/imagestreamtag.yaml, user-api/overlays/moc-prod/imagestreamtag.yaml
Bump up the images based on the version update v2022.03.14
Related-to: https://github.com/thoth-station/thoth-application/issues/2393
Sprint release updates.
=> :ship: Bump up the images based on the version update v2022.03.14

user-api/overlays/aws-prod/imagestreamtag.yaml, user-api/overlays/moc-prod/imagestreamtag.yaml
The built image is available: https://quay.io/repository/thoth-station/user-api?tab=tags
=> Bump user-api to v0.34.13 in prod

prow/overlays/smaug/plugins.yaml
This adds configuration for the prow [projectmanager plugin](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/projectmanager).
The configuration is meant to manage automatic addition of issues to GitHub projects based on their labels.
Configuration is included for the 4 projects matching our current [SIGs](https://github.com/thoth-station/core/blob/master/community/sig-list.md). For example, an issue labeled with `sig/devsecops` would get automatically added to the *New* column of the [SIG-DevSecOps project](https://github.com/orgs/thoth-station/projects/16).
For reference, sample configuration for that plugin can be seen in [the documented plugins.yaml config](https://github.com/kubernetes/test-infra/blob/853555e6b2bc3052fb863fef12be5c1521f8d36a/prow/plugins/plugin-config …
=> [prow] Add configuration for the projectmanager prow plugin

solver/base/imagestreams.yaml, solver/overlays/test/imagestreamtag.yaml
Addresses: https://github.com/thoth-station/s2i-thoth/issues/231
Related to: https://github.com/thoth-station/s2i-thoth/pull/235
Depends on: https://github.com/thoth-station/solver/pull/5151
Adding an ImageStream resource to the solver test overlay `imagestream.yaml` to stream the new fedora35-py310 solver image coming in [solver pull 5151](https://github.com/thoth-station/solver/pull/5151).
=> adding thoth solver f35-py310 image to imagestream in test overlay

integration-tests/overlays/aws-prod-ocp4-stage/README.rst, integration-tests/overlays/aws-prod-ocp4-stage/configmap.yaml, integration-tests/overlays/aws-prod-ocp4-stage/cronjob.yaml, integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml, integration-tests/overlays/aws-prod-ocp4-stage/kustomization.yaml, integration-tests/overlays/aws-prod-ocp4-stage/secret-generator.yaml, integration-tests/overlays/aws-prod-ocp4-stage/secrets.enc.yaml, integration-tests/overlays/aws-prod-ocp4-stage/thoth-notification.yaml
Partially addresses: https://github.com/thoth-station/thoth-application/issues/2451
This will create a new overlay for aws-prod-ocp4-stage for the thoth-integration tests.
/cc @harshad16 
/cc @mayaCostantini
=> creating aws-prod-ocp4-stage overlay for thoth-integration tests

prow/overlays/smaug/plugins.yaml
The [Kebechet GitHub project](https://github.com/orgs/thoth-station/projects/3) is not actively maintained according to recent feedback.
On the other hand, the [SIG User Experience project](https://github.com/orgs/thoth-station/projects/40) is ramping up.
This PR updates the prow plugin configuration for the `project` plugin to remove Kebechet and add SIG-User-Experience.
=> [prow] project map: SIG User Experience instead of Kebechet

amun/base/deploymentconfig.yaml
Downgrade amun api CPU limit for usability
The Amun API is not used as the same as user-API , the CPU limit of the whole 1 core is not needed.
=> Downgrade amun api cpu limit for usability

amun/base/deploymentconfig.yaml
Drop web concurrency for amun-api
Related-to: #2464 
As we dropped the number of cores being used, dropping the web concurrency to be under limits.
=> Drop web concurrency for amun-api

mi-scheduler/base/configmaps.yaml, mi-scheduler/base/cronjob.yaml
set mi-scheduler-cm configmap for mi-scheduler cronjob
we need this separation as the config map mi-scheduler lives in another namespace as thoth-common reads it and is used in workflows, so we need this as separate as it is directly being used in cronjob. 
https://github.com/thoth-station/thoth-application/blob/426358d5f6fad745e35a99ab74ee6cbf7067b2b6/mi-scheduler/base/cronjob.yaml#L63
https://github.com/thoth-station/thoth-application/blob/426358d5f6fad745e35a99ab74ee6cbf7067b2b6/mi-scheduler/overlays/moc-prod/kustomization.yaml#L24
=> set mi-scheduler-cm configmap for mi-scheduler cronjob

amun/overlays/aws-prod/amun-inspection/kustomization.yaml, amun/overlays/moc-prod/amun-inspection/kustomization.yaml, amun/overlays/ocp4-stage/amun-inspection/kustomization.yaml
Keep DM up-to-date which uses adviser image
Dependency monkey uses adviser image, as we only apply adviser image in thoth-backend.
This is way to keep the adviser image up-to-date in thoth-amun-inspection namespace , where DM runs.
=> Keep DM up-to-date which uses adviser image

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
Related to https://github.com/thoth-station/prescriptions-refresh-job/issues/130
Depends on https://github.com/thoth-station/prescriptions-refresh-job/pull/144
Exit `prescriptions-refresh-job` `gh-*` containers properly when the GitHub API request quota is reached for the token in use.
=> Exit prescriptions-refresh-gh containers when too many requests to GitHub API

amun/overlays/aws-prod/amun-api/argo-workflows/sync-template.yaml, amun/overlays/aws-prod/amun-api/kustomization.yaml, amun/overlays/aws-prod/amun-inspection/kustomization.yaml, amun/overlays/moc-prod/amun-api/argo-workflows/sync-template.yaml, amun/overlays/moc-prod/amun-api/kustomization.yaml, amun/overlays/moc-prod/amun-inspection/kustomization.yaml, amun/overlays/ocp4-stage/amun-api/argo-workflows/sync-template.yaml, amun/overlays/ocp4-stage/amun-api/kustomization.yaml, amun/overlays/ocp4-stage/amun-inspection/kustomization.yaml
Keep DM sync up-to-date which uses graph-sync image
=> Keep DM sync up-to-date which uses graph-sync image

amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml
Container image is available at [quay.io/thoth-station/amun-api:v0.10.3](https://quay.io/repository/thoth-station/amun-api?tab=tags&tag=latest)
=> Bump Amun API to v0.10.3 in stage

management-api/overlays/ocp4-stage/imagestreamtag.yaml
Related: https://github.com/thoth-station/management-api/issues/879
=> Bump management-api to v0.18.3 in stage

integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
Related to https://github.com/thoth-station/integration-tests/issues/313
/hold
Waiting for container image to be available at https://quay.io/repository/thoth-station/integration-tests?tab=tags
=> Bump integration tests to v0.11.2 in stage

core/overlays/aws-prod/backend-prod/configmaps.yaml, core/overlays/ocp4-stage/backend-stage/configmaps.yaml
Increase the parallel wf run limit and reduce ttl in stage for backend
Related-to: https://github.com/thoth-station/integration-tests/issues/309
https://github.com/thoth-station/investigator/issues/637
As we have available resources, lets check with increase wf parallel execution limits.
=> Increase the parallel wf run limit and reduce ttl in stage for backend

prow/overlays/smaug/plugins.yaml
The current sprint's milestone is [2022.05.09](https://github.com/thoth-station/thoth-application/milestone/29).
This PR fixes a typo in the prow milestone plugin configuration to match it.
=> [prow] Fix typo in current milestone configuration

integration-tests/README.md
Partially addresses: https://github.com/thoth-station/thoth-application/issues/2451
Related to: https://github.com/thoth-station/thoth-application/pull/2458
=> adding documentation on creating new integration test overlays

core/overlays/aws-prod/common/configmaps.yaml, core/overlays/moc-prod/common/configmaps.yaml, core/overlays/ocp4-stage/common/configmaps.yaml, core/overlays/test/configmaps.yaml, solver/overlays/aws-prod/imagestreamtag.yaml, solver/overlays/moc-prod/imagestreamtag.yaml, solver/overlays/ocp4-stage/imagestreamtag.yaml, solver/overlays/test/imagestreamtag.yaml
Start the sync of the fedora35 python 3.10 solvers
Fixes: https://github.com/thoth-station/thoth-application/issues/2479
Related-to: https://github.com/thoth-station/s2i-thoth/issues/231
start the solver execution for the f35-py3.10 based solvers.
=> Start the sync of the fedora35 python 3.10 solvers

prow/overlays/smaug/config.yaml
Tide is skipping contexts not defined by Prow config (enabled in settings). Turn this off for Peribolos as a service repo.
=> feat(prow): OSG Peribolos needs Tide stop skipping checks

prow/overlays/smaug/config.yaml
Release workflow is being blocked by mandatory pre-commit context on push to master. Disabling this branch protect rule for now.
=> feat: Disable branch protection on peribolos repo

prow/overlays/smaug/plugins.yaml
Initially this is meant to be used by the OSG repos, see https://github.com/open-services-group/community/pull/179
This adds an additional label `epic` to be managed by prow's label plugin, so that anyone can comment on issues:
``` text
/label epic
/remove-label epic
```
without requiring write permissions in the target repository.
=> [prow] Add an additional 'epic' label

sync-job/base/cron-workflow.yaml, sync-job/base/kustomization.yaml, sync-job/base/workflow-template.yaml, sync-job/overlays/common/imagestreamtag.yaml, sync-job/overlays/common/kustomization.yaml, sync-job/overlays/prod-to-stage/kustomization.yaml, sync-job/overlays/stage-to-prod/kustomization.yaml
Partially Addresses: https://github.com/thoth-station/thoth-application/issues/2513
Related to: https://github.com/thoth-station/sync-job/pull/61
Creating a cron-workflow for the sync-job
/cc @harshad16
=> creating cron-workflow to invoke job template for the sync-job

sync-job/base/workflow-template.yaml, sync-job/base/workflow.yaml
Remake of https://github.com/thoth-station/sync-job/pull/67
Addresses Part 3 of https://github.com/thoth-station/management-api/issues/887
Related to:
- https://github.com/thoth-station/management-api/pull/884/files
- https://github.com/thoth-station/common/pull/1260
Creating an Argo workflow that invokes an argo workflow template. Additionally openshift resources (job-template) have been moved to the openshift folder to match documentation and better organize the repo.
The sync job should be implemented as an argo workflow and workflow template so that it can be invoked by the management api with the `_schedule_workflow` function, and be more flexible in how we run it.
=> adding argo workflow and modifying template

solver/base/argo-workflows/solver-template.yaml
Related to https://github.com/thoth-station/thoth-application/issues/2569
Increase the `activeDeadlineSeconds` in the solver workflow used when first workflow fails due to not enough resources allocated.
=> Increase `activeDeadlineSeconds` in backup solver workflow

kafka/base/thoth-kafka.yaml
Updated the kafka to version 3.1.0
Related-to: https://github.com/thoth-station/thoth-application/issues/2566
Update required as the operator was updated to 2.1.0 amq streams
Already updated in cluster and working.
=> Updated the kafka to version 3.1.0

user-api/base/role.yaml
I gave user-api its own rule, removing it from the rule with
configmap permissions. I then duplicated the permissions that were
already present, and added "create" and "update" verbs to the rule.
closes: https://github.com/thoth-station/thoth-application/issues/2556
=> add create, and update permissions for secret resources 4 user-api

prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
Built image is available at https://quay.io/repository/thoth-station/prescriptions-refresh-job?tab=tags&tag=v0.7.1
=> Bump prescriptions-refresh-job to v0.7.1 in stage

adviser/overlays/ocp4-stage/imagestreamtag.yaml
Built image is available at https://quay.io/repository/thoth-station/adviser?tab=tags&tag=v0.56.0
=> Bump adviser to v0.56.0 in stage

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml, prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
- Temporarily disable the prescriptions-refresh-job handler responsible for updating scorecards as it consumes too many resources
- Schedule this cronjob to be run monthly instead of weekly
=> Suspend scorecards handler and schedule refresh job monthly

prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
Temporarily disable prescriptions because of an important increase in BigQuery API costs for some handlers.
=> Temporarily suspend prescriptions

management-api/overlays/ocp4-stage/imagestreamtag.yaml
/hold
Until container image is available
=> Bump management-api to v0.18.5 in stage

adviser/base/argo-workflows/kebechet-run-results.yaml
Include the thoth-advise-metadata env to the kebechet-run-result
Related-to: https://github.com/thoth-station/ps-nlp/issues/151#issuecomment-1179137642
=> Include the thoth-advise-metadata env to the kebechet-run-result

adviser/overlays/aws-prod/imagestreamtag.yaml, adviser/overlays/moc-prod/imagestreamtag.yaml, adviser/overlays/ocp4-stage/imagestreamtag.yaml, core/overlays/aws-prod/common/imagestreamtags.yaml, core/overlays/moc-prod/common/imagestreamtags.yaml, core/overlays/ocp4-stage/common/imagestreamtags.yaml, core/overlays/rick-test/imagestreamtags.yaml, integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml, integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml, integration-tests/overlays/ocp4-stage/imagestreamtag.yaml, prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
Bump up version of the updated component in release v2022.08.01
Related-to: https://github.com/thoth-station/thoth-application/issues/2598
=> :ship: Bump up version of the updated component in release v2022.08.01

user-api/base/configmap.yaml
It had been set to 12 hours in the configmap. 
The default value when this environment variable is not present for user api is 3 hours, but we can leave it as 4 hours here if needed.
=> Fix cache expiration value

investigator/base/deploymentconfig.yaml, investigator/overlays/aws-prod/deploymentconfig.yaml, investigator/overlays/moc-prod/deploymentconfig.yaml, investigator/overlays/ocp4-stage/deploymentconfig.yaml, investigator/overlays/test/deploymentconfig.yaml
Update the timeout for readinessprobe
This would fix the current argocd sync failure
=> :ant: Update the timeout for readinessprobe

triage-party/overlays/moc/config.yaml
This is to add a rule in the weekly triage view of triage-party to show any issues that do not yet have a SIG label.
=> Add a rule to triage-party to highlight issues without a SIG

adviser/base/argo-workflows/advise.yaml, adviser/base/argo-workflows/dependency-monkey.yaml, adviser/base/argo-workflows/provenance-check.yaml, buildlog-parser/base/argo-workflows/buildlog-parser.yaml, core/overlays/aws-prod/backend-prod/configmaps.yaml, core/overlays/aws-prod/middletier-prod/configmaps.yaml, core/overlays/ocp4-stage/backend-stage/configmaps.yaml, core/overlays/ocp4-stage/middletier-stage/configmaps.yaml, core/overlays/test/configmaps.yaml, package-extract/base/argo-workflows/package-extract.yaml, revsolver/base/argo-workflows/revsolver-template.yaml, security-indicators/base/argo-workflows/aggregator-template.yaml, security-indicators/base/argo-workflows/bandit-template.yaml, security-indicators/base/argo-workflows/cloc-template.yaml, solver/base/argo-workflows/solver-template.yaml, solver/overlays/test/argo-workflows/solver-template.yaml
switch insecure false for the agro-worflows
- Removed insecure flag from worklfows
Fixes: #2642 
- The argo-workflow artifact overrides the workflow-controller configuration. 
so we have removed the insecure bit from workflow and are going to rely on the workflow controller configuration.
=> :fire: switch insecure false for the agro-worflows

core/base/kustomization.yaml, core/base/send-webhooks-sa.yaml
add role which will be used for adviser workflows so that secrets created for callback urls can be deleted
closes: #2557
=> add new role and role binding for adviser

kebechet/overlays/aws-prod/imagestreamtag.yaml, kebechet/overlays/moc-prod/imagestreamtag.yaml, kebechet/overlays/ocp4-stage/imagestreamtag.yaml, prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml, user-api/overlays/aws-prod/imagestreamtag.yaml, user-api/overlays/moc-prod/imagestreamtag.yaml, user-api/overlays/ocp4-stage/imagestreamtag.yaml
Bump up version of the updated component in release v2022.09.12
Related-to: https://github.com/thoth-station/thoth-application/issues/2628
=> :ship: Bump up version of the updated component in release v2022.09.12

graph-backup-job/base/cronjob.yaml, graph-backup-job/overlays/aws-prod/kustomization.yaml, graph-backup-job/overlays/aws-prod/pvc.yaml, graph-backup-job/overlays/moc-prod/pvc.yaml, graph-backup-job/overlays/ocp4-stage/kustomization.yaml, graph-backup-job/overlays/ocp4-stage/pvc.yaml
Use pvc volume for graph-backup-job
Related-to: https://github.com/thoth-station/graph-backup-job/issues/242
=> Use pvc volume for graph-backup-job

mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
Related to https://github.com/thoth-station/mi-scheduler/issues/249
=> Update mi to 2.12.0 and mi-scheduler to 1.7.7

mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml, mi-scheduler/overlays/test/imagestreamtag.yaml
Related to https://github.com/thoth-station/mi-scheduler/issues/249
SSIA
=> Update mi-scheduler to 1.7.8

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml
Related to https://github.com/thoth-station/core/issues/440
Revert to a weekly computation of Scorecard prescriptions to aggregate info on each project revision. However, this implies an increase in cost for BigQuery we might want to consider, so we could also adapt the cron schedule to be run bi-weekly or keep it monthly.
cc @goern
=> Revert to weekly scorecard prescriptions

mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml, mi-scheduler/overlays/test/imagestreamtag.yaml
Related to https://github.com/thoth-station/mi-scheduler/issues/249
SSIA
=> Update mi-scheduler to 1.7.9

sefkhet-abwy-chatbot/overlays/moc/imagestreamtag.yaml, sefkhet-abwy/overlays/moc/imagestreamtag.yaml, sefkhet-abwy/overlays/ocp/imagestreamtag.yaml
Upgrade sefkhet-abwy image version to [v0.23.2](https://github.com/AICoE/sefkhet-abwy/pull/211).
=> Upgrade sefkhet-abwy image version to v0.23.2

amun/overlays/ocp4-stage/common/configmaps.yaml, build-watcher/overlays/amun-api/configmap.yaml, build-watcher/overlays/test/configmap.yaml, core/overlays/ocp4-stage/common/configmaps.yaml, core/overlays/ocp4-stage/common/secrets.enc.yaml, core/overlays/quicklab/configmaps.yaml, core/overlays/test/configmaps.yaml, core/overlays/test/secrets.enc.yaml, slo-reporter/overlays/ocp4-stage/configmap.yaml, slo-reporter/overlays/ocp4-stage/secrets.enc.yaml, slo-reporter/overlays/test/configmap.yaml, slo-reporter/overlays/test/secrets.enc.yaml
Use the new monitoring deployment in thoth-station component
Related-to: https://github.com/thoth-station/thoth-application/issues/2455
- Switch the thoth-station monitoring deployment in place of datahub deployment.
=> :package: Use the new monitoring deployment in thoth-station component

core/overlays/moc-prod/common/imagestreamtags.yaml, core/overlays/ocp4-stage/common/imagestreamtags.yaml
Upgrade workflow helper image version to v0.9.15
Required-for: #2702
=> Upgrade workflow helper image version to v0.9.15

adviser/base/openshift-templates/adviser.yaml, core/base/argo-management.yaml, core/base/kustomization.yaml, core/base/send-webhooks-sa.yaml, core/overlays/ocp4-stage/backend-stage/argo-management.yaml, core/overlays/test/argo-management.yaml
if no requests have been made with callback secret combine, then no secret will exist, by making the secret optional the volume that is mounted will be empty and still allow the step to run
Signed-off-by: Kevin <kpostlet@redhat.com>
fixes: #2677
=> make callback secret optional

pulp-pypi-sync-job/overlays/ocp4-stage/cronjob.yaml
Disable pulp index sync job for temporary fix
Related-to: #2711
=> Disable pulp index sync job for temporary fix

management-api/overlays/moc-prod/imagestreamtag.yaml
Upgrade management-api in prod to get storage v0.73.6 changes
Related-to: https://github.com/thoth-station/storages/issues/2732
=> Upgrade management-api in prod to get storage v0.73.6 changes

cve-update/overlays/moc-prod/imagestreamtag.yaml, cve-update/overlays/ocp4-stage/imagestreamtag.yaml
Bump up version of the updated component in release v2022.12.05
Fixes: https://github.com/thoth-station/thoth-application/issues/2700
=> :ship: Bump up version of the updated component in release v2022.12.05

CHANGELOG.md, version.py
Release of version 2022.12.05
Related-to: https://github.com/thoth-station/thoth-application/issues/2716
=> :ship: Release of version 2022.12.05

prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
Currently open PRs in the prescriptions repository
This is to temporarily stop the prescription refresh jobs.
While looking at the last execution of the job and the generated PRs I found out that current prescriptions seem to fail validation.
Pausing the job (meant to execute later today) until we clarify this.
=> Suspend prescription refresh execution

graph-refresh/overlays/ocp4-stage/cronjob.yaml
Resume graph-refresh-job for data ingestion
Fixes: #2720 
The unresolved message queue in kafka is now stable.
Resuming the graph-refresh-job would enable the functionality of populating the message queue again.
=> :play_or_pause_button: Resume graph-refresh-job for data ingestion

graph-sync/base/argo-workflows/sync-template.yaml, graph-sync/base/openshift-templates/syncJob-template.yaml
Remove unused env var in graph-sync job
Related-to: https://github.com/thoth-station/graph-sync-job/pull/678
=> :face_in_clouds: Remove unused env var in graph-sync job

adviser/base/openshift-templates/adviser.yaml
the unresolved package messages being created are ill formed and there is not a clear path to fixing this
Signed-off-by: Kevin <kpostlet@redhat.com>
thoth-station/workflow-helpers#329
=> temporarily disable message sending after adviser is complete

advise-reporter/overlays/moc-prod/cronjob.yaml, cve-update/overlays/moc-prod/cronjob.yaml, integration-tests/overlays/moc-prod-ocp4-stage/cronjob.yaml, mi-scheduler/overlays/moc-prod/cronjob.yaml, slo-reporter/overlays/moc-prod-ocp4-stage/cronjob.yaml
:sleeping: Hibernate the data-ingestion jobs on smaug cluster
As part of hibernation, only data-ingestion components in smaug
smaug would be used mainly for data services only.
=> :sleeping: Hibernate the data-ingestion jobs on smaug cluster

graph-backup-job/base/cronjob.yaml, graph-metrics-exporter/base/cronjob.yaml, graph-refresh/base/cronjob.yaml, integration-tests/base/cronjob.yaml
:sleeping: Slow down the daily jobs to monthly on-stage cluster
- slow down the daily jobs to monthly 
- push back graph-refresh-job to hourly
=> :sleeping: Slow down the daily jobs to monthly on stage cluster

core/overlays/ocp4-stage/graph-stage/postgresql.yaml
Upgrade DB pvc as it filled up
The DB pods are in `crashlooping` stage, as the PVC is filled up and not connecting.
This would increase the size of the PVC and fix the pod.
=> Upgrade DB pvc as it filled up

grafana-dashboard/ocp4-stage/thoth-kafka-argo-metrics.json, grafana-dashboard/ocp4-stage/thoth-knowledge-graph-content-metrics.json, grafana-dashboard/ocp4-stage/thoth-postgresql-metrics.json, grafana-dashboard/ocp4-stage/thoth-report.json, grafana-dashboard/ocp4-stage/thoth-service-metrics.json, grafana-dashboard/ocp4-stage/thoth-service-user-api.json, grafana-dashboard/ocp4-stage/thoth-sli-slo.json, grafana-dashboard/ocp4-stage/thoth-workflow-controller.json
Persist the grafana dashboard for stage cluster
Related-to: https://github.com/thoth-station/thoth-application/issues/2455
The grafana dashboard has already been uploaded to the grafana.
This is to persist the dashboard for the long term.
=> :chart_with_downwards_trend: Persist the grafana dashboard for stage cluster
