thoth-station/thoth-application

integration-tests/base/cronjob.yaml

Handle restarts of integration-tests

---

integration-tests/base/cronjob.yaml

Fixes: https://github.com/thoth-station/thoth-application/issues/1000

Fix restart policy for integration-tests

---

integration-tests/base/cronjob.yaml

state backofflimit inside jobtemplate for cronjob
Related-to: #1000

state backofflimit inside jobtemplate for cronjob

---

adviser/base/openshift-templates/dependency-monkey.yaml
adviser/overlays/cnv-prod/kustomization.yaml
adviser/overlays/cnv-prod/put-into-amun-inspection-namespace.yaml

Execute dependency monkey in amun-inspection namespace for thoth
Related-to: https://github.com/thoth-station/management-api/issues/725

Execute dependency monkey in amun-inspection namespace for thoth

---

amun/overlays/ocp4-stage/amun-api/openshift-templates/inspection-workflow.yaml

closes: https://github.com/thoth-station/thoth-application/issues/869

remove todo which was already fixed

---

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
mi-scheduler/base/openshift-templates/mi-run-template.yaml

https://github.com/thoth-station/mi-scheduler/issues/76#issuecomment-784871942

Add knowledge path to parameters

---

adviser/base/openshift-templates/dependency-monkey.yaml

Fixes: https://github.com/thoth-station/thoth-application/issues/1011

Schedule graph-sync for dependency monkey only if not dry run

---

solver/overlays/test/argo-workflows/solver-template.yaml
solver/overlays/test/kustomization.yaml

debug the new-solver with s2i based images in test
Related-to: https://github.com/thoth-station/thoth-application/pull/809

debug the new-solver with s2i based images in test

---

amun/base/deploymentconfig.yaml
management-api/base/deploymentconfig.yaml

Related: https://github.com/thoth-station/thoth-application/pull/992
Let's see if the linked issue fixes the problem.

Adjust web concurrency for management-api and amun-api

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/issues/1722

Bump adviser to v0.26.0 in stage

---

graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
graph-backup-job/overlays/test/thoth-notification.yaml

Bump version v0.8.1 for graph-backup-job

Bump version v0.8.1 for graph-backup-job

---

kebechet/base/argo-workflows/update_keb_installation.yaml
kebechet/base/kustomization.yaml
kebechet/overlays/test/kebechet.yaml
kebechet/overlays/test/kustomization.yaml

Depends on: https://github.com/thoth-station/workflow-helpers/pull/223
add new workflow helpers tasks for updating kebechet installation at the beginning kebechet workflow in test

add new workflow helper to update kebechet installation details

---

prow/overlays/cnv-prod/labels_thoth-station.yaml
prow/overlays/cnv-prod/plugins.yaml

from our Tech Talk discussion
a `kind/demo` label for Issue or PR someone want to give a demo or request a demo.

:sparkles: add a kind/demo label

---

graph-refresh/overlays/ocp4-stage/cronjob.yaml

switch back on graph-refresh in the stage

switch back on graph-refresh in the stage

---

solver/overlays/test/argo-workflows/solver-template.yaml

Execute solvers with app script
**Depends-On**: https://github.com/thoth-station/solver/pull/678

Execute solvers with app script

---

sefkhet-abwy/overlays/cnv-prod/imagestreamtag.yaml
sefkhet-abwy/overlays/ocp/imagestreamtag.yaml

Bump version v0.21.1 for sefkhet-abwy

Bump version v0.21.1 for sefkhet-abwy

---

package-extract/base/argo-workflows/package-extract.yaml
package-extract/base/openshift-templates/build-analysis.yaml

Related-To: https://github.com/thoth-station/metrics-exporter/issues/581
Add metrics for build-analysis/package-extract directly using Argo workflows metrics

Add build analysis metrics

---

graph-refresh/overlays/cnv-prod/cronjob.yaml
package-releases/overlays/cnv-prod/cronjob.yaml
package-update/overlays/cnv-prod/cronjob.yaml

suspend data ingestion in prod till upgrade

suspend data ingestion in prod till upgrade

---

mi-scheduler/base/cronjob.yaml

Fixes kebechet scheduling of `mi-scheduler`
Environment variables added to cronjob for `storages`

Add graph database envs

---

mi-scheduler/base/cronjob.yaml

This fixes prev PR #1034 by adding missing parameter

Add host variable

---

prow/overlays/cnv-prod/config.yaml

https://github.com/thoth-station/thamos/pull/790

update CI/CD configuration

---

prow/base/statusreconciler.yaml
prow/base/tide.yaml

Updated ceph bucket for statusreconciler and tide
Related-to #1039

Updated ceph bucket for statusreconciler and tide

---

amun/overlays/cnv-prod/amun-api/configmaps.yaml
amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
core/overlays/cnv-prod/backend-prod/configmaps.yaml
core/overlays/cnv-prod/common/configmaps.yaml
core/overlays/cnv-prod/graph-prod/ceph-storage.yaml
core/overlays/cnv-prod/infra-prod/prometheus-config.yaml
core/overlays/cnv-prod/infra-prod/secrets.enc.yaml
core/overlays/cnv-prod/middletier-prod/configmaps.yaml
grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
grafana-dashboard/overlays/cnv-prod/thoth-postgresql-metrics.json
grafana-dashboard/overlays/cnv-prod/thoth-service-metrics.json
grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json
grafana-dashboard/overlays/cnv-prod/thoth-user-api-metrics.json
grafana-dashboard/overlays/cnv-prod/thoth-workflow-controllers-metrics.json
integration-tests/overlays/cnv-prod-ocp4-stage/README.rst
integration-tests/overlays/cnv-prod-ocp4-stage/configmap.yaml
kebechet/overlays/cnv-prod/configmap.yaml
prow/add-ist
prow/overlays/cnv-prod/config.yaml
qeb-hwt-github-app/overlays/cnv-prod/configmap.yaml
sefkhet-abwy/overlays/cnv-prod/configmap.yaml
slo-reporter/overlays/cnv-prod/configmap.yaml

component migration from cnv-moc to zero-moc in prod

component migration from cnv-moc to zero-moc in prod

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Push SLO-reporter to v0.11.0 in stage and prod-stage

---

prow/overlays/cnv-prod/config.yaml

n/a
as discussed during release meeting

run integration-test v0.8 as a periodic prow job targeting {zero|cnv}-prod

---

core/overlays/cnv-prod/graph-prod/postgresql.yaml
core/overlays/ocp4-stage/graph-stage/postgresql.yaml

increase mem resource for the postgresql deployment

increase mem resource for the postgresql deployment

---

core/overlays/ocp4-stage/common/configmaps.yaml
solver/overlays/cnv-prod/imagestreamtag.yaml
solver/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/test/imagestreamtag.yaml

upgrade solvers to latest version and decommision solver-f32-py37
Related-to: #809

upgrade solvers to latest version and decommision solver-f32-py37

---

solver/base/argo-workflows/solver-template.yaml

Depends-On: https://github.com/thoth-station/solver/pull/662
Related: https://github.com/thoth-station/solver/issues/417
Related: https://github.com/thoth-station/s2i-thoth/issues/128

Change solver virtual env location

---

slo-reporter/overlays/ocp4-stage/cronjob.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml

SLO reporter stage and prod can send emails

---

user-api/base/configmap.yaml
user-api/base/deploymentconfig.yaml
user-api/overlays/ocp4-stage/configmap.yaml
user-api/overlays/test/configmap.yaml

Related: https://github.com/thoth-station/user-api/pull/1334

Make sure exceptions are reported on API when running in test/stage

---

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump metrics-exporter to v0.13.0

---

core/overlays/ocp4-stage/graph-stage/postgresql.yaml

increase cpu for the postgresql in stage
with this we would still have lot of free resources in the namespace thoth-graph-stage

increase cpu for the postgresql in stage

---

adviser/base/argo-workflows/advise.yaml
adviser/base/argo-workflows/dependency-monkey.yaml
adviser/base/argo-workflows/provenance-check.yaml

Related: https://github.com/thoth-station/adviser/pull/1708

Remove ENABLE_PREPARE specific configuration for adviser

---

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

```
[FIRING:1] ThothSchemaCheckStageMetricsExporter Thoth Metrics (metrics-exporter ocp4-stage metrics-exporter-thoth-infra-stage.apps.ocp4.prod.psi.redhat.com:80 datahub)
```

Solve metrics exporter schema check alarm for stage

---

core/overlays/test/postgresql.yaml
core/overlays/test/secrets.enc.yaml

configure admin user for the postgresql instance
Related-to: 
- https://github.com/thoth-station/thoth-application/issues/725
- https://github.com/thoth-station/storages/issues/2250
This would set  up a admin user for the posgresql db, then user can be used by other component based on use cases.

configure admin user for the postgresql instance

---

monitoring/README.md
monitoring/base/alertmanager-monitoring.yaml
monitoring/base/github-receiver.yaml
monitoring/base/kustomization.yaml
monitoring/base/prometheus-rules.yaml
monitoring/overlays/cnv-prod/kustomization.yaml

alert manager and monitoring for thoth production
Related-to: https://github.com/thoth-station/thoth-application/issues/854

alert manager and monitoring for thoth production

---

amun/overlays/cnv-prod/amun-api/configmaps.yaml
amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
core/overlays/cnv-prod/graph-prod/ceph-storage.yaml

introduce a new ceph setup and cofnigured amun with it
Related-to: https://github.com/thoth-station/amun-api/issues/613#issuecomment-801060846

introduce a new ceph setup and cofnigured amun with it

---

slo-reporter/overlays/zero-prod-ocp4-stage/configmap.yaml

Send prod email to AICoE

---

amun/overlays/cnv-prod/amun-inspection/configmaps.yaml

increase the ttl for amun-inspection workflows to 1hr
Related-to: https://github.com/thoth-station/amun-api/issues/611#issuecomment-801760231

increase the ttl for amun-inspection workflows to 1hr

---

core/overlays/cnv-prod/common/configmaps.yaml
core/overlays/cnv-prod/common/secrets.enc.yaml

configure thoth prod cluster with updated ceph

configure thoth prod cluster with updated ceph

---

graph-backup-job/overlays/ocp4-stage/thoth-notification.yaml

Thanks to @harshad16 for spotting this.

Fix links in graph-backup job

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Use new version for slo-reporter

---

prow/overlays/cnv-prod/config.yaml
prow/overlays/cnv-prod/label-sync-cronjob.yaml
prow/overlays/cnv-prod/labels_aicoe-aiops.yaml

SSIA
Setups additional Prow configuration for `aicoe-aiops`. 
/cc @MichaelClifford @durandom @hemajv @martinpovolny please review
Lebels file is derived from `labels_operate-first.yaml` and `labels.yaml` files.

feat: Setup prow for aicoe-aiops

---

prow/overlays/cnv-prod/config.yaml

:arrow_up: update the container image tags used to decorate prow jobs

---

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
mi-scheduler/base/cronjob.yaml
mi-scheduler/base/openshift-templates/mi-run-template.yaml

See comment here https://github.com/thoth-station/mi-scheduler/pull/105#issuecomment-804090599
This sets log envs correctly for `mi` and `mi-scheduler` applications

Add logging envs

---

adviser/overlays/cnv-prod/advise-resources-patch.yaml
adviser/overlays/cnv-prod/kustomization.yaml

increase the resources for adviser run in the production environment
Related-to: https://github.com/thoth-station/integration-tests/issues/165

increase the resources for adviser run in the production environment

---

adviser/overlays/cnv-prod/advise-resources-patch.yaml

debug increase of the resources for adviser run in the production
Related-to: https://github.com/thoth-station/integration-tests/issues/165

debug increase of the resources for adviser run in the production

---

qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml

bump resources for the qebhwt workflow
Related-to: #1085

bump resources for the qebhwt workflow

---

prow/overlays/cnv-prod/config.yaml

manage required checks for repos
Related-to: https://github.com/thoth-station/elyra-aidevsecops-tutorial/pull/127

manage required checks for repos

---

prescription-sync-job/base/cronjob.yaml

Otherwise only help message is printed as no command is supplied.

Run prescription sync command

---

adviser/base/argo-workflows/advise.yaml
adviser/base/argo-workflows/dependency-monkey.yaml

Related: https://github.com/thoth-station/thoth-application/issues/1052

Supply prescription.yaml to adviser container

---

prescription-sync-job/base/cronjob.yaml

Prescription syncing does not require knowledge graph

---

prow/overlays/cnv-prod/labels_operate-first.yaml

Tiny labels cleanup for the operate first

chore: Update operate first labels

---

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
mi-scheduler/base/openshift-templates/mi-run-template.yaml

Two workflows are not operational. Reducing to only one :'(

Mi scheduler/reduce parallelism

---

package-extract/overlays/cnv-prod/kustomization.yaml
package-extract/overlays/ocp4-stage/kustomization.yaml

templates are to be placed on the infra namespace

templates are to be placed on the infra namespace

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml

Bump up version for messaging v0.12.0 for stage and prod
Related-to: https://github.com/thoth-station/investigator/issues/479
Described here: https://github.com/thoth-station/investigator/issues/479#issuecomment-808484396

Bump up version for messaging v0.12.0 for stage and prod

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Bump adviser to 0.27.0 in stage

---

prow/overlays/cnv-prod/labels_operate-first.yaml

SSIA, resolves https://github.com/operate-first/support/issues/175

chore: Add triage labels for Operate First

---

advise-reporter/base/cronjob.yaml

Issue with Kafka due to wrong env variables.

Fix advise reporter talking to kafka

---

core/overlays/cnv-prod/common/secrets.enc.yaml

updated kafka certs for prod cluster
the certs are changed on production for each user of the cluster.

updated kafka certs for prod cluster

---

core/overlays/cnv-prod/common/secrets.enc.yaml

Reverts thoth-station/thoth-application#1135

Revert "updated kafka certs for prod cluster"

---

amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
amun/overlays/test/secrets.enc.yaml
core/overlays/cnv-prod/common/secrets.enc.yaml
core/overlays/ocp4-stage/common/secrets.enc.yaml
core/overlays/test/secrets.enc.yaml

updated thoth secrets across the board
Related-to: https://github.com/thoth-station/thoth-application/issues/945

updated thoth secrets across the board

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

- New version adjust references link to dashboards to be customizable.
- New version introduces workflow tasks latency in SLO report

Bump SLO-reporter to v0.13.0

---

core/overlays/cnv-prod/common/secrets.enc.yaml

updated new kafka certs for the prod

updated new kafka certs for the prod

---

core/overlays/zero-test/argo-namespace-install.yaml
core/overlays/zero-test/argo-ui-route.yaml
core/overlays/zero-test/argo-workflow-controller-metrics.yaml
core/overlays/zero-test/argo-workflows/send-message.yaml
core/overlays/zero-test/argo-workflows/send-messages.yaml
core/overlays/zero-test/buildConfig.yaml
core/overlays/zero-test/configmaps.yaml
core/overlays/zero-test/imagestreamtags.yaml
core/overlays/zero-test/job-generate-name.yaml
core/overlays/zero-test/kustomization.yaml
core/overlays/zero-test/pgbouncer.yaml
core/overlays/zero-test/postgresql-metrics-exporter.yaml
core/overlays/zero-test/postgresql.yaml
core/overlays/zero-test/secret-generator.yaml
core/overlays/zero-test/secrets.enc.yaml
core/overlays/zero-test/thoth-notification.yaml

created separate overlay for zero-test

created separate overlay for zero-test

---

core/overlays/zero-test/argo-namespace-install.yaml
core/overlays/zero-test/postgresql.yaml

Zero test fix
Fixing the issue with the zero-test cluster namespace

Zero test fix

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

fix defaults

---

user-api/base/deploymentconfig.yaml

To enable authenticated workflow, we need to provide a token to User API. See:
https://github.com/thoth-station/user-api/blob/20ac6db4154e5480970727ff831d0272bfbd5d1c/thoth/user_api/configuration.py#L37

Add missing User API token

---

adviser/base/openshift-templates/adviser.yaml
adviser/base/openshift-templates/provenance-checker.yaml

```
Failed: invalid spec: templates.adviser.tasks.graph-sync-advise failed to resolve {{workflow.parameters.THOTH_AUTHENTICATED_ADVISE}}
```

Fix parameters in the template

---

amun/overlays/cnv-prod/amun-api/secrets.enc.yaml
amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
amun/overlays/test/secrets.enc.yaml
core/overlays/cnv-prod/common/secrets.enc.yaml
core/overlays/ocp4-stage/common/secrets.enc.yaml
core/overlays/test/secrets.enc.yaml
core/overlays/zero-test/secrets.enc.yaml
integration-tests/overlays/cnv-prod-ocp4-stage/secrets.enc.yaml
integration-tests/overlays/ocp4-stage/secrets.enc.yaml
integration-tests/overlays/test/secrets.enc.yaml
management-api/base/deploymentconfig.yaml
user-api/base/deploymentconfig.yaml

set different secret for app-secret from thoth token
ensure separate secret for app-secret for the application and token for app-request-authentication

set different secret for app-secret from thoth token

---

adviser/base/openshift-templates/adviser.yaml
adviser/base/openshift-templates/provenance-checker.yaml

Additionally restrict unauthenticated parts of the workflows

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/thoth-application/pull/1146

Bump adviser to v0.28.0 in stage environment

---

.github/CODEOWNERS
prow/overlays/cnv-prod/config.yaml
prow/overlays/cnv-prod/integration-test-configmap.yaml
prow/overlays/cnv-prod/kustomization.yaml
prow/overlays/cnv-prod/secrets.enc.yaml

update integration test periodic

---

core/overlays/zero-test/imagestreamtags.yaml

bump up the investigator and messaging for the zero-test

bump up the investigator and messaging for the zero-test

---

user-api/overlays/cnv-prod/imagestreamtag.yaml
user-api/overlays/ocp4-stage/imagestreamtag.yaml

bump up the user-api 0.24.3 in the prod
Related-to: https://github.com/thoth-station/thoth-application/issues/1125
this would solve the internal issue we are facing on production.

bump up the user-api 0.24.3 in the prod

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml

bump up the investigator and messaging for the prod
Related-to: #1125

bump up the investigator and messaging for the prod

---

.github/PULL_REQUEST_TEMPLATE.md

updated the pull request template for thoth-application
make the pull request template more inclusive towards the repository.

updated the pull request template for thoth-application

---

qeb-hwt-github-app/overlays/test/argo-workflows/qeb-hwt-integration.yaml
qeb-hwt-github-app/overlays/test/openshift-templates/qeb-hwt.yaml

Related-To: https://github.com/thoth-station/thoth-application/issues/1178

Modify qeb-hwt to use thamos instead of messaging

---

slo-reporter/overlays/zero-prod-ocp4-stage/configmap.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/secrets.enc.yaml

Store in zero-prod on s3 in Operate First

---

advise-reporter/base/cronjob.yaml
advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
advise-reporter/overlays/test/buildConfig.yaml
advise-reporter/overlays/test/cronjob.yaml
slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Bump advise-reporter to `v0.7.3`
Bump slo-reporter to `v0.14.0`

update reporting components

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Add small adjustments in emails to be more clear.

Bump slo-reporter to v0.14.1

---

user-api/overlays/test/imagestreamtag.yaml

Related: https://github.com/thoth-station/user-api/pull/1407

Deploy user-api v0.25.0 to test environment

---

sefkhet-abwy/overlays/bot/configmap.yaml
sefkhet-abwy/overlays/bot/imagestreamtag.yaml
sefkhet-abwy/overlays/bot/kustomization.yaml
sefkhet-abwy/overlays/bot/secret-generator.yaml
sefkhet-abwy/overlays/bot/secrets.enc.yaml
sefkhet-abwy/overlays/bot/thoth-friday-scrum-cronjob.yaml
sefkhet-abwy/overlays/bot/thoth-scrum-cronjob.yaml

setup scrum-bot to the application component

setup scrum-bot to the application component

---

amun/overlays/ocp4-stage/amun-api/message-imagestream.yaml
amun/overlays/test/message-imagestream.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
core/overlays/zero-test/imagestreamtags.yaml
graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
kebechet/overlays/test/imagestreamtag.yaml
mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
security-indicators/overlays/ocp4-stage/imagestreamtag.yaml

Bump up versions for component in stage

Bump up versions for component in stage

---

mi-scheduler/overlays/test/imagestreamtag.yaml

Related to https://github.com/thoth-station/mi/issues/385
and https://github.com/thoth-station/mi/issues/388#issuecomment-829225565

Push new mi release

---

prow/overlays/cnv-prod/config.yaml

Hopefully solves https://github.com/thoth-station/thoth-application/issues/1215 for Operate-first.
Please check if this PR make sense since I don't know enough about Prow to fully understand what I'm doing...

feat(operate-first): Make tide to require lgtm label on merge

---

advise-reporter/overlays/test/imagestreamtag.yaml

missing new tag in test for advise-reporter

---

core/overlays/ocp4-stage/common/imagestreamtags.yaml
core/overlays/test/imagestreamtags.yaml
core/overlays/zero-test/imagestreamtags.yaml
graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
graph-backup-job/overlays/test/imagestreamtag.yaml
graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
graph-refresh/overlays/test/imagestreamtag.yaml
graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
graph-sync/overlays/test/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
metrics-exporter/overlays/test/imagestreamtag.yaml

Bump up versions of thoth components in stage

Bump up versions of thoth components in stage

---

core/overlays/cnv-prod/graph-prod/postgresql.yaml

Expand db pvc size
Related-to: #1221

Expand db pvc size

---

core/overlays/cnv-prod/backend-prod/argo-role.yaml
core/overlays/cnv-prod/middletier-prod/argo-role.yaml
core/overlays/zero-test/argo-role.yaml

this might fix https://github.com/thoth-station/kebechet/issues/720

enable argo serviceAccount to get pod logs

---

adviser/base/openshift-templates/provenance-checker.yaml

updated the correct variable for the provenance fix
Fixes: #1228 
Wrong variable was substituted.

updated the correct variable for the provenance fix

---

management-api/base/deploymentconfig.yaml

Add graph namespace to management-api

---

purge-job/base/argo-workflows/purge-template.yaml
purge-job/base/imagestream.yaml
purge-job/base/kustomization.yaml
purge-job/base/openshift-templates/purge.yaml
purge-job/overlays/cnv-prod/imagestreamtag.yaml
purge-job/overlays/cnv-prod/job-generate-name.yaml
purge-job/overlays/cnv-prod/kustomization.yaml
purge-job/overlays/cnv-prod/put-into-infra-namespace.yaml
purge-job/overlays/cnv-prod/thoth-notification.yaml
purge-job/overlays/ocp4-stage/imagestreamtag.yaml
purge-job/overlays/ocp4-stage/job-generate-name.yaml
purge-job/overlays/ocp4-stage/kustomization.yaml
purge-job/overlays/ocp4-stage/put-into-infra-namespace.yaml
purge-job/overlays/ocp4-stage/thoth-notification.yaml
purge-job/overlays/test/imagestreamtag.yaml
purge-job/overlays/test/job-generate-name.yaml
purge-job/overlays/test/kustomization.yaml
purge-job/overlays/test/thoth-notification.yaml

Related: https://github.com/thoth-station/purge-job/
Purging old data out of a Thoth deployment.

Introduce purge-job

---

prow/overlays/cnv-prod/labels_operate-first.yaml

Related to: https://github.com/operate-first/SRE/issues/283
/cc @HumairAK

feat: Add incident labels

---

graph-refresh/base/cronjob.yaml
investigator/base/deploymentconfig.yaml
revsolver/overlays/cnv-prod/imagestreamtag.yaml
revsolver/overlays/ocp4-stage/imagestreamtag.yaml

Enable revsolver

---

core/overlays/zero-test/imagestreamtags.yaml

I only updated one test env with my last PR

update zero-test messaging

---

adviser/base/argo-workflows/advise.yaml

Related: https://github.com/thoth-station/adviser/issues/1850

Tweak MCTS heat up phase

---

investigator/overlays/zero-test/deploymentconfig.yaml
investigator/overlays/zero-test/job-generate-name.yaml
investigator/overlays/zero-test/kustomization.yaml
investigator/overlays/zero-test/role.yaml
investigator/overlays/zero-test/role_binding.yaml
investigator/overlays/zero-test/route.yaml
investigator/overlays/zero-test/service.yaml
investigator/overlays/zero-test/thoth-notification.yaml

```
RBAC: [clusterrole.rbac.authorization.k8s.io \\\"argo-admin\\\" not found, clusterrole.rbac.authorization.k8s.io \\\"argo\\\" not found]\",\"reason\":\"Forbidden\",\"details\":{\"group\":\"argoproj.io\",\"kind\":\"workflows\"},\"code\":403}\n\n"}
```
Separate zero-test overlay investigator as it uses non cluster role

Separate zero-test overlay investigator as it uses non cluster role

---

monitoring/base/alertmanager-monitoring.yaml
monitoring/base/github-receiver.yaml
monitoring/base/kustomization.yaml
monitoring/base/prometheus-rules.yaml
monitoring/overlays/cnv-prod/kustomization.yaml
monitoring/overlays/cnv-prod/secret-generator.yaml
monitoring/overlays/cnv-prod/secrets.enc.yaml

Related-to: https://github.com/thoth-station/thoth-application/issues/854
Setup alert manager for thoth services alerting

Setup alertmanager for thoth services alerting

---

monitoring/base/prometheus-rules.yaml

Fixes: https://github.com/thoth-station/metrics-exporter/issues/598
Related-To: https://github.com/thoth-station/thoth-application/issues/854
Some alarms will be activated until https://github.com/thoth-station/metrics-exporter/pull/667 is merged and new version released in prod.

Add new alerts for prod

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
qeb-hwt-github-app/base/argo-workflows/qeb-hwt-integration.yaml
qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml

Fixes: https://github.com/thoth-station/thoth-application/issues/1178

Add new qeb-hwt workflow

---

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
metrics-exporter/overlays/test/imagestreamtag.yaml

Important for alarms, cc @harshad16

bump metrics exporter to v0.14.4

---

user-api/base/deploymentconfig.yaml

n/a
This adds some 3scale related annotations/label to user-api

add service discovery annotations/labels to user-api

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/test/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Solve one issue with datatype parsing.

bump slo-reporter to v0.14.2

---

adviser/overlays/test/imagestreamtag.yaml
core/overlays/zero-test/imagestreamtags.yaml

update test image streams to latest releases

---

prow/overlays/cnv-prod/s3-bucket-claim.yaml

setup nooba based ceph for prow
Related-to: https://github.com/operate-first/support/issues/243
Attempt to switch from rgw based ceph to nooba.

setup nooba based ceph for prow

---

prow/overlays/cnv-prod/imagestreamtags.yaml

Arrange the prow images in alphabetical order
NO other changes included, just ordered based on alphabetical order.

Arrange the prow images in alphabetical order

---

prow/base/crier.yaml
prow/base/deck.yaml
prow/base/deploymentconfig.yaml
prow/base/ghproxy.yaml
prow/base/hook.yaml
prow/base/label_sync_job.yaml
prow/base/needs-rebase.yaml
prow/base/prow-controller-manager.yaml
prow/base/sinker.yaml
prow/base/statusreconciler.yaml
prow/base/tide.yaml

Set limits on the prow deployments based on usage
Based-on: https://github.com/operate-first/apps/pull/653
Set the limits for resources based on the usage over the period of time.

Set limits on the prow deployments based on usage

---

core/base/argo-workflows/send-messages.yaml
kebechet/base/argo-workflows/update_keb_installation.yaml
kebechet/base/openshift-templates/kebechet-administrator.yaml

Keb admin workflow failing 
workflow entrypoint was wrong and some volumes needed to be mounted

keb admin workflow was failing

---

prow/overlays/cnv-prod/secrets.enc.yaml

Related-to: https://github.com/operate-first/support/issues/243
update the prow ceph bucket cerds

update the prow ceph bucket cerds

---

solver/base/argo-workflows/solver-template.yaml

I observed some solvers failing due to OOM.

Increase memory for solvers to 2Gi

---

adviser/base/openshift-templates/adviser.yaml
adviser/base/openshift-templates/dependency-monkey.yaml
adviser/base/openshift-templates/provenance-checker.yaml
kebechet/base/openshift-templates/kebechet-administrator.yaml
kebechet/base/openshift-templates/kebechet-run-url.yaml
kebechet/base/openshift-templates/kebechet.yaml
qeb-hwt-github-app/base/openshift-templates/qeb-hwt.yaml

Reduce the time to live 15-30 mins for backend workflows

Reduce the time to live 15-30 mins for backend workflows

---

solver/base/argo-workflows/solver-template.yaml

Related: https://github.com/thoth-station/solver/pull/704/
Related: https://github.com/thoth-station/solver/issues/703

Raise solvers on exit code propagating a signal from operating system

---

amun/base/service.yaml
amun/overlays/cnv-prod/amun-inspection/argo-namespace-install.yaml
amun/overlays/cnv-prod/amun-inspection/argo-workflow-controller-metrics.yaml
core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml
core/overlays/cnv-prod/backend-prod/argo-workflow-controller-metrics.yaml
core/overlays/cnv-prod/graph-prod/postgresql-metrics-exporter.yaml
core/overlays/cnv-prod/middletier-prod/argo-namespace-install.yaml
core/overlays/cnv-prod/middletier-prod/argo-workflow-controller-metrics.yaml
investigator/overlays/cnv-prod/service.yaml
management-api/base/service.yaml
metrics-exporter/base/service.yaml
user-api/base/service.yaml

set name of service port as metrics for the components

set name of service port as metrics for the components

---

solver/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/solver/issues/708

Bump solvers to v1.9.0 in stage environment

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Bump SLO-reporter to v0.14.3

---

prow/overlays/cnv-prod/config.yaml

include elyra aidevsecops to prow
Related-to: https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/162#issuecomment-848589082

include elyra aidevsecops to prow

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/user-api/pull/1423

Deploy user-api v0.25.2 to stage environment

---

kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/kebechet/issues/730

Bump Kebechet to v1.3.0 in stage environment

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/issues/1883

Bump adviser to v0.31.0 in stage environment

---

core/overlays/ocp4-stage/backend-stage/configmaps.yaml
core/overlays/quicklab/configmaps.yaml
core/overlays/test/configmaps.yaml
core/overlays/zero-test/configmaps.yaml

Related: https://github.com/thoth-station/thoth-application/issues/1202#issuecomment-828291143
Related: https://github.com/thoth-station/thoth-application/issues/1557
Related: https://github.com/thoth-station/thoth-application/issues/325

Archive logs to have them accessible to users

---

core/overlays/cnv-prod/backend-prod/argo-namespace-install.yaml
core/overlays/ocp4-stage/backend-stage/argo-namespace-install.yaml
core/overlays/quicklab/argo-namespace-install.yaml
core/overlays/test/argo-namespace-install.yaml
core/overlays/zero-test/argo-namespace-install.yaml

Allow argo role list pod logs

---

cve-update/base/cronjob.yaml

closes: https://github.com/thoth-station/cve-update-job/issues/413
Wrong envvar being used for ca location

wrong env var used for ca location

---

revsolver/overlays/ocp4-stage/imagestreamtag.yaml

Bump revsolver to v0.2.5 in stage environment

---

core/overlays/ocp4-stage/common/imagestreamtags.yaml
core/overlays/test/imagestreamtags.yaml
core/overlays/zero-test/imagestreamtags.yaml
graph-sync/overlays/ocp4-stage/imagestreamtag.yaml
graph-sync/overlays/test/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
package-releases/overlays/ocp4-stage/imagestreamtag.yaml
package-releases/overlays/test/imagestreamtag.yaml

Bump up the version of stage thoth services

Bump up the version of stage thoth services

---

advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
core/overlays/cnv-prod/common/imagestreamtags.yaml
cve-update/overlays/cnv-prod/imagestreamtag.yaml
graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
graph-sync/overlays/cnv-prod/imagestreamtag.yaml
management-api/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
package-releases/overlays/cnv-prod/imagestreamtag.yaml
revsolver/overlays/cnv-prod/imagestreamtag.yaml
user-api/overlays/cnv-prod/imagestreamtag.yaml

Bump thoth production services with updated versions

---

kebechet/overlays/cnv-prod/imagestreamtag.yaml

Related: https://github.com/thoth-station/thoth-application/pull/1532
Related: https://github.com/thoth-station/kebechet/issues/730

Bump Kebechet to v1.3.0 in prod

---

.prow.yaml

set resource limit for prow jobs
…

set resource limit for prow jobs

---

kebechet/overlays/cnv-prod/imagestreamtag.yaml

revert back to kebechet v1.2.4
Related-to: https://github.com/thoth-station/kebechet/issues/735

revert back to kebechet v1.2.4

---

adviser/base/argo-workflows/advise.yaml

Related: https://github.com/thoth-station/adviser/issues/1885

Supply a path to labels.json location to take labels into account

---

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Fixes: https://github.com/thoth-station/metrics-exporter/issues/688

Bump metrics-exporter to v0.14.6 to fix bug

---

kebechet/base/argo-workflows/update_keb_installation.yaml

https://github.com/thoth-station/workflow-helpers/pull/223#discussion_r648388612

add retry strategy for installation update

---

kebechet/overlays/cnv-prod/imagestreamtag.yaml

Related-To: https://github.com/thoth-station/thoth-application/issues/1651

Rollback Kebechet due to bug

---

adviser/base/argo-workflows/advise.yaml
adviser/base/openshift-templates/adviser.yaml

https://github.com/thoth-station/adviser/blob/e08bd43e44979f84d00c1e1a08f9d4120223619b/thoth/adviser/sieves/update.py#L61

add new template param for package update advises

---

amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml

Related: https://github.com/thoth-station/amun-api/issues/626

Bump Amun API to v0.9.5 in stage environment

---

.prow.yaml

increase the resource for kustomize prow job

increase the resource for kustomize prow job

---

solver/base/imagestreams.yaml
solver/overlays/cnv-prod/imagestreamtag.yaml

Related: thoth-station/s2i-thoth#184
Related: #663

Add solver-f34-py39 to CNV prod

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

bump version of Adviser v0.33.1 in stage

---

adviser/base/argo-workflows/advise.yaml

Related: https://github.com/thoth-station/adviser/issues/1911

Block security indicator step to resolve stacks without si

---

triage-party/overlays/zero-prod/imagestreamtags.yaml

Switch to thoth-station triage-party image
Related-to: https://github.com/thoth-station/thoth-application/issues/1649#issuecomment-859775434
Built the image from https://github.com/google/triage-party
cc: @goern

Switch to thoth-station triage-party image

---

prescriptions-gh-release-notes-job/base/openshift-templates/prescriptions-gh-release-notes.yaml

Closes: https://github.com/thoth-station/prescriptions/issues/18

introduce GitHub release notes prescription job

---

amun/overlays/cnv-prod/amun-api/message-imagestream.yaml
amun/overlays/ocp4-stage/amun-api/message-imagestream.yaml
amun/overlays/test/message-imagestream.yaml
core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
core/overlays/zero-test/imagestreamtags.yaml
graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
package-releases/overlays/cnv-prod/imagestreamtag.yaml
package-releases/overlays/ocp4-stage/imagestreamtag.yaml
package-update/overlays/cnv-prod/imagestreamtag.yaml
package-update/overlays/ocp4-stage/imagestreamtag.yaml
user-api/overlays/cnv-prod/imagestreamtag.yaml
user-api/overlays/ocp4-stage/imagestreamtag.yaml

Bump up all apps which are related to the messaging update
Related-to: https://github.com/thoth-station/thoth-application/issues/1618

Bump up all apps which are related to the messaging update

---

init-job/base/argo-workflows/initialize-schema.yaml

Related: https://github.com/thoth-station/init-job/pull/418

Configure solver rules in init-job

---

solver/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/test/imagestreamtag.yaml

enable all deployment environments to have new solvers

enable all deployment environments to have new solvers

---

adviser/base/imagestream.yaml
adviser/overlays/cnv-prod/imagestreamtag.yaml
adviser/overlays/ocp4-stage/imagestreamtag.yaml
adviser/overlays/test/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/issues/1908

Add image streams for prescriptions

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/pull/1924

Bump adviser to v0.34.0 in stage environment

---

prow/overlays/cnv-prod/kustomization.yaml
prow/overlays/cnv-prod/org_thoth-station.yaml
prow/overlays/cnv-prod/peribolos.yaml

see https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos

add peribolos for thoth-station

---

core/overlays/cnv-prod/common/secrets.enc.yaml
investigator/overlays/cnv-prod/deploymentconfig.yaml
investigator/overlays/cnv-prod/kustomization.yaml

update the ssl certs for investigator

update the ssl certs for investigator

---

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml

Related to https://github.com/thoth-station/thoth-application/pull/1704#event-4898469014

Add increased timeout to workflow template (12k seconds)

---

investigator_message_metrics/overlays/zero-prod/deploymentconfig.yaml
investigator_message_metrics/overlays/zero-prod/kustomization.yaml

setup the investigator message metrics for prod
Related-to: https://github.com/thoth-station/metrics-exporter/issues/654

setup the investigator message metrics for prod

---

advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
user-api/overlays/cnv-prod/imagestreamtag.yaml
user-api/overlays/ocp4-stage/imagestreamtag.yaml

bump up module with messaging update

bump up module with messaging update

---

adviser/base/argo-workflows/advise.yaml

Related: https://github.com/thoth-station/prescriptions/pull/24
Depends-On: https://github.com/thoth-station/thoth-application/pull/1694
Depends-On: https://github.com/thoth-station/thoth-application/pull/1701
Related: https://github.com/thoth-station/adviser/issues/1908

Make prescriptions available to the adviser container

---

slo-reporter/overlays/zero-prod-ocp4-stage/configmap.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/cronjob.yaml

fix the slo-reporter configmap and cronjob

fix the slo-reporter configmap and cronjob

---

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
mi-scheduler/base/openshift-templates/mi-run-template.yaml

Fixes https://github.com/thoth-station/common/issues/1174
Add MI_MERGE flag for data merging into the mi templates (run and workflow)

Add merge flags to run and workflow templates

---

prescriptions-gh-release-notes-job/base/openshift-templates/prescriptions-gh-release-notes.yaml

updated the sa for the prescription release notes

updated the sa for the prescription release notes

---

management-api/overlays/cnv-prod/imagestreamtag.yaml
user-api/overlays/cnv-prod/imagestreamtag.yaml
user-api/overlays/ocp4-stage/imagestreamtag.yaml

Bump version thoth services for release v06.21.2021

Bump version thoth services for release v06.21.2021

---

adviser/base/argo-workflows/advise.yaml
adviser/base/openshift-templates/adviser.yaml

fix of the volume placement in the workflow
Related-to: #1743 
This is tested :medal_sports:

fix of the volume placement in the workflow

---

solver/base/argo-workflows/solver-template.yaml

Reduce the resource usage based on comsumption
This will help us with boosting more solver runs at a time.

Reduce the resource usage based on comsumption

---

core/base/configmaps.yaml
pulp-pypi-sync-job/base/cronjob.yaml
pulp-pypi-sync-job/base/imagestream.yaml
pulp-pypi-sync-job/base/kustomization.yaml
pulp-pypi-sync-job/overlays/cnv-prod/cronjob.yaml
pulp-pypi-sync-job/overlays/cnv-prod/imagestreamtag.yaml
pulp-pypi-sync-job/overlays/cnv-prod/job-generate-name.yaml
pulp-pypi-sync-job/overlays/cnv-prod/kustomization.yaml
pulp-pypi-sync-job/overlays/cnv-prod/thoth-notification.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/cronjob.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/job-generate-name.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/kustomization.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/thoth-notification.yaml
pulp-pypi-sync-job/overlays/test/cronjob.yaml
pulp-pypi-sync-job/overlays/test/imagestreamtag.yaml
pulp-pypi-sync-job/overlays/test/job-generate-name.yaml
pulp-pypi-sync-job/overlays/test/kustomization.yaml
pulp-pypi-sync-job/overlays/test/thoth-notification.yaml

Related: https://github.com/thoth-station/thoth-application/issues/1733

Introduce pulp-pypi-sync-job

---

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

bump metrics-exporter to v0.16.1

---

metrics-exporter/base/deploymentconfig.yaml
metrics-exporter/overlays/cnv-prod/deploymentconfig.yaml

set the resource based on the usage

set the resource based on the usage

---

graph-schema-update/base/openshift-templates/graph-schema-update-job-template.yaml

set more timeout sec for graph schema update
Having trouble updating schema in the db.

set more timeout sec for graph schema update

---

mi-scheduler/base/configmaps.yaml

https://github.com/thoth-station/mi-scheduler/issues/140
Schedule data aggregation for `aicoe-aiops` organization
Also add `thoth-station` org and `openshift/origin` repo (it got somehow lost in past local commits)

Mi scheduler/schedule aicoe aiops

---

integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
prow/overlays/cnv-prod/config.yaml

Related: https://github.com/thoth-station/integration-tests/issues/202

Bump integration-tests to v0.8.3

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Add labels to metrics pushed to pushgateway

Bump SLO reporter to v0.15.0

---

prow/overlays/cnv-prod/config.yaml

fix: Enable on repo prow for AICoE

---

slo-reporter/overlays/test/cronjob.yaml

Stop SLO-reporter test

---

adviser/base/argo-workflows/trigger-integration.yaml
adviser/base/openshift-templates/adviser.yaml
core/base/configmaps.yaml
core/overlays/cnv-prod/common/configmaps.yaml
core/overlays/ocp4-stage/common/configmaps.yaml
core/overlays/test/configmaps.yaml
core/overlays/zero-test/configmaps.yaml
docs/environments.md
prow/overlays/cnv-prod/labels.yaml
prow/overlays/cnv-prod/org_thoth-station.yaml

Related-To: https://github.com/thoth-station/user-api/issues/1454

Remove last bits of qeb-hwt

---

advise-reporter/overlays/ocp4-stage/cronjob.yaml
cve-update/overlays/ocp4-stage/cronjob.yaml
graph-refresh/overlays/ocp4-stage/cronjob.yaml
package-releases/overlays/ocp4-stage/cronjob.yaml
package-update/overlays/ocp4-stage/cronjob.yaml
slo-reporter/overlays/ocp4-stage/cronjob.yaml

pause the data ingestion for the stage cluster

pause the data ingestion for the stage cluster

---

graph-refresh/overlays/cnv-prod/cronjob.yaml
package-releases/base/cronjob.yaml
package-update/overlays/cnv-prod/cronjob.yaml

resume the data ingestion for the prod
Related-to: https://github.com/thoth-station/thoth-application/issues/1766

resume the data ingestion for the prod

---

advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml

Related-To: https://github.com/thoth-station/metrics-exporter/issues/725
Related-To: https://github.com/thoth-station/metrics-exporter/issues/724

Bump reporter to v0.10.0

---

core/overlays/ocp4-stage/common/configmaps.yaml

switch on only the solver needed for the ingestion

switch on only the solver needed for the ingestion

---

core/overlays/ocp4-stage/common/configmaps.yaml

switch on only the ubi8 solver for the ingestion

switch on only the ubi8 solver for the ingestion

---

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump metrics-exporter to v0.16.2

---

metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump metrics-exporter to v0.16.3

---

advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml

Fix issue encountered: https://github.com/thoth-station/reporter/pull/226#issue-682442442

Bump thoth reporter to v0.10.1

---

advise-reporter/overlays/cnv-prod/imagestreamtag.yaml
advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump adviser reporter to v0.10.2

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
graph-backup-job/overlays/cnv-prod/imagestreamtag.yaml
graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
graph-metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
graph-refresh/overlays/cnv-prod/imagestreamtag.yaml
graph-sync/overlays/cnv-prod/imagestreamtag.yaml

Related-To: https://github.com/thoth-station/thoth-application/issues/1792 (all patch releases)

Bump graph related component to v0.51.0 of thoth-storages

---

grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json

Related-To: https://github.com/thoth-station/thoth-application/issues/429

Add workflows rate metrics

---

mi-scheduler/base/configmaps.yaml
mi-scheduler/base/cronjob.yaml

None
All of the data aggregation requests are currently Issues and Pullrequests, therefore changing entities to be only these by default

Add MI entities as PullRequest and Issue

---

mi-scheduler/base/cronjob.yaml

Related to https://github.com/thoth-station/thoth-application/pull/1809

Fix reference to be key instead of value

---

mi-scheduler/base/configmaps.yaml

Related to https://github.com/thoth-station/common/pull/1187

Changing org list to not contain spaces

---

mi-scheduler/base/cronjob.yaml

None
Fix the logging envvar value

Fix thoth logging for mi-github cronjob

---

mi-scheduler/base/configmaps.yaml

Make entities consistent with other string lists

---

triage-party/overlays/zero-prod/config.yaml

:sparkles: do not include area/rel-eng issues from filter

---

graph-refresh/overlays/ocp4-stage/cronjob.yaml

switch on the graph-refresh job for stage

switch on the graph-refresh job for stage

---

purge-job/base/argo-workflows/purge-issues.yaml
purge-job/base/kustomization.yaml
purge-job/base/openshift-templates/purge.yaml

Related: #1644 
Depends on: thoth-station/workflow-helpers#301

add new step in purge job for creating upstream issues

---

mi-scheduler/overlays/zero-test/secrets.enc.yaml

I created a new GH user to get mote API bandwidth for MI, this is the secrets of this user and a access token.

add secrets for meta-informa

---

adviser/overlays/cnv-prod/imagestreamtag.yaml
core/overlays/cnv-prod/common/imagestreamtags.yaml
mi-scheduler/overlays/cnv-prod/imagestreamtag.yaml
package-extract/overlays/cnv-prod/imagestreamtag.yaml
package-update/overlays/cnv-prod/imagestreamtag.yaml
revsolver/overlays/cnv-prod/imagestreamtag.yaml
slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml
user-api/overlays/cnv-prod/imagestreamtag.yaml

Bump up versions of thoth components in prod for release v19.07.2021
https://github.com/thoth-station/thoth-application/issues/1803

Bump up versions of thoth components in prod for release v19.07.2021

---

solver-project-url-job/base/cronjob.yaml
solver-project-url-job/base/imagestream.yaml
solver-project-url-job/base/kustomization.yaml
solver-project-url-job/overlays/test/buildConfig.yaml
solver-project-url-job/overlays/test/cronjob.yaml
solver-project-url-job/overlays/test/imagestreamtag.yaml
solver-project-url-job/overlays/test/job-generate-name.yaml
solver-project-url-job/overlays/test/kustomization.yaml
solver-project-url-job/overlays/test/thoth-notification.yaml

thoth-station/core#286
.yaml file to create cronjob for solver-project-url-job

Solver project url job

---

metrics-exporter/overlays/cnv-prod/kustomization.yaml
metrics-exporter/overlays/cnv-prod/secret-generator.yaml
metrics-exporter/overlays/cnv-prod/secrets.enc.yaml
metrics-exporter/overlays/ocp4-stage/kustomization.yaml
metrics-exporter/overlays/ocp4-stage/secret-generator.yaml
metrics-exporter/overlays/ocp4-stage/secrets.enc.yaml
metrics-exporter/overlays/test/kustomization.yaml
metrics-exporter/overlays/test/secret-generator.yaml
metrics-exporter/overlays/test/secrets.enc.yaml

setup kebehcet github token secrets for metrics-exporter
Secret is needed for metrics-expoeter > v0.18.0
this would have any effect on current deployment.

setup kebehcet github token secrets for metrics-exporter

---

metrics-exporter/base/deploymentconfig.yaml
metrics-exporter/overlays/cnv-prod/deploymentconfig.yaml
metrics-exporter/overlays/cnv-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump up version for metrics-exporter

Bump up version for metrics-exporter

---

mi-scheduler/base/argo-workflows/mi-workflow-template.yaml
mi-scheduler/base/openshift-templates/mi-run-template.yaml

Related to https://github.com/thoth-station/common/pull/1193
Add new merge path variable to mi templates

Add merge path to openshift and argo templates

---

management-api/overlays/cnv-prod/imagestreamtag.yaml
management-api/overlays/ocp4-stage/imagestreamtag.yaml
management-api/overlays/test/imagestreamtag.yaml

Bump up version for management-api
Related-to: 
https://github.com/thoth-station/thoth-application/issues/1792
https://github.com/thoth-station/thoth-application/issues/1849
This would have alembic version update.

Bump up version for management-api

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/prescriptions/issues/85

Bump prescriptions to v0.5.1 in stage environment

---

core/overlays/ocp4-stage/graph-stage/postgresql.yaml

upgrade the db cpu resource limit for stage

upgrade the db cpu resource limit for stage

---

pulp-opf/overlays/zero-prod/kustomization.yaml
pulp-opf/overlays/zero-prod/routes.yaml

setup pulp tls route for serving
Related-to: https://github.com/operate-first/support/issues/353#issuecomment-899516224
This would be added to the argocd , to keep it automated.

setup pulp tls route for serving

---

kebechet/overlays/cnv-prod/imagestreamtag.yaml
management-api/overlays/cnv-prod/imagestreamtag.yaml
mi-scheduler/overlays/cnv-prod/imagestreamtag.yaml
mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
mi-scheduler/overlays/test/imagestreamtag.yaml

Bump up the images based on the version update v2021.08.16
Related-to: https://github.com/thoth-station/thoth-application/issues/1872
Update based on the release.

Bump up the images based on the version update v2021.08.16

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml

bump investigator to v0.14.3 to fix bug

---

integration-tests/overlays/cnv-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/test/imagestreamtag.yaml
prow/overlays/cnv-prod/config.yaml

Bump integration-tests to v0.8.4

---

graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/graph-refresh-job/issues/634

Bump graph-refresh to v0.3.13 in stage

---

kebechet/overlays/cnv-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Fixes: https://github.com/thoth-station/ps-nlp/issues/150

Bump kebechet to fix issue

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/prescriptions/pull/109
Depends-On: https://github.com/thoth-station/thoth-application/pull/1883

Bump prescriptions to v0.6.0 in stage environment

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml

Bump workflow-helpers to v0.8.8 to allow graph update and fix kebechet administrator

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

bump slo-reporter to v0.16.2 to fix enum issues

---

solver/base/argo-workflows/solver-template.yaml

I've spotted few OOM, let's increase memory for this branch of solver workflow.

Add more memory for high resources solver branch

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/issues/2063

Bump adviser to v0.40.0 in stage environment

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/prescriptions/pull/117

Bump prescriptions to v0.7.0 in stage environment

---

slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/zero-prod-ocp4-stage/imagestreamtag.yaml

Bump slo-reporter to v0.17.0

---

core/overlays/cnv-prod/graph-prod/postgresql.yaml

Fixes: https://github.com/thoth-station/thoth-application/issues/1907
Fixes: https://github.com/thoth-station/thoth-application/issues/1908

increate memory for database in prod

---

core/overlays/cnv-prod/common/configmaps.yaml
core/overlays/ocp4-stage/common/configmaps.yaml
core/overlays/quicklab/configmaps.yaml
core/overlays/test/configmaps.yaml
core/overlays/zero-test/configmaps.yaml
package-releases/base/cronjob.yaml
package-releases/overlays/cnv-prod/cronjob.yaml

Related: https://github.com/thoth-station/thoth-application/issues/1822

Remove only-if-package-seen configuration option

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml

fix kebechet administrator workflow in prod

---

investigator/overlays/ocp4-stage/deploymentconfig.yaml

Do not schedule kebechet admin in stage

---

core/overlays/cnv-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
investigator/overlays/test/deploymentconfig.yaml

Fix investigator triggering adviser v5

---

investigator/overlays/ocp4-stage/kustomization.yaml

Enable patch for investigator stage

---

grafana-dashboard/overlays/cnv-prod/thoth-kafka-argo-metrics.json
grafana-dashboard/overlays/cnv-prod/thoth-knowledge-graph-content-metrics.json
grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json

Update dashboards in prod

---

kebechet/base/openshift-templates/kebechet-administrator.yaml

Many kebechet administrator are running, but they are just going to send messages.

Reduce TTL for kebechet administrator

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/issues/2073

Bump adviser to v0.41.0 in stage environment

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh.yaml
prescriptions-refresh-job/base/imagestream.yaml
prescriptions-refresh-job/base/kustomization.yaml
prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml
prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
prescriptions-refresh-job/overlays/ocp4-stage/job-generate-name.yaml
prescriptions-refresh-job/overlays/ocp4-stage/kustomization.yaml
prescriptions-refresh-job/overlays/ocp4-stage/put-into-middletier-namespace.yaml
prescriptions-refresh-job/overlays/ocp4-stage/thoth-notification.yaml
prescriptions-refresh-job/overlays/test/cronworkflow.yaml
prescriptions-refresh-job/overlays/test/imagestreamtag.yaml
prescriptions-refresh-job/overlays/test/job-generate-name.yaml
prescriptions-refresh-job/overlays/test/kustomization.yaml
prescriptions-refresh-job/overlays/test/thoth-notification.yaml
prescriptions-refresh-job/overlays/zero-prod/cronworkflow.yaml
prescriptions-refresh-job/overlays/zero-prod/imagestreamtag.yaml
prescriptions-refresh-job/overlays/zero-prod/job-generate-name.yaml
prescriptions-refresh-job/overlays/zero-prod/kustomization.yaml
prescriptions-refresh-job/overlays/zero-prod/put-into-middletier-namespace.yaml
prescriptions-refresh-job/overlays/zero-prod/thoth-notification.yaml

Introduce [prescriptions-refresh](https://github.com/thoth-station/prescriptions-refresh-job) CronWorkflow.

Add manifests needed for prescriptions-refresh

---

grafana-dashboard/overlays/cnv-prod/thoth-sli-slo.json

Fix panels colours behaviour in Grafana dashboard

---

prow/base/statusreconciler.yaml
prow/base/tide.yaml
prow/overlays/smaug/config.yaml
prow/overlays/smaug/secrets.enc.yaml

update the prow ceph bucket for the instance

update the prow ceph bucket for the instance

---

prow/base/statusreconciler.yaml
prow/base/tide.yaml
prow/overlays/smaug/config.yaml
prow/overlays/smaug/secrets.enc.yaml

Adjust the prow ceph bucket

---

package-releases/base/cronjob.yaml

Related: https://github.com/thoth-station/thoth-application/issues/1895

Increase activeDeadlineSeconds for package-releases

---

mi-scheduler/overlays/test/cronjob.yaml

None
Enable cronjobs in `test` to be active

Unsuspend cronjobs

---

prow/overlays/smaug/config.yaml

Add tide to AICoE tutorials repo

---

sesheta-srcops/overlays/smaug/configmaps.yaml
sesheta-srcops/overlays/smaug/kustomization.yaml
sesheta-srcops/overlays/smaug/secret-generator.yaml
sesheta-srcops/overlays/smaug/secrets.enc.yaml

add sesheta-srcops secrets

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/pull/2102

Bump adviser to v0.44.0 in stage environment

---

adviser/base/argo-workflows/advise.yaml
adviser/base/openshift-templates/adviser.yaml

Related: https://github.com/thoth-station/adviser/issues/2096

Propagate information about authenticated advise to adviser

---

graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/graph-refresh-job/issues/644

Bump graph-refresh in stage to v0.3.15

---

core/overlays/moc-prod/common/secrets.enc.yaml

patch the moc secrets for the new contributors

patch the moc secrets for the new contributors

---

advise-reporter/base/cronjob.yaml
advise-reporter/overlays/aws-prod/cronjob.yaml
advise-reporter/overlays/moc-prod/cronjob.yaml
advise-reporter/overlays/test/cronjob.yaml
adviser/base/argo-workflows/advise.yaml
adviser/base/argo-workflows/dependency-monkey.yaml
adviser/base/argo-workflows/kebechet-run-results.yaml
adviser/base/argo-workflows/parse-adviser-output.yaml
adviser/base/argo-workflows/parse-provenance-checker-output.yaml
adviser/base/argo-workflows/provenance-check.yaml
adviser/base/argo-workflows/trigger-integration.yaml
management-api/base/deploymentconfig.yaml

Patch the service with annotations to refer imagestreams
Related-to: https://github.com/thoth-station/thoth-application/issues/1996
Testing if the annotation would work for application.

Patch the service with annotations to refer imagestreams

---

investigator/overlays/aws-prod/job-generate-name.yaml
investigator/overlays/aws-prod/kustomization.yaml
investigator/overlays/aws-prod/thoth-notification.yaml
investigator/overlays/moc-prod/job-generate-name.yaml
investigator/overlays/moc-prod/kustomization.yaml
investigator/overlays/moc-prod/thoth-notification.yaml
investigator/overlays/ocp4-stage/job-generate-name.yaml
investigator/overlays/ocp4-stage/kustomization.yaml
investigator/overlays/ocp4-stage/thoth-notification.yaml
investigator/overlays/rick-test/job-generate-name.yaml
investigator/overlays/rick-test/kustomization.yaml
investigator/overlays/rick-test/thoth-notification.yaml
investigator/overlays/test/job-generate-name.yaml
investigator/overlays/test/kustomization.yaml
investigator/overlays/test/thoth-notification.yaml

fix the chat-notification resolve for newer kustomize
Related-to: #2005 
This would remove the generateName from the Kustomize

fix the chat-notification resolve for newer kustomize

---

adviser/base/argo-workflows/advise.yaml
adviser/base/configmap.yaml
adviser/base/kustomization.yaml
adviser/overlays/aws-prod/configmap.yaml
adviser/overlays/aws-prod/kustomization.yaml
adviser/overlays/moc-prod/configmap.yaml
adviser/overlays/moc-prod/kustomization.yaml
adviser/overlays/ocp4-stage/configmap.yaml
adviser/overlays/ocp4-stage/kustomization.yaml
adviser/overlays/test/configmap.yaml
adviser/overlays/test/kustomization.yaml

Fixes: https://github.com/thoth-station/thoth-application/issues/1086

Create adviser configmap with all the configuration options

---

.pre-commit-config.yaml

use https based url in the pre-commit
Related-to: https://github.com/thoth-station/thoth-application/issues/2111

use https based url in the pre-commit

---

monitoring/overlays/moc-prod/alerting-rules.yaml

Simplify alerting rule

---

core/base/configmaps.yaml
thoth-repo-init/base/argo-workflows/thoth-repo-init.yaml
thoth-repo-init/base/imagestream.yaml
thoth-repo-init/base/kustomization.yaml
thoth-repo-init/base/openshift-templates/thoth-repo-init.yaml
thoth-repo-init/overlays/test/imagestreamtag.yaml
thoth-repo-init/overlays/test/kustomization.yaml
thoth-repo-init/overlays/test/thoth-notification.yaml

Depends on #1964 
I have added a new template for running advise and adding `.thoth.yaml` file to uninitialized repositories. This may not be the best place for this in `thoth-application` please let me know if you feel it is better of living somewhere else.

create new workflow for repo initialization

---

grafana-dashboard/overlays/aws-prod/argocd.json
grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
grafana-dashboard/overlays/aws-prod/thoth-postgresql-metrics.json
grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json
grafana-dashboard/overlays/aws-prod/thoth-user-api-metrics.json
grafana-dashboard/overlays/aws-prod/thoth-workflow-controllers-metrics.json
grafana-dashboard/overlays/moc-prod/argocd.json
grafana-dashboard/overlays/moc-prod/thoth-kafka-argo-metrics.json
grafana-dashboard/overlays/moc-prod/thoth-knowledge-graph-content-metrics.json
grafana-dashboard/overlays/moc-prod/thoth-postgresql-metrics.json
grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json
grafana-dashboard/overlays/moc-prod/thoth-user-api-metrics.json
grafana-dashboard/overlays/moc-prod/thoth-workflow-controllers-metrics.json

Modifying [Thoth issue 2029](https://github.com/thoth-station/thoth-application/issues/2029) but forgot to remove the ports when I updated the dashboards

removing ports

---

revsolver/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/thoth-application/issues/2091

Bump revsolver to v0.2.10 in stage

---

slo-reporter/overlays/moc-prod-ocp4-stage/configmap.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml

patch the smaug secrets for slo-reportor
fixes: https://github.com/thoth-station/thoth-application/issues/1843

patch the smaug secrets for slo-reportor

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/user-api/issues/1501

Bump user-api to v0.27.2 in stage environment

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/thoth-application/issues/2091
Related: https://github.com/thoth-station/prescriptions/issues/18546
Related: https://github.com/thoth-station/prescriptions/pull/18547
Related: https://github.com/thoth-station/adviser/issues/2159

Bump adviser to v0.47.0 in stage environment

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh.yaml

Add task related to CVE warning aggration.

Add cve-warning prescriptions-refresh task

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Bump user-api stage to v0.28.0

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Bump up the kebechet version to v1.6.2

Bump up the kebechet version to v1.6.2

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Bump up the kebechet version to v1.6.3
Kebechet is breaking currently, this would fix it.

Bump up the kebechet version to v1.6.3

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Bump up the kebechet version to v1.6.5

Bump up the kebechet version to v1.6.5

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Testing https://github.com/thoth-station/thamos/pull/945

bump user-api stage to v0.28.1

---

prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml
user-api/overlays/rick-test/imagestreamtag.yaml

Bump up the images based on the version update v2021.11.22
Fixes: #2137

Bump up the images based on the version update v2021.11.22

---

grafana-dashboard/overlays/moc-prod/thoth-sli-slo.json

Fix dashboard metrics labels

---

slo-reporter/overlays/moc-prod-ocp4-stage/configmap.yaml

Adjust SLO-reporter CM

---

slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml

set up the smaug thanos token for slo-reportor
Fixes: https://github.com/thoth-station/thoth-application/issues/920
Related-to: https://github.com/thoth-station/thoth-application/issues/2142

set up the smaug thanos token for slo-reportor

---

adviser/overlays/aws-prod/imagestreamtag.yaml
adviser/overlays/moc-prod/imagestreamtag.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml
user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml
user-api/overlays/rick-test/imagestreamtag.yaml

Bump up the images based on the version update v2021.12.06
Related-to: https://github.com/thoth-station/thoth-application/issues/2158

Bump up the images based on the version update v2021.12.06

---

slo-reporter/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump SLO reporter to v0.19.0

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh.yaml

Add all the PyPI-related handlers to prescriptions-refresh cronjob.

Add PyPI specific handlers for prescriptions-refresh

---

prow/base/statusreconciler.yaml
prow/base/tide.yaml
prow/overlays/smaug/config.yaml
prow/overlays/smaug/secrets.enc.yaml

Patch prow instance with the s3 connection from smaug cluster
Related-to: https://github.com/thoth-station/thoth-application/issues/2196
Related-to: https://github.com/operate-first/support/issues/490

Patch prow instance with the s3 connection from smaug cluster

---

core/overlays/moc-prod/common/secrets.enc.yaml

Patch moc prod ceph bucket in smaug cluster

Patch moc prod ceph bucket in smaug cluster

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml

See: https://github.com/thoth-station/prescriptions-refresh-job/pull/89

Prescriptions refresh PyPI artifact size requires connection to the database

---

adviser/base/argo-workflows/dependency-monkey.yaml

```
Options --pipeline/--prescription are disjoint
```

Explicit pipeline configuration and prescritpions are disjoint

---

kebechet/base/openshift-templates/kebechet.yaml

Fix the kebechet slug var in the kebechet yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/2205

Fix the kebechet slug var in the kebechet yaml

---

kebechet/base/openshift-templates/kebechet.yaml

Revert the kebechet update installation due errors
Related-to: https://github.com/thoth-station/kebechet/issues/942

Revert the kebechet update installation due errors

---

prescriptions-refresh-job/base/kustomization.yaml

Patch the prescriptions refresh job for deployment
Fixes: https://github.com/thoth-station/thoth-application/issues/2208

Patch the prescriptions refresh job for deployment

---

core/overlays/moc-prod/common/secrets.enc.yaml

Patch the smaug cluster kafka certs due to updates
Fixes: https://github.com/operate-first/apps/issues/1464

Patch the smaug cluster kafka certs due to updates

---

adviser/overlays/aws-prod/imagestreamtag.yaml
adviser/overlays/moc-prod/imagestreamtag.yaml
mi-scheduler/overlays/moc-prod/imagestreamtag.yaml
mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
mi-scheduler/overlays/rick-test/imagestreamtag.yaml
package-extract/overlays/aws-prod/imagestreamtag.yaml
package-extract/overlays/moc-prod/imagestreamtag.yaml
prescriptions-refresh-job/overlays/moc/imagestreamtag.yaml
security-indicators/overlays/aws-prod/imagestreamtag.yaml
security-indicators/overlays/moc-prod/imagestreamtag.yaml
security-indicators/overlays/ocp4-stage/imagestreamtag.yaml
user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml
user-api/overlays/rick-test/imagestreamtag.yaml

Bump up the images based on the version update v2021.12.20
Related-to: https://github.com/thoth-station/thoth-application/issues/2183

Bump up the images based on the version update v2021.12.20

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/storages/pull/2515

Bump user-api to v0.30.0 in stage environment

---

management-api/overlays/ocp4-stage/imagestreamtag.yaml

Bump up version for managment-api

Bump up version for managment-api

---

nepthys/base/cronjob.yaml

Bump up the resources for nepthys

Bump up the resources for nepthys

---

solver-error-classifier-job/base/cronjob.yaml
solver-error-classifier-job/base/imagestream.yaml
solver-error-classifier-job/base/kustomization.yaml
solver-error-classifier-job/overlays/test/buildConfig.yaml
solver-error-classifier-job/overlays/test/cronjob.yaml
solver-error-classifier-job/overlays/test/imagestreamtag.yaml
solver-error-classifier-job/overlays/test/kustomization.yaml
solver-error-classifier-job/overlays/test/thoth-notification.yaml

thoth-station/solver-error-classifier#5
cronjob, overlays and config yaml files for running the solver error classifier job

Solver error classifier yaml files

---

adviser/base/configmap.yaml
adviser/base/openshift-templates/adviser.yaml
adviser/overlays/aws-prod/configmap.yaml
adviser/overlays/moc-prod/configmap.yaml
adviser/overlays/ocp4-stage/configmap.yaml

Configure links to Thoth search UI based on deployment used.

Adjust links to Thoth search UI based on deployment

---

adviser/base/argo-workflows/advise.yaml
adviser/base/openshift-templates/adviser.yaml

Place adviser search URL configuration to environment section

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Bump adviser to v0.50.0 in stage environment

Bump adviser to v0.50.0 in stage environment

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Bump user-api to v0.33.0 in stage environment.

Bump user-api to v0.33.0 in stage

---

core/overlays/ocp4-stage/common/imagestreamtags.yaml

Bump workflow helpers to update schema in stage

---

adviser/base/argo-workflows/kebechet-run-results.yaml

Related-To: https://github.com/thoth-station/core/issues/322

Add metrics to kebechet-run-results task

---

adviser/overlays/aws-prod/imagestreamtag.yaml
adviser/overlays/moc-prod/imagestreamtag.yaml
amun/overlays/aws-prod/amun-api/imagestreamtag.yaml
amun/overlays/moc-prod/amun-api/imagestreamtag.yaml
core/overlays/aws-prod/common/imagestreamtags.yaml
core/overlays/moc-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
cve-update/overlays/aws-prod/imagestreamtag.yaml
cve-update/overlays/moc-prod/imagestreamtag.yaml
graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
graph-metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
graph-refresh/overlays/aws-prod/imagestreamtag.yaml
graph-refresh/overlays/moc-prod/imagestreamtag.yaml
graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml
management-api/overlays/aws-prod/imagestreamtag.yaml
management-api/overlays/moc-prod/imagestreamtag.yaml
package-releases/overlays/aws-prod/imagestreamtag.yaml
package-releases/overlays/moc-prod/imagestreamtag.yaml

Bump up the images based on the version update v2022.01.17
Related-to: https://github.com/thoth-station/thoth-application/issues/2238
Release version for the first completion.

Bump up the images based on the version update v2022.01.17

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Bump up kebechet for fixing the release issue
Related-to: https://github.com/thoth-station/kebechet/issues/976

Bump up kebechet for fixing the release issue

---

pulp-metrics-exporter/README.md
pulp-metrics-exporter/application-stage.yaml
pulp-metrics-exporter/base/configmap.yaml
pulp-metrics-exporter/base/deploymentconfig.yaml
pulp-metrics-exporter/base/imagestream.yaml
pulp-metrics-exporter/base/kustomization.yaml
pulp-metrics-exporter/base/route.yaml
pulp-metrics-exporter/base/secret.yaml
pulp-metrics-exporter/base/service.yaml
pulp-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
pulp-metrics-exporter/overlays/ocp4-stage/kustomization.yaml
pulp-metrics-exporter/overlays/ocp4-stage/secret-generator.yaml
pulp-metrics-exporter/overlays/ocp4-stage/thoth-notification.yaml

Related: https://github.com/thoth-station/pulp-metrics-exporter

Deploy pulp-metrics-exporter

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Bump up kebechet v1.7.3 for fixing the release issue

Bump up kebechet v1.7.3 for fixing the release issue

---

pulp-metrics-exporter/base/kustomization.yaml
pulp-metrics-exporter/base/secret.yaml
pulp-metrics-exporter/overlays/ocp4-stage/secrets.enc.yaml

Include the secrets required for the pulp-metrics-exporter

Include the secrets required for the pulp-metrics-exporter

---

pulp-pypi-sync-job/overlays/ocp4-stage/imagestreamtag.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/kustomization.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/secret-generator.yaml
pulp-pypi-sync-job/overlays/ocp4-stage/secrets.enc.yaml
pulp-pypi-sync-job/overlays/test/imagestreamtag.yaml
pulp-pypi-sync-job/overlays/test/kustomization.yaml
pulp-pypi-sync-job/overlays/test/secret-generator.yaml
pulp-pypi-sync-job/overlays/test/secrets.enc.yaml

Include the secrets required for the pulp-sync-job
Related-to: https://github.com/thoth-station/thoth-application/issues/2269

Include the secrets required for the pulp-sync-job

---

docs/secret_management.md

I wanted to refer someone to this document but there were some typos and
confusing instructions in the GPG Keys section. I've tried to clean things
up.

Clarify process for generating and publishing GPG keys

---

core/overlays/aws-prod/common/secrets.enc.yaml
core/overlays/moc-prod/common/secrets.enc.yaml
core/overlays/ocp4-stage/common/secrets.enc.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml
slo-reporter/overlays/ocp4-stage/secrets.enc.yaml

sync up secret based on new gpg key addition
Related-to: https://github.com/thoth-station/thoth-application/issues/2259#issuecomment-1024021669

sync up secret based on new gpg key addition

---

slo-reporter/base/cronjob.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/configmap.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/cronjob.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/kustomization.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/secret-generator.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/secrets.enc.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/thoth-notification.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/cronjob.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml

Introduce slo-reporter for prod and update the cronjob for rest
Related-to: https://github.com/thoth-station/thoth-application/issues/2259

Introduce slo-reporter for prod and update the cronjob for rest

---

monitoring/overlays/aws-prod/alerting-rules.yaml
monitoring/overlays/moc-prod/alerting-rules.yaml

Fixes: https://github.com/thoth-station/thoth-application/issues/1914

Fix labels in alarms

---

pulp-metrics-exporter/overlays/ocp4-stage/secrets.enc.yaml

fix the pulp metrics exporter secrets
This would fix the authentication issue happening in the pulp metrics exporter.

fix the pulp metrics exporter secrets

---

slo-reporter/overlays/aws-prod-ocp4-stage/configmap.yaml

Do not use port in instance name for Prometheus

---

monitoring/overlays/aws-prod/alerting-rules.yaml
monitoring/overlays/moc-prod/alerting-rules.yaml

Related-To: https://github.com/thoth-station/thoth-application/issues/854

Add pg dump missing alarm

---

metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump metrics exporter to v0.20.2 in stage

---

monitoring/overlays/aws-prod/alerting-rules.yaml
monitoring/overlays/moc-prod/alerting-rules.yaml

Related-To: https://github.com/thoth-station/thoth-application/issues/854

Add bloat table or index alerts for prod

---

grafana-dashboard/overlays/aws-prod/thoth-kafka-argo-metrics.json
grafana-dashboard/overlays/aws-prod/thoth-knowledge-graph-content-metrics.json
grafana-dashboard/overlays/aws-prod/thoth-service-metrics.json
grafana-dashboard/overlays/aws-prod/thoth-sli-slo.json

Fix Grafana dashboards in prod

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Fixes: https://github.com/thoth-station/user-api/issues/1645

Bump user-api to v0.34.1 in stage

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/storages/pull/2578

Bump user-api to v0.34.2 in stage

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Related to https://github.com/thoth-station/user-api/pull/1657#issuecomment-1029813917

Bump user-api to v0.34.3 in stage

---

user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml

Related to https://github.com/thoth-station/user-api/pull/1657#issuecomment-1029813917

Bump user-api to v0.34.3 in prod

---

grafana-dashboard/overlays/moc-prod/pulp-metrics.json

Related-To: https://github.com/thoth-station/pulp-metrics-exporter/issues/17

Save Pulp Grafana Dashboard

---

prow/overlays/smaug/plugins.yaml

Override doesn't work in open-services-group. This should fix it.
https://github.com/open-services-group/community/pull/49#issuecomment-1032983342

feat(prow): Enable override in open-services-group

---

solver/base/imagestreams.yaml
solver/overlays/aws-prod/imagestreamtag.yaml
solver/overlays/moc-prod/imagestreamtag.yaml
solver/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/test/imagestreamtag.yaml

Remove solvers that are no longer used from deployment.

Remove old solvers from deployment manifests

---

document-sync-job/base/cronjob.yaml

Related: https://github.com/thoth-station/document-sync-job/pull/15/
Let's sync only recent documents to reduce CPU time occupied by the job.

Perform syncs of documents that are recent

---

prow/base/statusreconciler.yaml
prow/base/tide.yaml
prow/overlays/smaug/config.yaml
prow/overlays/smaug/secrets.enc.yaml

Fix the prow with Thoth OBC from rick cluster
Related-to: https://github.com/operate-first/operations/issues/454
We are switching to temporary bucket of thoth from rick cluster.

Fix the prow with Thoth OBC from rick cluster

---

integration-tests/base/cronjob.yaml

Integration tests failed on OOM.

Fix integration-tests OOM

---

prow/overlays/smaug/config.yaml

bounce integration test within prow config

---

prow/base/statusreconciler.yaml
prow/base/tide.yaml
prow/overlays/smaug/config.yaml
prow/overlays/smaug/secrets.enc.yaml

Prow storage is set to the respective cluster
Related-to: https://github.com/operate-first/operations/issues/454
Storage in smaug cluster, seems to be stable, switching back to smaug stroage

:hatched_chick: Prow storage is set to the respective cluster

---

solver/overlays/test/imagestreamtag.yaml

The pipeline failed to push changes as a different overlay pushed commit first which lead to refusing commit.
```
+ git config --local user.email goern+sesheta@redhat.com
+ git config --local user.name sesheta
+ git status
On branch master
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   solver/overlays/test/imagestreamtag.yaml
no changes added to commit (use "git add" and/or "git commit -a")
+ git add .
+ git commit -m ':ship: Deploy the Tag v1.11.2 for solver'
[master 32f90e25] :ship: Deploy the Tag v1.11.2 for solver
1 file changed, 41 insertions(+), 41 deletions(-)
rewrite solver/overlays/test/imagestreamtag.yaml …
```

Bump solver-rhel-8-py38 to v1.11.2 in test environment

---

solver/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/integration-tests/issues/259
Related: https://github.com/thoth-station/solver/issues/5146

Bump solvers to v1.11.2 in stage

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml

Related: #2281 
Le'ts increase memory required to run prescriptions-refresh cronjobs.

Increase memory for prescriptions-refresh jobs

---

adviser/base/argo-workflows/advise.yaml

Related: https://github.com/thoth-station/adviser/pull/2280
Enable memory optimizer in adviser.

Set up adviser memory optimizer

---

prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/prescriptions-refresh-job/issues/124

Bump prescriptions-refresh to v0.6.0 in stage

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml

The current deployment fails on OOM.

Increase memory for prescriptions-refresh-pypi

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml

The current deployment fails on OOM.

Increase memory for prescriptions-refresh-pg

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-image-analysis.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pg.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-quay.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-scorecards.yaml

Some jobs were killed as they exceeded deadline.

Increase deadline for prescriptions-refresh jobs

---

prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-gh.yaml
prescriptions-refresh-job/base/argo-workflows/prescriptions-refresh-pypi.yaml
prescriptions-refresh-job/overlays/ocp4-stage/kustomization.yaml
prescriptions-refresh-job/overlays/test/kustomization.yaml

We have run only the very first template.

Run all the steps in prescriptions-refresh PyPI workflow

---

integration-tests/overlays/ocp4-stage/imagestreamtag.yaml

Bump integration-tests in stage.

Bump integration-tests to v0.9.3 in stage environment

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/pull/2287

Bump adviser to v0.52.1 in stage environment

---

prow/overlays/smaug/config.yaml
prow/overlays/smaug/plugins.yaml

add os-climate base config/plugins

---

prow/overlays/smaug/config.yaml

#2367 
Updated prow config.yaml to include OS-Climate repos.

update prow config.yaml for os-climate repos

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/adviser/pull/2294

Bump adviser to v0.52.2 in stage

---

amun/overlays/aws-prod/amun-api/secrets.enc.yaml
amun/overlays/moc-prod/amun-api/secrets.enc.yaml
amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml

Fix the kafka secrets issue for amun
Related-to: https://github.com/thoth-station/integration-tests/issues/253#issuecomment-1061080342
Kakfa secrets were missing from amun deployment

Fix the kafka secrets issue for amun

---

amun/overlays/aws-prod/amun-api/secrets.enc.yaml
amun/overlays/moc-prod/amun-api/secrets.enc.yaml
amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml

Patch the kafka secrets to amun-inspection namespace
Related-to: https://github.com/thoth-station/integration-tests/issues/253#issuecomment-1061080342

Patch the kafka secrets to amun-inspection namespace

---

integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/integration-tests/pull/293

Bump integration-tests to v0.10.1

---

integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/ocp4-stage/imagestreamtag.yaml

Related to https://github.com/thoth-station/integration-tests/pull/298

Bump integration-tests to v0.11.0

---

core/overlays/moc-prod/middletier-prod/configmaps.yaml
mi-scheduler/overlays/moc-prod/cronjob.yaml
mi-scheduler/overlays/moc-prod/imagestreamtag.yaml
mi-scheduler/overlays/moc-prod/kustomization.yaml
mi-scheduler/overlays/moc-prod/role-binding.yaml
mi-scheduler/overlays/ocp4-stage/imagestreamtag.yaml
mi-scheduler/overlays/ocp4-stage/kustomization.yaml
mi-scheduler/overlays/ocp4-stage/role-binding.yaml
mi-scheduler/overlays/test/imagestreamtag.yaml

Patch mi prod deployment in smaug cluster
Patched some of resources to make the mi function properly in stage and prod.
This would allow mi to use the vast resource in smaug cluster, instead of waiting on test cluster.

Patch mi prod deployment in smaug cluster

---

mi-scheduler/base/job.yaml

Related to https://github.com/thoth-station/thoth-application/issues/2333
This is a momentary fix (specs) for the missing apiversion update.

Add job specs to the mi-scheduler

---

advise-reporter/overlays/aws-prod/imagestreamtag.yaml
advise-reporter/overlays/moc-prod/imagestreamtag.yaml
advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml

Introduce patch, due to https://github.com/thoth-station/storages/pull/2609

bump reporter to v0.11.1

---

adviser/overlays/aws-prod/imagestreamtag.yaml
adviser/overlays/moc-prod/imagestreamtag.yaml

Closes: https://github.com/thoth-station/thamos/issues/1082

Bump adviser to v0.53.0 in prod deployments

---

grafana-dashboard/base/thoth-postgresql-metrics.json

Show date last db backup

---

user-api/base/deploymentconfig.yaml
user-api/overlays/aws-prod/deploymentconfig.yaml
user-api/overlays/moc-prod/deploymentconfig.yaml
user-api/overlays/rick-test/deploymentconfig.yaml

Related to https://github.com/thoth-station/user-api/issues/1721

Propagate URL to Thoth Search UI in deployments

---

user-api/base/deploymentconfig.yaml
user-api/overlays/aws-prod/deploymentconfig.yaml
user-api/overlays/moc-prod/deploymentconfig.yaml
user-api/overlays/rick-test/deploymentconfig.yaml

Fix user-api Thoth Search UI environment variable in deployments

---

investigator/overlays/ocp4-stage/deploymentconfig.yaml

set the pending workflow limit for the investigator
set this to fix the issue of workflow crossing beyond the workflow limits
link: https://chat.google.com/room/AAAAVjnVXFk/S4bPm3gXGdQ

set the pending workflow limit for the investigator

---

amun/overlays/moc-prod/amun-api/configmaps.yaml
amun/overlays/moc-prod/amun-api/secrets.enc.yaml

patch up the moc-prod s3 for amun
Fix the amun connection to s3 for moc-prod environment

patch up the moc-prod s3 for amun

---

amun/overlays/aws-prod/amun-api/argo-workflows/sync-template.yaml
amun/overlays/aws-prod/amun-api/configmaps.yaml
amun/overlays/aws-prod/amun-api/kustomization.yaml
amun/overlays/aws-prod/amun-api/secrets.enc.yaml
amun/overlays/moc-prod/amun-api/argo-workflows/sync-template.yaml
amun/overlays/moc-prod/amun-api/configmaps.yaml
amun/overlays/moc-prod/amun-api/kustomization.yaml
amun/overlays/moc-prod/amun-api/secrets.enc.yaml
amun/overlays/ocp4-stage/amun-api/argo-workflows/sync-template.yaml
amun/overlays/ocp4-stage/amun-api/configmaps.yaml
amun/overlays/ocp4-stage/amun-api/kustomization.yaml
amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml

include the graph-sync template for the dm
Failing dm in integration-tests
This would fix the dm graph-sync step.
setting up graph-sync required cm and secrets.

include the graph-sync template for the dm

---

amun/overlays/aws-prod/amun-inspection/configmaps.yaml
amun/overlays/moc-prod/amun-inspection/configmaps.yaml
amun/overlays/ocp4-stage/amun-inspection/configmaps.yaml

Set kafka configmap for the amun-inspection
amun workflow require kafka cm for sending messages

Set kafka configmap for the amun-inspection

---

document-sync-job/overlays/ocp4-stage/cronjob.yaml

Related-to: https://github.com/thoth-station/thoth-application/issues/2475
switch on the document-sync in stage

switch on the document-sync in stage

---

graph-sync/overlays/aws-prod/middletier/kustomization.yaml
graph-sync/overlays/moc-prod/middletier/kustomization.yaml

Fixed Image patch to use correct ns in prod

Fixed Image patch to use correct ns in prod

---

amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
amun/overlays/test/secrets.enc.yaml
core/overlays/ocp4-stage/common/secrets.enc.yaml
core/overlays/test/secrets.enc.yaml

Upgrade the kafka secrets for the stage deployments
Related-to: https://github.com/thoth-station/thoth-application/issues/2484

Upgrade the kafka secrets for the stage deployments

---

amun/overlays/ocp4-stage/amun-api/kustomization.yaml

Fix the stage deployment of dm graph-sync
Fixes: https://github.com/thoth-station/thoth-application/issues/2488

Fix the stage deployment of dm graph-sync

---

amun/overlays/aws-prod/amun-api/kustomization.yaml
amun/overlays/moc-prod/amun-api/kustomization.yaml
amun/overlays/ocp4-stage/amun-api/kustomization.yaml

Fix the configmap in amun-api
Fixes: https://github.com/thoth-station/thoth-application/issues/2491

Fix the configmap in amun-api

---

amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml

Related: https://github.com/thoth-station/amun-api/pull/661

Bump Amun API to v0.10.2 in stage environment

---

amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml

Related: https://github.com/thoth-station/amun-api/issues/672

Bump Amun API to v0.10.4 in stage

---

mi-scheduler/overlays/test/imagestreamtag.yaml

SSIA
Related to https://github.com/thoth-station/core/issues/322

Update mi to 2.10.7 and mi-scheduler to 1.7.5

---

integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/ocp4-stage/imagestreamtag.yaml

This should fix `count` and `limit` in queries.

Bump integration-tests to v0.11.1

---

amun/overlays/ocp4-stage/amun-api/imagestreamtag.yaml

Related: https://github.com/thoth-station/amun-api/issues/676

Bump Amun API to v0.10.5

---

.prow.yaml

Update pre-commit image tag

---

mi-scheduler/overlays/test/imagestreamtag.yaml

Update mi-scheduler to v1.7.6

---

amun/overlays/aws-prod/amun-api/imagestreamtag.yaml
amun/overlays/moc-prod/amun-api/imagestreamtag.yaml
core/overlays/aws-prod/common/imagestreamtags.yaml
core/overlays/moc-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
integration-tests/overlays/aws-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
management-api/overlays/aws-prod/imagestreamtag.yaml
management-api/overlays/moc-prod/imagestreamtag.yaml
user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml

Bump up the images based on the version update v2022.04.18
Related-to: https://github.com/thoth-station/thoth-application/issues/2472

Bump up the images based on the version update v2022.04.18

---

core/overlays/aws-prod/common/imagestreamtags.yaml
core/overlays/moc-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
graph-sync/overlays/aws-prod/common/imagestreamtag.yaml
graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml

Upgrade workflow-helper and graph-sync for sync fix

Upgrade workflow-helper and graph-sync for sync fix

---

adviser/overlays/ocp4-stage/imagestreamtag.yaml

Related: https://github.com/thoth-station/prescriptions/pull/23487

Bump adviser to v0.55.0 in stage environment

---

solver/overlays/ocp4-stage/imagestreamtag.yaml

Update all solver images to latest version in ocp4-stage.

Update solver images in stage

---

investigator/base/deploymentconfig.yaml
investigator/overlays/aws-prod/deploymentconfig.yaml
investigator/overlays/moc-prod/deploymentconfig.yaml
investigator/overlays/ocp4-stage/deploymentconfig.yaml
investigator/overlays/rick-test/deploymentconfig.yaml
investigator/overlays/test/deploymentconfig.yaml
investigator_message_metrics/base/deploymentconfig.yaml
investigator_message_metrics/overlays/aws-prod/deploymentconfig.yaml
investigator_message_metrics/overlays/moc-prod/deploymentconfig.yaml
investigator_message_metrics/overlays/test/deploymentconfig.yaml

Enable auto offset reset to latest for resolving offset issues
Related-to: #2566

Enable auto offset reset to latest for resolving offset issues

---

core/overlays/aws-prod/common/imagestreamtags.yaml
core/overlays/moc-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
core/overlays/test/imagestreamtags.yaml

Bump up investigator version for fixing kafka consumption
Related-to: #2566

Bump up investigator version for fixing kafka consumption

---

core/overlays/ocp4-stage/common/secrets.enc.yaml

Update the kafka creds for stage cluster
Related-to: #2566

Update the kafka creds for stage cluster

---

slo-reporter/overlays/moc-prod-ocp4-stage/configmap.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/cronjob.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/kustomization.yaml

Adjusted slo-reporter config for moc run to use its own config

Adjusted slo-reporter config for moc run to use its own config

---

adviser/overlays/aws-prod/imagestreamtag.yaml
adviser/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml
user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml

Bump up the images based on the version update v2022.05.30
Related-to: https://github.com/thoth-station/thoth-application/issues/2521

Bump up the images based on the version update v2022.05.30

---

prow/overlays/smaug/config.yaml

feat: Disable branch protection on probot-extensions repo

---

core/overlays/test/secrets.enc.yaml

Fix the kafka connection of ocp4 test

Fix the kafka connection of ocp4 test

---

adviser/overlays/aws-prod/imagestreamtag.yaml
adviser/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Bump up version of the updated component in release v2022.06.20
Related-to: https://github.com/thoth-station/thoth-application/issues/2553

Bump up version of the updated component in release v2022.06.20

---

prow/overlays/smaug/config.yaml

feat: Disable branch protection on probot-template repo

---

prow/overlays/smaug/config.yaml

Part of: https://github.com/open-services-group/community/issues/231
~~**Do not merge, migration in progress**~~ Migration complete
/hold

feat: Relocate Probot repositories to Operate First

---

prow/overlays/smaug/config.yaml

include operate first website repo again

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml
management-api/overlays/aws-prod/imagestreamtag.yaml
management-api/overlays/moc-prod/imagestreamtag.yaml
prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/aws-prod/imagestreamtag.yaml
solver/overlays/moc-prod/imagestreamtag.yaml
solver/overlays/test/imagestreamtag.yaml
user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml
user-api/overlays/ocp4-stage/imagestreamtag.yaml

Bump up the versions for the release of v2022.07.11
Fixes: https://github.com/thoth-station/thoth-application/issues/2581

:arrow_up: Bump up the versions for the release of v2022.07.11

---

core/overlays/aws-prod/common/configmaps.yaml
core/overlays/aws-prod/common/secrets.enc.yaml

Update the kafka to stay inline with operate-first

:astonished: Update the kafka to stay inline with operate-first

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Updated the version of kebechet v0.10.2

:arrow_up: Updated the version of kebechet v0.10.2

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Updated the version of kebechet v0.10.3

:arrow_up: Updated the version of kebechet v0.10.3

---

prescriptions-refresh-job/overlays/ocp4-stage/cronworkflow.yaml

Related to https://github.com/thoth-station/thoth-application/pull/2603

Re-enable prescriptions-refresh-job

---

investigator/base/deploymentconfig.yaml
investigator/overlays/aws-prod/deploymentconfig.yaml
investigator/overlays/moc-prod/deploymentconfig.yaml
investigator/overlays/ocp4-stage/deploymentconfig.yaml
investigator/overlays/test/deploymentconfig.yaml

Upgrade the resource CPU for investigator deployment

:arrow_up: Upgrade the resource cpu for investigator deployment

---

investigator/base/deploymentconfig.yaml
investigator/overlays/aws-prod/deploymentconfig.yaml
investigator/overlays/moc-prod/deploymentconfig.yaml
investigator/overlays/ocp4-stage/deploymentconfig.yaml
investigator/overlays/test/deploymentconfig.yaml

Update the memory resource for the investigator

:ant: Update the memory resource for investigator

---

sync-job/base/workflow-template.yaml

part of https://github.com/thoth-station/thoth-application/issues/2533

Add the prometheus gateway to sync job

---

kebechet/overlays/aws-prod/imagestreamtag.yaml
kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Update the kebechet version v1.10.5

Update the kebechet version v1.10.5

---

graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
management-api/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/test/imagestreamtag.yaml

upgrade graph-sync, solver and management-api to fix the solver runs
Related-to: https://github.com/thoth-station/storages/issues/2703

upgrade graph-sync, solver and management-api to fix the solver runs

---

adviser/overlays/aws-prod/imagestreamtag.yaml
adviser/overlays/moc-prod/imagestreamtag.yaml
adviser/overlays/ocp4-stage/imagestreamtag.yaml
core/overlays/aws-prod/common/imagestreamtags.yaml
core/overlays/moc-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
cve-update/overlays/aws-prod/imagestreamtag.yaml
cve-update/overlays/moc-prod/imagestreamtag.yaml
cve-update/overlays/ocp4-stage/imagestreamtag.yaml
graph-backup-job/overlays/aws-prod/imagestreamtag.yaml
graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
graph-refresh/overlays/aws-prod/imagestreamtag.yaml
graph-refresh/overlays/moc-prod/imagestreamtag.yaml
graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
metrics-exporter/overlays/aws-prod/imagestreamtag.yaml
metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
package-releases/overlays/aws-prod/imagestreamtag.yaml
package-releases/overlays/moc-prod/imagestreamtag.yaml
package-releases/overlays/ocp4-stage/imagestreamtag.yaml
user-api/overlays/aws-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml
user-api/overlays/ocp4-stage/imagestreamtag.yaml

Update the components to fix the alerts

Update the components to fix the alerts

---

core/overlays/aws-prod/graph-prod/postgresql.yaml

Lower the limit to give space for other pvc's

Lower the limit to give space for other pvc's

---

advise-reporter/overlays/aws-prod/cronjob.yaml
cve-update/overlays/aws-prod/cronjob.yaml
document-sync-job/overlays/ocp4-stage/cronjob.yaml
graph-backup-job/overlays/aws-prod/cronjob.yaml
graph-metrics-exporter/overlays/aws-prod/cronjob.yaml
integration-tests/overlays/aws-prod-ocp4-stage/cronjob.yaml
slo-reporter/overlays/aws-prod-ocp4-stage/cronjob.yaml

Migration: Turn off cronjob on the balrog cluster
Related-to: https://github.com/thoth-station/thoth-application/issues/2663

:turtle: Migration: Turn off cronjob on the balrog cluster

---

amun/overlays/moc-prod/amun-api/secrets.enc.yaml
amun/overlays/moc-prod/common/configmaps.yaml
core/overlays/moc-prod/common/configmaps.yaml
core/overlays/moc-prod/common/secrets.enc.yaml

Use aws s3 for moc deployments
Related-to: https://github.com/thoth-station/thoth-application/issues/2663

:turtle: Use aws s3 for moc deployments

---

graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
management-api/overlays/moc-prod/imagestreamtag.yaml
prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml
purge-job/overlays/moc-prod/imagestreamtag.yaml
solver/overlays/moc-prod/imagestreamtag.yaml

Bump up version of the updated component in release v2022.10.03
Related-to: https://github.com/thoth-station/thoth-application/issues/2635

:ship: Bump up version of the updated component in release v2022.10.03

---

adviser/base/openshift-templates/adviser.yaml
core/base/argo-workflows/send-webhooks.yaml
core/overlays/moc-prod/backend-prod/configmaps.yaml
core/overlays/moc-prod/middletier-prod/configmaps.yaml

Minor fixes for argo-workflow template send-webhooks

Minor fixes for argo-workflow template send-webhooks

---

core/overlays/moc-prod/backend-prod/kustomization.yaml
core/overlays/moc-prod/middletier-prod/configmaps.yaml
core/overlays/moc-prod/middletier-prod/kustomization.yaml

Patch image ref of send-webhook based on namespace

Patch image ref of send-webhook based on namespace

---

core/overlays/moc-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml

Update the investigator image with latest storages

Update the investigator image with latest storages

---

adviser/base/configmap.yaml
adviser/overlays/moc-prod/configmap.yaml
adviser/overlays/ocp4-stage/configmap.yaml

fixes: https://github.com/thoth-station/thamos/issues/1163
fixed search url

fixed thoth search ur

---

management-api/overlays/moc-prod/imagestreamtag.yaml
management-api/overlays/ocp4-stage/imagestreamtag.yaml

Bump up with version of management-api

Bump up with version of management-api

---

core/overlays/moc-prod/common/secrets.enc.yaml
slo-reporter/overlays/moc-prod-ocp4-stage/secrets.enc.yaml

Update the thanos reader token for slo-reporter
Related-to: https://github.com/thoth-station/thoth-application/issues/2259
The token was expired, updated it with new token.

:lock: Update the thanos reader token for slo-reporter

---

mi-scheduler/overlays/test/imagestreamtag.yaml

Related to https://github.com/thoth-station/thoth-application/pull/2680 but forgot to update test as well

Update mi to 2.12.0 and mi-s to 1.7.7 [test nmspc]

---

grafana-dashboard/base/thoth-kafka-argo-metrics.json
grafana-dashboard/base/thoth-knowledge-graph-content-metrics.json
grafana-dashboard/base/thoth-postgresql-metrics.json
grafana-dashboard/base/thoth-service-metrics.json
grafana-dashboard/base/thoth-sli-slo.json
grafana-dashboard/base/thoth-user-api-metrics.json
grafana-dashboard/base/thoth-workflow-controllers-metrics.json

Updated and removed balrog panels from grafana dashboards
Related-to: https://github.com/thoth-station/thoth-application/issues/2663

:books: Updated and removed balrog panels from grafana dashboards

---

.pre-commit-config.yaml
.thoth.yaml
OWNERS
integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/test/imagestreamtag.yaml
solver/overlays/moc-prod/imagestreamtag.yaml
solver/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/test/imagestreamtag.yaml

Bump the version of integration-tests and solver

:boat: Bump the version of integration-tests and solver

---

graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Bump the version of graph-metrics-exporter

:boat: Bump the version of graph-metrics-exporter

---

prescriptions-refresh-job/overlays/ocp4-stage/imagestreamtag.yaml

/hold
Waiting for https://github.com/thoth-station/prescriptions-refresh-job/pull/200 to be merged.

Bump prescriptions-refresh-job to v0.8.0 in ocp4-stage

---

sefkhet-abwy-chatbot/overlays/moc/imagestreamtag.yaml
sefkhet-abwy/overlays/moc/imagestreamtag.yaml
sefkhet-abwy/overlays/ocp/imagestreamtag.yaml

Upgrade sefkhet abwy image version to v0.23.1

Upgrade sefkhet abwy image version to v0.23.1

---

kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Bump up version of the updated component in release v2022.11.14

:ship: Bump up version of the updated component in release v2022.11.14

---

CHANGELOG.md
version.py

Release of v2022.11.14
Fixes: #2698

:ship: Release of v2022.11.14

---

amun/overlays/test/deploymentconfig.yaml

Fix the amun-api deployment with web concurrency set
Fixes: https://sentry.io/organizations/red-hat-it/issues/3745189549/?environment=ocp-test&project=1298083&query=is%3Aunresolved&referrer=issue-stream

Fix the amun-api deployment with web concurrency set

---

kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

upgrade kebechet for the release fix

upgrade kebechet for the release fix

---

core/overlays/ocp4-stage/backend-stage/kustomization.yaml
core/overlays/ocp4-stage/middletier-stage/kustomization.yaml
core/overlays/test/kustomization.yaml

Fix imagestream issue for workflow-helper

Fix imagestream issue for workflow-helper

---

kebechet/overlays/moc-prod/imagestreamtag.yaml
kebechet/overlays/ocp4-stage/imagestreamtag.yaml

Upgrade kebechet image version to v1.11.2

Upgrade kebechet image version to v1.11.2

---

graph-refresh/overlays/ocp4-stage/cronjob.yaml

Pause the graph-refresh job for sync period to stabilize
Related-to: #2720

:pause_button: Pause the graph-refresh job for sync period to stabilize

---

core/overlays/moc-prod/common/secrets.enc.yaml

Updating the kafka certs for smaug cluster deployment
Related-to: https://github.com/operate-first/support/issues/1187

:face_in_clouds: Updating the kafka certs for smaug cluster deployment

---

graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
solver/overlays/ocp4-stage/imagestreamtag.yaml
solver/overlays/test/imagestreamtag.yaml

Upgrade the graph-sync and solver in stage cluster

:pushpin: Upgrade the graph-sync and solver in stage cluster

---

management-api/overlays/ocp4-stage/imagestreamtag.yaml

Upgrade the management-api in stage cluster
Related-to: https://github.com/thoth-station/storages/issues/2745

:pushpin: Upgrade the management-api in stage cluster

---

metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml

Upgrade the metrics-exporter in stage cluster

:pushpin: Upgrade the metrics-exporter in stage cluster

---

advise-reporter/overlays/ocp4-stage/imagestreamtag.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
cve-update/overlays/ocp4-stage/imagestreamtag.yaml
graph-backup-job/overlays/ocp4-stage/imagestreamtag.yaml
graph-metrics-exporter/overlays/ocp4-stage/imagestreamtag.yaml
graph-refresh/overlays/ocp4-stage/imagestreamtag.yaml
graph-sync/overlays/ocp4-stage/common/imagestreamtag.yaml
user-api/overlays/ocp4-stage/imagestreamtag.yaml

Upgrade the all components using thoth-storages in stage cluster
Fixes the current alerts

:pushpin: Upgrade the all components using thoth-storages in stage cluster

---

user-api/overlays/ocp4-stage/imagestreamtag.yaml

Upgrade user-api in stage cluster for cachemiss error fix

:pushpin: Upgrade user-api in stage cluster for cachemiss error fix

---

advise-reporter/overlays/moc-prod/imagestreamtag.yaml
core/overlays/moc-prod/common/imagestreamtags.yaml
core/overlays/ocp4-stage/common/imagestreamtags.yaml
cve-update/overlays/moc-prod/imagestreamtag.yaml
graph-backup-job/overlays/moc-prod/imagestreamtag.yaml
graph-metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
graph-refresh/overlays/moc-prod/imagestreamtag.yaml
graph-sync/overlays/moc-prod/common/imagestreamtag.yaml
integration-tests/overlays/moc-prod-ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/ocp4-stage/imagestreamtag.yaml
integration-tests/overlays/test/imagestreamtag.yaml
management-api/overlays/moc-prod/imagestreamtag.yaml
metrics-exporter/overlays/moc-prod/imagestreamtag.yaml
solver/overlays/moc-prod/imagestreamtag.yaml
user-api/overlays/moc-prod/imagestreamtag.yaml

Bump up version of the updated component in release v2023.01.23
Related-to: https://github.com/thoth-station/thoth-application/issues/2735

:ship: Bump up version of the updated component in release v2023.01.23

---

amun/overlays/test/deploymentconfig.yaml
graph-backup-job/overlays/test/cronjob.yaml
graph-metrics-exporter/overlays/test/cronjob.yaml
integration-tests/overlays/test/cronjob.yaml
investigator/overlays/test/deployment.yaml
investigator_message_metrics/overlays/test/deploymentconfig.yaml
management-api/overlays/test/kustomization.yaml
metrics-exporter/overlays/test/kustomization.yaml
mi-scheduler/overlays/test/cronjob.yaml
stress-tests/overlays/test/cronjob.yaml
user-api/overlays/test/kustomization.yaml

:sleeping: Hibernate all deployments and jobs in a test cluster
As a part of hibernation of the project

:sleeping: Hibernate all deployments and jobs in test cluster

---

amun/overlays/moc-prod/amun-api/secrets.enc.yaml
amun/overlays/ocp4-stage/amun-api/secrets.enc.yaml
amun/overlays/test/secrets.enc.yaml
core/overlays/moc-prod/common/secrets.enc.yaml
core/overlays/ocp4-stage/common/secrets.enc.yaml
core/overlays/test/secrets.enc.yaml
docs/thoth_logging.md
kebechet/overlays/moc-prod/secrets.enc.yaml
kebechet/overlays/ocp4-stage/secrets.enc.yaml
kebechet/overlays/test/secrets.enc.yaml
sefkhet-abwy-chatbot/overlays/moc/secrets.enc.yaml
sefkhet-abwy/overlays/moc/secrets.enc.yaml
sefkhet-abwy/overlays/ocp/secrets.enc.yaml

:sleeping: Turn off sentry logging by removing sentry_dsn
As part of the hibernation of the project.

:sleeping: Turn off sentry logging by removing sentry_dsn

---

core/overlays/ocp4-stage/common/secrets.enc.yaml
kafka/base/thoth-kafka.yaml

Upgrade kafka to 3.4.0 version for compatability with cluster amq

Upgrade kafka to 3.4.0 version for compatability with cluster amq
